/**
 * Curated PT-BR accent fixes for public-facing text emitted by scripts and legacy
 * mock/assertion sources. This is intentionally bounded to known patterns from the
 * project audit, not a generic autocorrect.
 */
const PTBR_TEXT_FIXES: Array<[string, string]> = [
  [" nao ", " não "],
  [" Nao ", " Não "],
  ["politico ", "político "],
  ["politica ", "política "],
  ["politicos ", "políticos "],
  ["politicas ", "políticas "],
  ["eleicao ", "eleição "],
  ["eleicoes ", "eleições "],
  ["filiacao ", "filiação "],
  ["atualizacao ", "atualização "],
  ["situacao ", "situação "],
  ["posicao ", "posição "],
  ["relacao ", "relação "],
  ["relacoes ", "relações "],
  ["gestao ", "gestão "],
  ["informacao ", "informação "],
  ["informacoes ", "informações "],
  ["denuncia ", "denúncia "],
  ["denuncias ", "denúncias "],
  ["corrupcao ", "corrupção "],
  ["acusacao ", "acusação "],
  ["condenacao ", "condenação "],
  ["investigacao ", "investigação "],
  ["organizacao ", "organização "],
  ["educacao ", "educação "],
  ["populacao ", "população "],
  ["migracao ", "migração "],
  ["votacao ", "votação "],
  ["fundacao ", "fundação "],
  ["participacao ", "participação "],
  ["Camara ", "Câmara "],
  ["atuacao ", "atuação "],
  ["nivel ", "nível "],
  ["Joao ", "João "],
  ["publico ", "público "],
  ["publica ", "pública "],
  ["Justica ", "Justiça "],
  ["Policia ", "Polícia "],
  ["patrimonio ", "patrimônio "],
  ["agronegocio ", "agronegócio "],
  ["atipicas ", "atípicas "],
  ["atipico ", "atípico "],
  ["seguranca ", "segurança "],
  ["experiencia ", "experiência "],
  ["historico ", "histórico "],
  ["movimentacoes ", "movimentações "],
  ["presidencia ", "presidência "],
  ["propria ", "própria "],
  ["proprio ", "próprio "],
  ["previdencia ", "previdência "],
  ["exercicio ", "exercício "],
  ["comunicacao ", "comunicação "],
  ["reeleicao ", "reeleição "],
  ["regiao ", "região "],
  ["influencia ", "influência "],
  ["reuniao ", "reunião "],
  ["acoes ", "ações "],
  ["operacao ", "operação "],
  ["declaracao ", "declaração "],
  ["associacao ", "associação "],
  ["variacao ", "variação "],
  ["aprovacao ", "aprovação "],
  ["integracao ", "integração "],
  ["licitacao ", "licitação "],
  ["oscilacao ", "oscilação "],
  ["recuperacao ", "recuperação "],
  ["reparacao ", "reparação "],
  ["representacao ", "representação "],
  ["valorizacao ", "valorização "],
  ["negociacao ", "negociação "],
  ["alfabetizacao ", "alfabetização "],
  ["atracao ", "atração "],
  ["dedetizacao ", "dedetização "],
  ["difamacao ", "difamação "],
  ["elaboracao ", "elaboração "],
  ["geracao ", "geração "],
  ["reducao ", "redução "],
  ["abolicao ", "abolição "],
  ["remocao ", "remoção "],
  ["aquisicao ", "aquisição "],
  ["privatizacao ", "privatização "],
  ["milhoes ", "milhões "],
  ["bilhoes ", "bilhões "],
  ["concessoes ", "concessões "],
  ["agressoes ", "agressões "],
  ["secretario ", "secretário "],
  ["salario ", "salário "],
  ["primario ", "primário "],
  ["possessorio ", "possessório "],
  ["previdenciario ", "previdenciário "],
  ["proprietario ", "proprietário "],
  ["agraria ", "agrária "],
  ["apartidaria ", "apartidária "],
  ["historia ", "história "],
  ["transparencia ", "transparência "],
  ["incompetencia ", "incompetência "],
  ["conveniencia ", "conveniência "],
  ["transferencia ", "transferência "],
  ["critico ", "crítico "],
  ["criticas ", "críticas "],
  ["basica ", "básica "],
  ["ciencia ", "ciência "],
  ["democratico ", "democrático "],
  ["medico ", "médico "],
  ["medica ", "médica "],
  ["jornalisticas ", "jornalísticas "],
  ["tambem ", "também "],
  ["porem ", "porém "],
  [" ate ", " até "],
  ["construida ", "construída "],
  ["incluido ", "incluído "],
  ["imovel ", "imóvel "],
  ["imoveis ", "imóveis "],
  ["depositos ", "depósitos "],
  ["industria ", "indústria "],
  ["lider ", "líder "],
  ["previas ", "prévias "],
  ["mansao ", "mansão "],
  ["mantem ", "mantém "],
  ["ameacas ", "ameaças "],
  ["indice ", "índice "],
  ["periodo ", "período "],
  ["saude ", "saúde "],
  ["Familia ", "Família "],
  ["familia ", "família "],
  ["marco/", "março/"],
  ["apos ", "após "],
  ["deficit ", "déficit "],
  ["minimo ", "mínimo "],
  ["decadas ", "décadas "],
  ["equilibrio ", "equilíbrio "],
  ["familias ", "famílias "],
  ["climatico ", "climático "],
  ["fundiarias ", "fundiárias "],
  ["adesao ", "adesão "],
  ["superavit ", "superávit "],
  ["milhao ", "milhão "],
  ["socias ", "sócias "],
  ["fundao ", "fundão "],
  ["jeronimo ", "jerônimo "],
  ["sebastiao ", "sebastião "],
  ["referencia ", "referência "],
  ["pressao ", "pressão "],
  ["entao ", "então "],
  ["transicao ", "transição "],
  ["reconstrucao ", "reconstrução "],
  ["missao ", "missão "],
  ["universitaria ", "universitária "],
  ["universitario ", "universitário "],
  ["inabilitacao ", "inabilitação "],
  ["sancao ", "sanção "],
  ["acordao ", "acórdão "],
  ["violencia ", "violência "],
  ["inflacao ", "inflação "],
  ["movimentacao ", "movimentação "],
  ["renovacao ", "renovação "],
  ["residencia ", "residência "],
  ["formacao ", "formação "],
  ["mobilizacao ", "mobilização "],
  ["redemocratizacao ", "redemocratização "],
  ["tendencia ", "tendência "],
  ["agencia ", "agência "],
  ["confirmacao ", "confirmação "],
  ["indicacao ", "indicação "],
  ["conceicao ", "conceição "],
  ["Republica", "República"],
  ["Uniao ", "União "],
  ["empresario ", "empresário "],
  ["empresaria ", "empresária "],
  ["turismologa ", "turismóloga "],
  ["musico ", "músico "],
  ["palacio ", "palácio "],
  ["renuncia ", "renúncia "],
  ["fusao ", "fusão "],
  ["alianca ", "aliança "],
  ["Maranhao", "Maranhão"],
  ["Rondonia", "Rondônia"],
  ["Amapa", "Amapá"],
  ["Goias", "Goiás"],
  ["Ceara", "Ceará"],
  ["Parana", "Paraná"],
  ["Piaui", "Piauí"],
  ["Paraiba", "Paraíba"],
  ["Vitoria", "Vitória"],
  ["Maceio", "Maceió"],
  ["Brasilia", "Brasília"],
  ["Guaruja", "Guarujá"],
  ["Arcabouco", "Arcabouço"],
  ["Sao Paulo", "São Paulo"],
  ["Democracia Crista", "Democracia Cristã"],
  ["Partido da Causa Operaria", "Partido da Causa Operária"],
  ["Partido Missao", "Partido Missão"],
]

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
}

function preserveCase(match: string, replacement: string): string {
  if (!match || !replacement) return replacement
  if (match[0] === match[0].toUpperCase() && replacement[0] !== replacement[0].toUpperCase()) {
    return replacement[0].toUpperCase() + replacement.slice(1)
  }
  return replacement
}

function replaceBoundedFix(text: string, from: string, to: string): string {
  const normalizedFrom = from.trim()
  const normalizedTo = to.trim()
  if (!normalizedFrom) return text

  const regex = new RegExp(
    `(?<!\\p{L})${escapeRegex(normalizedFrom)}(?=[^\\p{L}]|$)`,
    "giu"
  )

  return text.replace(regex, (match) => preserveCase(match, normalizedTo))
}

export function sanitizePtBrText(text: string): string {
  let result = text

  for (const [from, to] of PTBR_TEXT_FIXES) {
    result = replaceBoundedFix(result, from, to)
  }

  return result
}

export function sanitizeNullablePtBrText<T extends string | null | undefined>(value: T): T {
  if (typeof value !== "string") return value
  return sanitizePtBrText(value) as T
}
