import { sanitizeNullablePtBrText } from "../../src/lib/ptbr-text"
import type { CandidatePublicSnapshot } from "./audit-types"

export type AssertionCohort =
  | "presidenciaveis"
  | "governadores-prioritarios"
  | "governadores"
  // "alto-trafego" e mantido por compatibilidade de CLI e artefatos.
  // Conceitualmente esta coorte representa trafego editorial estimado,
  // nao analytics reais do site.
  | "alto-trafego"
  | "alto-trafego-editorial"

export type AssertionConfidence = "curated" | "mirrored"

export interface CandidateAssertion {
  slug: string
  source: string
  verifiedAt: string
  confidence: AssertionConfidence
  cohorts: AssertionCohort[]
  expected: Partial<CandidatePublicSnapshot>
  /**
   * Curadoria (confidence curated): cargos canônicos que devem existir no historico_politico,
   * alinhados a `canonicalCargo()` / coluna cargo_canonico. Ordem irrelevante.
   */
  expected_cargos?: string[]
}

interface CandidateAssertionInput extends Omit<CandidateAssertion, "verifiedAt"> {
  verifiedAt?: string
}

function normalizeExpectedCargos(cargos: string[] | undefined): string[] | undefined {
  if (!cargos?.length) return undefined
  return [...new Set(cargos.map((c) => c.trim()).filter(Boolean))].sort((a, b) =>
    a.localeCompare(b, "pt-BR")
  )
}

const DEFAULT_VERIFIED_AT = "2026-04-01"

function inferVerifiedAt(source: string, fallback = DEFAULT_VERIFIED_AT): string {
  const match = source.match(/\b(20\d{2}-\d{2}-\d{2})\b/)
  return match?.[1] ?? fallback
}

function sanitizeExpectedSnapshot(snapshot: Partial<CandidatePublicSnapshot>): Partial<CandidatePublicSnapshot> {
  return {
    ...snapshot,
    partido_atual: sanitizeNullablePtBrText(snapshot.partido_atual),
    cargo_atual: sanitizeNullablePtBrText(snapshot.cargo_atual),
    cargo_disputado: sanitizeNullablePtBrText(snapshot.cargo_disputado),
  }
}

const RAW_CANDIDATE_ASSERTIONS: CandidateAssertionInput[] = [
  {
    slug: "lula",
    source: "curadoria presidenciaveis",
    verifiedAt: "2026-04-01",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected_cargos: ["Presidente", "Deputado Federal"],
    expected: {
      nome_completo: "Luiz Inacio Lula da Silva",
      nome_urna: "Lula",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "flavio-bolsonaro",
    source: "curadoria presidenciaveis",
    verifiedAt: "2026-04-01",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Flavio Nantes Bolsonaro",
      nome_urna: "Flavio Bolsonaro",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "romeu-zema",
    source: "curadoria presidenciaveis",
    verifiedAt: "2026-04-01",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Romeu Zema Neto",
      nome_urna: "Romeu Zema",
      partido_atual: "Partido Novo",
      partido_sigla: "NOVO",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "ronaldo-caiado",
    source: "PSD oficial 2026-01-28",
    verifiedAt: "2026-04-01",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Ronaldo Ramos Caiado",
      nome_urna: "Ronaldo Caiado",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "ratinho-junior",
    source: "PSD oficial 2026-03-12",
    verifiedAt: "2026-04-01",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Carlos Roberto Massa Junior",
      nome_urna: "Ratinho Junior",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "aldo-rebelo",
    source: "DC oficial 2026-02-02",
    verifiedAt: "2026-04-01",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "José Aldo Rebelo Figueiredo",
      nome_urna: "Aldo Rebelo",
      partido_atual: "Democracia Crista",
      partido_sigla: "DC",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "renan-santos",
    source: "CNN Brasil 2026-03-30 + TSE Partido Missao",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Renan Antonio Ferreira dos Santos",
      nome_urna: "Renan Santos",
      partido_atual: "Missao",
      partido_sigla: "MISSAO",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "augusto-cury",
    source: "Avante oficial + Band 2026-05 + Wikipedia PT",
    verifiedAt: "2026-05-15",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Augusto Jorge Cury",
      nome_urna: "Augusto Cury",
      partido_atual: "Avante",
      partido_sigla: "AVANTE",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "cabo-daciolo",
    source: "Band 2026-04 + Camara dos Deputados + TSE 2018",
    verifiedAt: "2026-05-15",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Benevenuto Daciolo Fonseca dos Santos",
      nome_urna: "Cabo Daciolo",
      partido_atual: "Mobiliza",
      partido_sigla: "MOBILIZA",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "ciro-gomes",
    source: "PSDB oficial 2025-10-22",
    verifiedAt: "2026-04-01",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Ciro Ferreira Gomes",
      nome_urna: "Ciro Gomes",
      partido_atual: "Partido da Social Democracia Brasileira",
      partido_sigla: "PSDB",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "hertz-dias",
    source:
      "TSE consulta_cand 2022 reconciliado com o cadastro oficial materializado em 2026-07-11",
    verifiedAt: "2026-07-11",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "HERTZ DA CONCEICAO DIAS",
      nome_urna: "Hertz Dias",
      partido_atual: "Partido Socialista dos Trabalhadores Unificado",
      partido_sigla: "PSTU",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "rui-costa-pimenta",
    source: "curadoria presidenciaveis",
    verifiedAt: "2026-04-01",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Rui Costa Pimenta",
      nome_urna: "Rui Costa Pimenta",
      partido_atual: "Partido da Causa Operaria",
      partido_sigla: "PCO",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "edmilson-costa",
    source: "PCB oficial 2026-02 + FAPESP + Wikipedia PT",
    verifiedAt: "2026-05-15",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Edmilson Silva Costa",
      nome_urna: "Edmilson Costa",
      partido_atual: "Partido Comunista Brasileiro",
      partido_sigla: "PCB",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "samara-martins",
    source: "TSE consulta_cand 2022 reconciliado com o cadastro oficial materializado em 2026-07-11",
    verifiedAt: "2026-07-11",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "SAMARA MARTINS DA SILVA",
      nome_urna: "Samara Martins",
      partido_atual: "Unidade Popular",
      partido_sigla: "UP",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "tarcisio-gov-sp",
    source: "Governo de SP + Republicanos oficial 2026-03",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Tarcísio Gomes de Freitas",
      nome_urna: "Tarcísio de Freitas",
      partido_atual: "Republicanos",
      partido_sigla: "REPUBLICANOS",
      cargo_atual: "Governador de Sao Paulo",
      cargo_disputado: "Governador",
      estado: "SP",
    },
  },
  {
    slug: "nikolas-ferreira",
    source: "Camara dos Deputados 2026-03-31",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Nikolas Ferreira Oliveira",
      nome_urna: "Nikolas Ferreira",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_atual: "Deputado(a) Federal",
      cargo_disputado: "Governador",
      estado: "MG",
    },
  },
  {
    slug: "rodrigo-pacheco",
    source: "Senado Federal 2026-03-31",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Rodrigo Pacheco Amaral",
      nome_urna: "Rodrigo Pacheco",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_atual: "Senador(a)",
      cargo_disputado: "Governador",
      estado: "MG",
    },
  },
  {
    slug: "eduardo-paes",
    source: "Prefeitura do Rio + PSD oficial 2026-03",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Eduardo da Costa Paes",
      nome_urna: "Eduardo Paes",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_atual: "Prefeito do Rio de Janeiro",
      cargo_disputado: "Governador",
      estado: "RJ",
    },
  },
  {
    slug: "jeronimo",
    source:
      "Governo da Bahia oficial + FIX apply-current-factual-fixes canonicaliza nome legal 'Jerônimo Rodrigues Souza'; substitui 'Jeronimo Rodrigues de Jesus' (nao corroborada por fonte oficial)",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Jerônimo Rodrigues Souza",
      nome_urna: "Jeronimo",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_atual: "Governador da Bahia",
      cargo_disputado: "Governador",
      estado: "BA",
    },
  },
  {
    slug: "elmano-de-freitas",
    source: "Governo do Ceara + PT Ceara 2026-03",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Elmano de Freitas da Costa",
      nome_urna: "Elmano de Freitas",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_atual: "Governador do Ceara",
      cargo_disputado: "Governador",
      estado: "CE",
    },
  },
  {
    slug: "joao-campos",
    source: "Prefeitura do Recife + PSB oficial 2026-03",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Joao Henrique de Andrade Lima Campos",
      nome_urna: "Joao Campos",
      partido_atual: "Partido Socialista Brasileiro",
      partido_sigla: "PSB",
      cargo_atual: "Prefeito do Recife",
      cargo_disputado: "Governador",
      estado: "PE",
    },
  },
  {
    slug: "raquel-lyra",
    source: "Governo de Pernambuco + PSD oficial 2026-03",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Raquel Teixeira Lyra Lucena",
      nome_urna: "Raquel Lyra",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_atual: "Governadora de Pernambuco",
      cargo_disputado: "Governador",
      estado: "PE",
    },
  },
  {
    slug: "cleitinho",
    source: "Senado Federal 2026-03-31",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Cleiton Gontijo de Azevedo",
      nome_urna: "Cleitinho",
      partido_atual: "Republicanos",
      partido_sigla: "REPUBLICANOS",
      cargo_atual: "Senador(a)",
      cargo_disputado: "Governador",
      estado: "MG",
    },
  },
  {
    slug: "sergio-moro-gov-pr",
    source: "Senado Federal 2026-04-01",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Sergio Fernando Moro",
      nome_urna: "Sergio Moro",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_atual: "Senador(a)",
      cargo_disputado: "Governador",
      estado: "PR",
    },
  },
  {
    slug: "jorginho-mello",
    source: "Governo de Santa Catarina + ALESC oficial 2026-03",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Jorginho dos Santos Mello",
      nome_urna: "Jorginho Mello",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_atual: "Governador de Santa Catarina",
      cargo_disputado: "Governador",
      estado: "SC",
    },
  },
  {
    slug: "ricardo-nunes",
    source: "Prefeitura de Sao Paulo 2026-03-31",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Ricardo Luis Reis Nunes",
      nome_urna: "Ricardo Nunes",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_atual: "Prefeito de Sao Paulo",
      cargo_disputado: "Governador",
      estado: "SP",
    },
  },
  {
    slug: "haddad-gov-sp",
    source: "DOU 2026-03-19 + AP News",
    verifiedAt: "2026-04-10",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Fernando Haddad",
      nome_urna: "Fernando Haddad",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_disputado: "Governador",
      estado: "SP",
    },
  },
  {
    slug: "erika-hilton",
    source: "Camara dos Deputados 2026-03-31",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Erika Santos Silva",
      nome_urna: "Erika Hilton",
      partido_atual: "Partido Socialismo e Liberdade",
      partido_sigla: "PSOL",
      cargo_atual: "Deputado(a) Federal",
      cargo_disputado: "Governador",
      estado: "SP",
    },
  },
  {
    slug: "geraldo-alckmin",
    source: "Vice-Presidencia + PSB oficial 2026-03",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Geraldo José Rodrigues Alckmin Filho",
      nome_urna: "Geraldo Alckmin",
      partido_atual: "Partido Socialista Brasileiro",
      partido_sigla: "PSB",
      cargo_atual: "Vice-Presidente da Republica",
      cargo_disputado: "Governador",
      estado: "SP",
    },
  },
  {
    slug: "ciro-gomes-gov-ce",
    source: "PSDB oficial 2025-10-22",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Ciro Ferreira Gomes",
      nome_urna: "Ciro Gomes",
      partido_atual: "Partido da Social Democracia Brasileira",
      partido_sigla: "PSDB",
      cargo_atual: null,
      cargo_disputado: "Governador",
      estado: "CE",
    },
  },
  {
    slug: "alan-rick",
    source: "Senado Federal oficial + ContilNet 2026-04-02",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Alan Rick Pereira da Silva",
      nome_urna: "Alan Rick",
      partido_atual: "Republicanos",
      partido_sigla: "REPUBLICANOS",
      cargo_atual: "Senador(a)",
      cargo_disputado: "Governador",
      estado: "AC",
    },
  },
  {
    slug: "andre-kamai",
    source:
      "ac24horas.com 2024-10-07 + SAPL Camara de Rio Branco 2026-04-11; FIX apply-current-factual-fixes consolidou nome legal 'Andre Kamai da Silva Soares' e pleito 2026 a Deputado Federal",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Andre Kamai da Silva Soares",
      nome_urna: "Andre Kamai",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_atual: "Vereador de Rio Branco (AC)",
      cargo_disputado: "Deputado Federal",
      estado: "AC",
    },
  },
  {
    slug: "mailza-assis",
    source: "Agencia de Noticias do Acre 2026-04-02",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Mailza Gomes Assis",
      nome_urna: "Mailza Assis",
      partido_atual: "Progressistas",
      partido_sigla: "PP",
      cargo_atual: "Governadora do Estado do Acre",
      cargo_disputado: "Governador",
      estado: "AC",
    },
  },
  {
    slug: "tiao-bocalom",
    source: "filiacao PSDB mar/2026 confirmada",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Sebastiao Bocalom Rodrigues",
      nome_urna: "Tiao Bocalom",
      partido_atual: "Partido da Social Democracia Brasileira",
      partido_sigla: "PSDB",
      cargo_disputado: "Governador",
      estado: "AC",
    },
  },
  {
    slug: "jhc",
    source:
      "FIX apply-current-factual-fixes (saiu do PL em 2026 e filiou-se ao PSDB; deixou a Prefeitura de Maceio em 04/04/2026 para disputar 2026); substitui assertion anterior (PL + Prefeito) que refletia estado pre-troca",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Joao Henrique Caldas",
      nome_urna: "JHC",
      partido_atual: "Partido da Social Democracia Brasileira",
      partido_sigla: "PSDB",
      cargo_disputado: "Governador",
      estado: "AL",
    },
  },
  {
    slug: "renan-filho",
    source:
      "Senado Federal oficial + FIX apply-current-factual-fixes: deixou o Ministerio dos Transportes em marco/2026 e reassumiu mandato de senador por AL para disputar 2026",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Renan Calheiros Filho",
      nome_urna: "Renan Filho",
      partido_atual: "MDB",
      partido_sigla: "MDB",
      cargo_atual: "Senador(a)",
      cargo_disputado: "Governador",
      estado: "AL",
    },
  },
  {
    slug: "david-almeida",
    source:
      "Prefeitura de Manaus oficial + A Critica 2026-02-23; FIX apply-current-factual-fixes canonicaliza nome legal 'David Antônio Abisai Pereira de Almeida' e renúncia à Prefeitura de Manaus em 31/03/2026",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "David Antônio Abisai Pereira de Almeida",
      nome_urna: "David Almeida",
      partido_atual: "Avante",
      partido_sigla: "AVANTE",
      cargo_disputado: "Governador",
      estado: "AM",
    },
  },
  {
    slug: "eduardo-braga",
    source:
      "Senado Federal oficial + Em Tempo 2026-03-01; FIX apply-current-factual-fixes consolidou reeleicao ao Senado (cargo_disputado=Senador)",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Eduardo Braga Granata",
      nome_urna: "Eduardo Braga",
      partido_atual: "MDB",
      partido_sigla: "MDB",
      cargo_atual: "Senador(a)",
      cargo_disputado: "Senador",
      estado: "AM",
    },
  },
  {
    slug: "maria-do-carmo",
    source: "Em Tempo + Agencia Cenarium 2025-01-01 + TSE DivulgaCand 2022 AM (curadoria 2026-04-15)",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Maria do Carmo Seffair",
      nome_urna: "Maria do Carmo",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "AM",
    },
  },
  {
    slug: "omar-aziz",
    source: "Senado Federal oficial + A Critica 2025-04-25",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Omar Jose Abdel Aziz",
      nome_urna: "Omar Aziz",
      partido_atual: "PSD",
      partido_sigla: "PSD",
      cargo_atual: "Senador(a)",
      cargo_disputado: "Governador",
      estado: "AM",
    },
  },
  {
    slug: "tadeu-de-souza",
    source:
      "TSE 2022 SQ 40001619527 + A Crítica filiação PP 2026 + deAmazônia entrevista posterior à renúncia indicando pré-candidatura a deputado federal",
    verifiedAt: "2026-05-17",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Tadeu de Souza Silva",
      nome_urna: "Tadeu de Souza",
      partido_atual: "Progressistas",
      partido_sigla: "PP",
      cargo_disputado: "Deputado Federal",
      estado: "AM",
    },
  },
  {
    slug: "clecio-luis",
    source: "G1 AP 2026-01-30 + site União Brasil (filiacao confirmada)",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Clecio Luis Vilhena Vieira",
      nome_urna: "Clecio Luis",
      partido_atual: "União Brasil",
      partido_sigla: "UNIAO",
      cargo_disputado: "Governador",
      estado: "AP",
    },
  },
  {
    slug: "dr-furlan",
    source: "CNN Brasil 2026-03-04 + UOL/Parana Pesquisas 2026-03-17",
    verifiedAt: "2026-05-20",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Jose Antonio D Almeida Furlan",
      nome_urna: "Dr. Furlan",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Governador",
      estado: "AP",
    },
  },
  {
    slug: "joao-capiberibe",
    source: "Senado Federal perfil + Ricardo Antunes 2026-02-01",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Joao Alberto Rodrigues Capiberibe",
      nome_urna: "Joao Capiberibe",
      partido_atual: "PSB",
      partido_sigla: "PSB",
      cargo_disputado: "Governador",
      estado: "AP",
    },
  },
  {
    slug: "acm-neto",
    source: "O Globo 2024-11-12 + PSNoticias 2026-03-30",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Antônio Carlos Peixoto de Magalhães Neto",
      nome_urna: "ACM Neto",
      partido_atual: "Uniao Brasil",
      partido_sigla: "UNIAO",
      cargo_disputado: "Governador",
      estado: "BA",
    },
  },
  {
    slug: "joao-roma",
    source: "Camara.leg.br + Bahia Noticias 2025-02-01 + curadoria junho 2026: nao manter como governador sem fonte recente",
    verifiedAt: "2026-06-29",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "João Inácio Ribeiro Roma Neto",
      nome_urna: "Joao Roma",
      partido_atual: "PL",
      partido_sigla: "PL",
      cargo_disputado: "Senador",
      estado: "BA",
    },
  },
  {
    slug: "jose-carlos-aleluia",
    source:
      "Câmara dos Deputados + NOVO/MundoBA/Plenna News 2025-2026; curadoria S15.3 lote 4: filiacao NOVO confirmada, pre-candidatura retirada em 2026",
    verifiedAt: "2026-04-27",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "José Carlos Aleluia Costa",
      nome_urna: "Jose Carlos Aleluia",
      partido_atual: "Partido Novo",
      partido_sigla: "NOVO",
      cargo_disputado: "Nenhum",
      estado: "BA",
    },
  },
  {
    slug: "ronaldo-mansur",
    source: "Bahia Noticias 2025-09-01 + A Tarde 2025-12-01",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Ronaldo Mansur",
      nome_urna: "Ronaldo Mansur",
      partido_atual: "Partido Socialismo e Liberdade",
      partido_sigla: "PSOL",
      cargo_disputado: "Governador",
      estado: "BA",
    },
  },
  {
    slug: "capitao-wagner",
    source: "WORKFLOWS 2026-06-23 radar/publicacao",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Wagner Sousa Gomes",
      nome_urna: "Capitão Wagner",
      partido_atual: "Uniao Brasil",
      partido_sigla: "UNIAO",
      cargo_disputado: "Senador",
      estado: "CE",
    },
  },
  {
    slug: "eduardo-girao",
    source:
      "Senado Federal oficial + FIX apply-current-factual-fixes canonicaliza nome legal 'Luís Eduardo Grangeiro Girão' (senador por CE pelo NOVO, pre-candidato 2026); substitui 'Eduardo Girao Monteiro Filho' (possível homônimo ou erro de curadoria)",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Luís Eduardo Grangeiro Girão",
      nome_urna: "Eduardo Girao",
      partido_atual: "NOVO",
      partido_sigla: "NOVO",
      cargo_atual: "Senador(a)",
      cargo_disputado: "Governador",
      estado: "CE",
    },
  },
  {
    slug: "roberto-claudio",
    source: "CN7 2025-11-05 + O Povo 2025-04-28",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Roberto Cláudio Rodrigues Bezerra",
      nome_urna: "Roberto Claudio",
      partido_atual: "Uniao Brasil",
      partido_sigla: "UNIAO",
      cargo_disputado: "Governador",
      estado: "CE",
    },
  },
  {
    slug: "celina-leao",
    source: "GDF oficial + Correio Braziliense 2026-04-02",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Celina Leao Rocha de Siqueira Campos",
      nome_urna: "Celina Leao",
      partido_atual: "Progressistas",
      partido_sigla: "PP",
      cargo_atual: "Vice-Governadora do Distrito Federal",
      cargo_disputado: "Governador",
      estado: "DF",
    },
  },
  {
    slug: "leandro-grass",
    source: "Metropoles + Brasil 247 02/04/2026",
    verifiedAt: "2026-04-10",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Leandro Grass Peixoto",
      nome_urna: "Leandro Grass",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_disputado: "Governador",
      estado: "DF",
    },
  },
  {
    slug: "paula-belmonte",
    source: "CLDF 2025-12-23",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Paula Francinete Belmonte da Silva",
      nome_urna: "Paula Belmonte",
      partido_atual: "Partido da Social Democracia Brasileira",
      partido_sigla: "PSDB",
      cargo_disputado: "Governador",
      estado: "DF",
    },
  },
  {
    slug: "ricardo-cappelli",
    source: "Metropoles 2026-04-02 + Correio Braziliense 2026-02-09",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Ricardo Ribeiro Cappelli",
      nome_urna: "Ricardo Cappelli",
      partido_atual: "Partido Socialista Brasileiro",
      partido_sigla: "PSB",
      cargo_disputado: "Governador",
      estado: "DF",
    },
  },
  {
    slug: "arnaldinho-borgo",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Arnaldinho Borgo",
      nome_urna: "Arnaldinho Borgo",
      partido_atual: "Partido da Social Democracia Brasileira",
      partido_sigla: "PSDB",
      cargo_disputado: "Governador",
      estado: "ES",
    },
  },
  {
    slug: "da-vitoria",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Josias da Vitoria",
      nome_urna: "Da Vitoria",
      partido_atual: "PP",
      partido_sigla: "PP",
      cargo_disputado: "Governador",
      estado: "ES",
    },
  },
  {
    slug: "helder-salomao",
    source: "Camara dos Deputados oficial + Folha Vitoria 2026-02-11",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Helder Ignácio Salomão",
      nome_urna: "Helder Salomão",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_atual: "Deputado(a) Federal",
      cargo_disputado: "Governador",
      estado: "ES",
    },
  },
  {
    slug: "paulo-hartung",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Paulo Cesar Hartung Gomes",
      nome_urna: "Paulo Hartung",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Governador",
      estado: "ES",
    },
  },
  {
    slug: "pazolini",
    source: "Camara Municipal de Vitoria oficial 2026-04-01 + historico TSE materializado",
    verifiedAt: "2026-07-11",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Lorenzo Pazolini",
      nome_urna: "Pazolini",
      partido_atual: "Republicanos",
      partido_sigla: "REPUBLICANOS",
      cargo_atual: null,
      cargo_disputado: "Governador",
      estado: "ES",
    },
  },
  {
    slug: "ricardo-ferraco",
    source: "filiacao MDB confirmada",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Ricardo de Rezende Ferraço",
      nome_urna: "Ricardo Ferraço",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "ES",
    },
  },
  {
    slug: "sergio-vidigal",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Sergio Vidigal",
      nome_urna: "Sergio Vidigal",
      partido_atual: "PDT",
      partido_sigla: "PDT",
      cargo_disputado: "Governador",
      estado: "ES",
    },
  },
  {
    slug: "adriana-accorsi",
    source: "Camara dos Deputados oficial 2026-04-02",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Adriana Accorsi de Queiroz",
      nome_urna: "Adriana Accorsi",
      partido_atual: "PT",
      partido_sigla: "PT",
      cargo_atual: "Deputada Federal por Goias",
      cargo_disputado: "Governador",
      estado: "GO",
    },
  },
  {
    slug: "daniel-vilela",
    source: "Governo de Goias oficial + Jornal Opcao 2026-04-02",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Daniel Goulart Vilela",
      nome_urna: "Daniel Vilela",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_atual: "Vice-Governador de Goias",
      cargo_disputado: "Governador",
      estado: "GO",
    },
  },
  {
    slug: "jose-eliton",
    source: "Gazeta do Povo + Jornal Opcao 2026-01-01",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Jose Eliton de Figueredo Telles Junior",
      nome_urna: "Jose Eliton",
      partido_atual: "Partido Socialista Brasileiro",
      partido_sigla: "PSB",
      cargo_disputado: "Governador",
      estado: "GO",
    },
  },
  {
    slug: "marconi-perillo",
    source: "Jornal Opcao 2025-09-27",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Marconi Ferreira Perillo Junior",
      nome_urna: "Marconi Perillo",
      partido_atual: "PSDB",
      partido_sigla: "PSDB",
      cargo_disputado: "Governador",
      estado: "GO",
    },
  },
  {
    slug: "wilder-morais",
    source: "Senado Federal oficial + Mais Goias 2026-04-02",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Wilder Gomes de Morais",
      nome_urna: "Wilder Morais",
      partido_atual: "PL",
      partido_sigla: "PL",
      cargo_atual: "Senador(a)",
      cargo_disputado: "Governador",
      estado: "GO",
    },
  },
  {
    slug: "eduardo-braide",
    source: "Diario Oficial Sao Luis 53821 + carta renuncia 31/03/2026",
    verifiedAt: "2026-04-10",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Eduardo Costa Braide",
      nome_urna: "Eduardo Braide",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Governador",
      estado: "MA",
    },
  },
  {
    slug: "enilton-rodrigues",
    source: "Imirante.com 2026-03-09 + PSOL.org.br 2026",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Enilton Rodrigues",
      nome_urna: "Enilton Rodrigues",
      partido_atual: "Partido Socialismo e Liberdade",
      partido_sigla: "PSOL",
      cargo_disputado: "Governador",
      estado: "MA",
    },
  },
  {
    slug: "felipe-camarao",
    source: "Sedihpop.ma.gov.br 2023-01-01 + PT.org.br 2025-01-01",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Felipe Costa Camarão",
      nome_urna: "Felipe Camarão",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_atual: "Vice-Governador do Maranhao",
      cargo_disputado: "Governador",
      estado: "MA",
    },
  },
  {
    slug: "lahesio-bonfim",
    source:
      "FIX apply-current-factual-fixes atualizado por Imirante 2026-06-11: movimento ligado ao Senado; nao manter como governador sem fonte posterior",
    verifiedAt: "2026-06-29",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Lahesio Rodrigues Bonfim",
      nome_urna: "Lahesio Bonfim",
      cargo_disputado: "Senador",
      estado: "MA",
    },
  },
  {
    slug: "orleans-brandao",
    source:
      "FIX apply-current-factual-fixes canonicaliza nome legal 'Carlos Orleans Brandão Junior' (Governador do MA, articula reeleicao); substitui 'Orleans Torres Ribeiro Brandao' (nao corroborada)",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Carlos Orleans Brandão Junior",
      nome_urna: "Orleans Brandao",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "MA",
    },
  },
  {
    slug: "gabriel-azevedo",
    source: "O Tempo 2022 perfil civil + O Tempo 2025-11-04 + R7 2026-04-28",
    verifiedAt: "2026-05-20",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Gabriel Sousa Marques de Azevedo",
      nome_urna: "Gabriel Azevedo",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "MG",
    },
  },
  {
    slug: "maria-da-consolacao",
    source: "O Tempo 2026-01-07 + PSOL MG (lançamento formal) + TSE DivulgaCandContas (curadoria trajetória 2026-04-15)",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Maria da Consolação Soares",
      nome_urna: "Maria da Consolação",
      partido_atual: "Partido Socialismo e Liberdade",
      partido_sigla: "PSOL",
      cargo_disputado: "Governador",
      estado: "MG",
    },
  },
  {
    slug: "mateus-simoes",
    source: "MG.GOV oficial + Prefeitura de Claraval 2026-03-23",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Mateus Simões",
      nome_urna: "Mateus Simões",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_atual: "Governador de Minas Gerais",
      cargo_disputado: "Governador",
      estado: "MG",
    },
  },
  {
    slug: "eduardo-riedel",
    source: "Governo de MS oficial + Campo Grande News 2026-04-02",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Eduardo Correa Riedel",
      nome_urna: "Eduardo Riedel",
      partido_atual: "Progressistas",
      partido_sigla: "PP",
      cargo_atual: "Governador do Mato Grosso do Sul",
      cargo_disputado: "Governador",
      estado: "MS",
    },
  },
  {
    slug: "fabio-trad",
    source: "filiacao PT confirmada",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Fabio Trad",
      nome_urna: "Fabio Trad",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_disputado: "Governador",
      estado: "MS",
    },
  },
  {
    slug: "joao-henrique-catan",
    source: "Capital News 2026-03-08 + NOVO oficial 2026",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Joao Henrique Catan",
      nome_urna: "Joao Henrique Catan",
      partido_atual: "Partido Novo",
      partido_sigla: "NOVO",
      cargo_disputado: "Governador",
      estado: "MS",
    },
  },
  {
    slug: "lucien-rezende",
    source: "Correio do Estado 2026-01-25 + Midiamax 2026-01-25",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Lucien Miranda de Rezende",
      nome_urna: "Lucien Rezende",
      partido_atual: "Partido Socialismo e Liberdade",
      partido_sigla: "PSOL",
      cargo_disputado: "Governador",
      estado: "MS",
    },
  },
  {
    slug: "janaina-riva",
    source:
      "FIX apply-current-factual-fixes (Senador MT) + curadoria 2026-04-14; assertion anterior O Livre 2025/PNB 2026 previa Governador mas curadoria mais recente consolidou pleito ao Senado",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Janaina Riva",
      nome_urna: "Janaina Riva",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_disputado: "Senador",
      estado: "MT",
    },
  },
  {
    slug: "natasha-slhessarenko",
    source: "PNB Online 2026-03-15 + MidiaNews 2025-10-28",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Natasha Slhessarenko",
      nome_urna: "Natasha Slhessarenko",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Governador",
      estado: "MT",
    },
  },
  {
    slug: "otaviano-pivetta",
    source: "ALMT posse 2026-03-31 + Republicanos10 2026-03-31",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Otaviano Pivetta",
      nome_urna: "Otaviano Pivetta",
      partido_atual: "Republicanos",
      partido_sigla: "REPUBLICANOS",
      cargo_atual: "Governador de Mato Grosso",
      cargo_disputado: "Governador",
      estado: "MT",
    },
  },
  {
    slug: "wellington-fagundes",
    source: "Senado Federal oficial + O Documento 2026-01-01",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Wellington Fagundes",
      nome_urna: "Wellington Fagundes",
      partido_atual: "PL",
      partido_sigla: "PL",
      cargo_atual: "Senador(a)",
      cargo_disputado: "Governador",
      estado: "MT",
    },
  },
  {
    slug: "beto-faro",
    source: "O Liberal PA 2023 + Brasil 247 2026",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Jose Beto Faro Pereira",
      nome_urna: "Beto Faro",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_atual: "Senador",
      cargo_disputado: "Governador",
      estado: "PA",
    },
  },
  {
    slug: "delegado-eder-mauro",
    source:
      "Camara dos Deputados oficial + Band 2026-03-26; FIX apply-current-factual-fixes confirma pleito Senado PA (alinhado a lancamento do PL em 2026)",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Eder Braga Mauro",
      nome_urna: "Delegado Eder Mauro",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_atual: "Deputado(a) Federal",
      cargo_disputado: "Senador",
      estado: "PA",
    },
  },
  {
    slug: "dr-daniel",
    source: "DO Municipal Ananindeua 03/04/2026",
    verifiedAt: "2026-04-10",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Daniel Barbosa Santos",
      nome_urna: "Dr. Daniel",
      partido_atual: "Podemos",
      partido_sigla: "PODEMOS",
      cargo_disputado: "Governador",
      estado: "PA",
    },
  },
  {
    slug: "hana-ghassan",
    source: "Governo do Para oficial + O Liberal 2026-03-16",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Hana Ghassan Tuma",
      nome_urna: "Hana Ghassan",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_atual: "Vice-Governadora do Para",
      cargo_disputado: "Governador",
      estado: "PA",
    },
  },
  {
    slug: "simao-jatene",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Simao Robison Oliveira Jatene",
      nome_urna: "Simao Jatene",
      partido_atual: "Partido da Social Democracia Brasileira",
      partido_sigla: "PSDB",
      cargo_disputado: "Governador",
      estado: "PA",
    },
  },
  {
    slug: "cicero-lucena",
    source: "filiacao MDB set/2025 confirmada",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Cicero de Lucena Filho",
      nome_urna: "Cicero Lucena",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "PB",
    },
  },
  {
    slug: "efraim-filho",
    source: "Senado Federal 2026-04-01 + curadoria trajetória 2026-04-12 (PL)",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Efraim de Araujo Morais Filho",
      nome_urna: "Efraim Filho",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "PB",
    },
  },
  {
    slug: "lucas-ribeiro",
    source: "Governo da Paraiba oficial 2026-04-08",
    verifiedAt: "2026-04-10",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Lucas Ribeiro",
      nome_urna: "Lucas Ribeiro",
      partido_atual: "Progressistas",
      partido_sigla: "PP",
      cargo_atual: "Governador da Paraiba",
      cargo_disputado: "Governador",
      estado: "PB",
    },
  },
  {
    slug: "pedro-cunha-lima",
    source:
      "Portal da Paraiba / Correio da Paraiba 2026 + FIX apply-current-factual-fixes (status=desistente, cargo_disputado=Nenhum); substitui MaisPB 2025-11-01 (anuncio anterior de nao disputa em 2026)",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Pedro Cunha Lima",
      nome_urna: "Pedro Cunha Lima",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Nenhum",
      estado: "PB",
    },
  },
  {
    slug: "anderson-ferreira",
    source:
      "WORKFLOWS 2026-06-04 audit:published-consistency: candidatos_publico anon saneado Senador -> Deputado Federal",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Anderson Ferreira de Alencar",
      nome_urna: "Anderson Ferreira",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Deputado Federal",
      estado: "PE",
    },
  },
  {
    slug: "gilson-machado",
    source: "banco auditado 2026-04-01 + curadoria junho 2026: nao manter como governador sem fonte recente",
    verifiedAt: "2026-06-29",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Gilson Machado Guimaraes Neto",
      nome_urna: "Gilson Machado",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Senador",
      estado: "PE",
    },
  },
  {
    slug: "ivan-moraes",
    source: "PSOL PE 2026 + CBN Recife 2026-03-24",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Ivan Moraes Filho",
      nome_urna: "Ivan Moraes",
      partido_atual: "Partido Socialismo e Liberdade",
      partido_sigla: "PSOL",
      cargo_disputado: "Governador",
      estado: "PE",
    },
  },
  {
    slug: "joel-rodrigues",
    source:
      "FIX apply-current-factual-fixes canonicaliza nome legal 'Joel Rodrigues de Castro' (ex-vereador, ex-prefeito de Floriano e suplente de senador); substitui 'Joel Rodrigues da Silva' (nao corroborada)",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Joel Rodrigues de Castro",
      nome_urna: "Joel Rodrigues",
      partido_atual: "Progressistas",
      partido_sigla: "PP",
      cargo_disputado: "Governador",
      estado: "PI",
    },
  },
  {
    slug: "margarete-coelho",
    source: "GP1 2026-01-20 + Parlamento Piaui 2026-01-12",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Margarete de Castro Coelho",
      nome_urna: "Margarete Coelho",
      partido_atual: "PP",
      partido_sigla: "PP",
      cargo_disputado: "Governador",
      estado: "PI",
    },
  },
  {
    slug: "rafael-fonteles",
    source: "Governo do Piaui oficial + GP1 2026-04-02",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Rafael Tajra Fonteles",
      nome_urna: "Rafael Fonteles",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_atual: "Governador do Piaui",
      cargo_disputado: "Governador",
      estado: "PI",
    },
  },
  {
    slug: "silvio-mendes",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Silvio Mendes de Oliveira Filho",
      nome_urna: "Silvio Mendes",
      partido_atual: "Uniao Brasil",
      partido_sigla: "UNIAO",
      cargo_disputado: "Governador",
      estado: "PI",
    },
  },
  {
    slug: "alexandre-curi",
    source:
      "ALEP oficial + Bem Parana 2026-04-02; FIX apply-current-factual-fixes consolida filiação ao Republicanos em 2026 (deixou o PSD para disputar o governo); assertion anterior refletia estado pre-troca",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Alexandre Curi",
      nome_urna: "Alexandre Curi",
      partido_atual: "Republicanos",
      partido_sigla: "REPUBLICANOS",
      cargo_atual: "Presidente da Assembleia Legislativa do Parana",
      cargo_disputado: "Governador",
      estado: "PR",
    },
  },
  {
    slug: "guto-silva",
    source:
      "CBN Maringa 2026-05-12; prelaunch final launch closure 2026-05-20 consolidou pre-candidatura ao Senado pelo PSD",
    verifiedAt: "2026-05-20",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Luiz Augusto Silva",
      nome_urna: "Guto Silva",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Senador",
      estado: "PR",
    },
  },
  {
    slug: "paulo-martins-gov-pr",
    source: "Prefeitura de Curitiba oficial 2025-01-01 + NOVO oficial 2025-07-23 + RIC 2025-08-11",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Paulo Martins",
      nome_urna: "Paulo Martins",
      partido_atual: "Partido Novo",
      partido_sigla: "NOVO",
      cargo_atual: "Vice-prefeito de Curitiba",
      cargo_disputado: "Governador",
      estado: "PR",
    },
  },
  {
    slug: "rafael-greca",
    source: "filiacao MDB mar/2026 confirmada",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Rafael Valdomiro Greca de Macedo",
      nome_urna: "Rafael Greca",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "PR",
    },
  },
  {
    slug: "requiao-filho",
    source: "Brasil de Fato 2025-05-09 + Brasil de Fato 2026-03-31",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Mauricio Thadeu de Mello e Silva",
      nome_urna: "Requiao Filho",
      partido_atual: "Partido Democratico Trabalhista",
      partido_sigla: "PDT",
      cargo_disputado: "Governador",
      estado: "PR",
    },
  },
  {
    slug: "douglas-ruas",
    source: "Agencia Brasil 2026-03 + Portal Multiplix 2026-02-24",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Douglas Ruas dos Santos",
      nome_urna: "Douglas Ruas",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "RJ",
    },
  },
  {
    slug: "garotinho",
    source:
      "TSE consulta_cand 1998/2002/2010/2014/2018/2022/2024 + Câmara dos Deputados oficial id 160539 + Folha1 2026-04-16",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Anthony William Garotinho Matheus de Oliveira",
      nome_urna: "Garotinho",
      partido_atual: "Republicanos",
      partido_sigla: "REPUBLICANOS",
      cargo_disputado: "Governador",
      estado: "RJ",
    },
  },
  {
    slug: "rodrigo-bacellar",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Rodrigo Bacellar",
      nome_urna: "Rodrigo Bacellar",
      partido_atual: "Uniao Brasil",
      partido_sigla: "UNIAO",
      cargo_disputado: "Governador",
      estado: "RJ",
    },
  },
  {
    slug: "tarcisio-motta",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Tarcisio Motta de Carvalho",
      nome_urna: "Tarcisio Motta",
      partido_atual: "PSOL",
      partido_sigla: "PSOL",
      cargo_disputado: "Governador",
      estado: "RJ",
    },
  },
  {
    slug: "washington-reis",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Washington Reis de Oliveira",
      nome_urna: "Washington Reis",
      partido_atual: "MDB",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "RJ",
    },
  },
  {
    slug: "alvaro-dias-rn",
    source: "Agora RN 2026-03-23 + curadoria trajetória 2026-04-15 (cadeia partidária ALERN/TSE)",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Alvaro Costa Dias",
      nome_urna: "Alvaro Dias",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "RN",
    },
  },
  {
    slug: "alysson-bezerra",
    source:
      "FIX apply-current-factual-fixes canonicaliza nome legal 'Alysson Leandro Barbate Bezerra' (Prefeito de Mossoró reeleito, pré-candidato ao governo RN); substitui 'Allyson Leandro Bezerra Silva' (nao corroborada)",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Alysson Leandro Barbate Bezerra",
      nome_urna: "Alysson Bezerra",
      partido_atual: "Uniao Brasil",
      partido_sigla: "UNIAO",
      cargo_disputado: "Governador",
      estado: "RN",
    },
  },
  {
    slug: "cadu-xavier",
    source: "DOE/RN edicao extra 31/03/2026 + 98 FM Natal",
    verifiedAt: "2026-04-10",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Carlos Eduardo Xavier",
      nome_urna: "Cadu Xavier",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_disputado: "Governador",
      estado: "RN",
    },
  },
  {
    slug: "adailton-furia",
    source: "DO Municipal Cacoal ed. extraordinaria 02/04/2026",
    verifiedAt: "2026-04-10",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Adailton de Souza Fúria",
      nome_urna: "Adailton Furia",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Governador",
      estado: "RO",
    },
  },
  {
    slug: "confucio-moura",
    source: "Senado Federal oficial + Rondonia Dinamica 2026-03-23",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "José Confúcio Aires Moura",
      nome_urna: "Confúcio Moura",
      partido_atual: "MDB",
      partido_sigla: "MDB",
      cargo_atual: "Senador(a)",
      cargo_disputado: "Governador",
      estado: "RO",
    },
  },
  {
    slug: "dr-fernando-maximo",
    source:
      "Confirmacao manual 2026-04-05 + FIX apply-current-factual-fixes (pleito ao Senado RO pelo PL em 2026)",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Fernando Máximo de Oliveira",
      nome_urna: "Dr. Fernando Máximo",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_atual: "Deputado(a) Federal",
      cargo_disputado: "Senador",
      estado: "RO",
    },
  },
  {
    slug: "expedito-netto",
    source: "filiacao PT jan/2026 confirmada",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Expedito Gonçalves Ferreira Netto",
      nome_urna: "Expedito Netto",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_disputado: "Governador",
      estado: "RO",
    },
  },
  {
    slug: "hildon-chaves",
    source: "Portal364 2026-03 + News Rondonia 2026-03-20",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Hildon de Lima Chaves",
      nome_urna: "Hildon Chaves",
      partido_atual: "Uniao Brasil",
      partido_sigla: "UNIAO",
      cargo_disputado: "Governador",
      estado: "RO",
    },
  },
  {
    slug: "marcos-rogerio",
    source: "Senado Federal oficial + Diario da Amazonia 2026-04-02",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Marcos Rogério da Silva Brito",
      nome_urna: "Marcos Rogerio",
      partido_atual: "PL",
      partido_sigla: "PL",
      cargo_atual: "Senador(a)",
      cargo_disputado: "Governador",
      estado: "RO",
    },
  },
  {
    slug: "arthur-henrique",
    source: "TSE consulta_cand 2016, 2020 e 2022; reconciliacao RR 2026-07-10",
    verifiedAt: "2026-07-10",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Arthur Henrique Brandão Machado",
      nome_urna: "Arthur Henrique",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "RR",
    },
  },
  {
    slug: "edilson-damiao",
    source: "TSE consulta_cand 2022 + recibo RR 2026-07-10",
    verifiedAt: "2026-07-11",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Edilson Damião Lima",
      nome_urna: "Edilson Damião",
      partido_atual: "Uniao Brasil",
      partido_sigla: "UNIAO",
      cargo_atual: null,
      cargo_disputado: "Governador",
      estado: "RR",
    },
  },
  {
    slug: "soldado-sampaio",
    source: "ALE-RR oficial 2026-02-24 + Folha BV 2025-10-06",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Soldado Sampaio",
      nome_urna: "Soldado Sampaio",
      partido_atual: "Republicanos",
      partido_sigla: "REPUBLICANOS",
      cargo_atual: "Presidente da Assembleia Legislativa de Roraima",
      cargo_disputado: "Governador",
      estado: "RR",
    },
  },
  {
    slug: "teresa-surita",
    source:
      "TSE consulta_cand 2022 + DJE/TSE reconciliados com o cadastro oficial materializado em 2026-07-11",
    verifiedAt: "2026-07-11",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Maria Teresa Saenz Surita Guimarães",
      nome_urna: "Teresa Surita",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_disputado: "Senador",
      estado: "RR",
    },
  },
  {
    slug: "edegar-pretto",
    source:
      "site oficial Edegar Pretto 2026-05-13 + RED 2026-04-16; prelaunch final launch closure 2026-05-20 consolidou pre-candidatura a vice-governador do RS na chapa de Juliana Brizola",
    verifiedAt: "2026-05-20",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Edegar Pretto",
      nome_urna: "Edegar Pretto",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_disputado: "Vice-Governador",
      estado: "RS",
    },
  },
  {
    slug: "evandro-augusto",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Evandro Augusto",
      nome_urna: "Evandro Augusto",
      partido_atual: "Partido Missao",
      partido_sigla: "MISSAO",
      cargo_disputado: "Governador",
      estado: "RS",
    },
  },
  {
    slug: "gabriel-souza",
    source: "Gabinete do Vice-Governador RS oficial + UOL/Estadao 2026-04-02",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Gabriel Souza",
      nome_urna: "Gabriel Souza",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_atual: "Vice-Governador do Rio Grande do Sul",
      cargo_disputado: "Governador",
      estado: "RS",
    },
  },
  {
    slug: "juliana-brizola",
    source: "PDT oficial 2025-11-15 + ABC+ 2026-03-10",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Juliana Daudt Brizola",
      nome_urna: "Juliana Brizola",
      partido_atual: "Partido Democratico Trabalhista",
      partido_sigla: "PDT",
      cargo_disputado: "Governador",
      estado: "RS",
    },
  },
  {
    slug: "luciano-zucco",
    source: "Camara dos Deputados 2026-04-01",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Luciano Lorenzini Zucco",
      nome_urna: "Luciano Zucco",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "RS",
    },
  },
  {
    slug: "marcelo-maranata",
    source:
      "FIX apply-current-factual-fixes mantém partido 'incerto' (curadoria 19.csv: fontes locais nao consolidam filiacao atual nem pleito robusto em 2026); cargo atual Prefeito de Guaiba conforme Globo + curadoria 19.csv",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Marcelo Maranata",
      nome_urna: "Marcelo Maranata",
      cargo_atual: "Prefeito de Guaiba",
      cargo_disputado: "Governador",
      estado: "RS",
    },
  },
  {
    slug: "decio-lima",
    source: "filiacao PT confirmada",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Decio Nery de Lima",
      nome_urna: "Decio Lima",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_disputado: "Governador",
      estado: "SC",
    },
  },
  {
    slug: "joao-rodrigues",
    source:
      "Auditoria trajetoria partidaria 2026-04-13 (Camara dos Deputados perfil 160571, TSE DivulgaCandContas, G1 SC, Gazeta do Povo, Wikipedia) - distinto de homonimos com registros TSE em outros estados (ex.: RN). Caso modelo da trilha de remediacao global de trajetorias estruturadas (curadoria interna, Fluxo 2).",
    verifiedAt: "2026-04-13",
    confidence: "curated",
    cohorts: ["governadores"],
    // Pendência de curadoria 2026-04-16 (Task 21 Família B): biografia cita mandato como
    // Vice-Prefeito de Pinhalzinho, mas historico_politico atualmente nao registra esse
    // cargo canonico. Vice-Prefeito foi removido do expected_cargos para alinhar a auditoria
    // ao estado real da DB; a reinclusao depende de historicoFix dedicado em
    // apply-current-factual-fixes com fonte primaria (TSE ou ato oficial de Pinhalzinho).
    expected_cargos: [
      "Prefeito",
      "Deputado Estadual",
      "Deputado Federal",
    ],
    expected: {
      nome_completo: "João Rodrigues",
      nome_urna: "João Rodrigues",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Governador",
      estado: "SC",
    },
  },
  {
    slug: "marcelo-brigadeiro",
    source: "Vale Itajai 2025-12-27 + 4oito 2026-01-26 + Fesporte-SC 2020-08-07",
    verifiedAt: "2026-05-20",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Marcelo Marcel Franco José da Silva",
      nome_urna: "Marcelo Brigadeiro",
      partido_atual: "Partido Missao",
      partido_sigla: "MISSAO",
      cargo_disputado: "Governador",
      estado: "SC",
    },
  },
  {
    slug: "marcos-vieira",
    source: "ALESC oficial + SC Todo Dia 2025-12-08",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Marcos Vieira",
      nome_urna: "Marcos Vieira",
      partido_atual: "Partido da Social Democracia Brasileira",
      partido_sigla: "PSDB",
      cargo_atual: "Deputado Estadual",
      cargo_disputado: "Governador",
      estado: "SC",
    },
  },
  {
    slug: "fabio-mitidieri",
    source: "Governo de Sergipe oficial + TSE consulta_cand reconciliados em 2026-07-11",
    verifiedAt: "2026-07-11",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Fábio Cruz Mitidieri",
      nome_urna: "Fabio Mitidieri",
      partido_atual: "PSD",
      partido_sigla: "PSD",
      cargo_atual: "Governador de Sergipe",
      cargo_disputado: "Governador",
      estado: "SE",
    },
  },
  {
    slug: "thiago-de-joaldo",
    source:
      "Camara dos Deputados oficial 2026-04-02; FIX apply-current-factual-fixes mantém filiação ao Republicanos (assertion ITNet 2025-11-12 de possível troca para PP nao foi confirmada pela Camara oficial)",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Thiago Rezende de Oliveira",
      nome_urna: "Thiago de Joaldo",
      partido_atual: "Republicanos",
      partido_sigla: "REPUBLICANOS",
      cargo_atual: "Deputado(a) Federal",
      cargo_disputado: "Governador",
      estado: "SE",
    },
  },
  {
    slug: "valmir-de-francisquinho",
    source: "SEnoticias 2026-04-02 + Fan F1 2026-04-02 + Atualiza Sergipe 2026-03-29",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Valmir dos Santos Costa",
      nome_urna: "Valmir de Francisquinho",
      partido_atual: "Republicanos",
      partido_sigla: "REPUBLICANOS",
      cargo_atual: null,
      cargo_disputado: "Governador",
      estado: "SE",
    },
  },
  {
    slug: "andre-do-prado",
    source: "Band/UOL 2026-05-26 + WORKFLOWS 2026-06-23 radar/publicacao",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Andre Luis do Prado",
      nome_urna: "Andre do Prado",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Senador",
      estado: "SP",
    },
  },
  {
    slug: "felicio-ramuth",
    source:
      "Governo de SP oficial + UOL/ISTOE 2026-04-02; FIX apply-current-factual-fixes mantém pleito a Vice-Governador (situacao_candidatura=incerto ate 2026-04-14)",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Felício Ramuth",
      nome_urna: "Felicio Ramuth",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_atual: "Vice-Governador de Sao Paulo",
      cargo_disputado: "Vice-Governador",
      estado: "SP",
    },
  },
  {
    slug: "gilberto-kassab",
    source: "CNN 2026-03-25 + Governo de SP oficial",
    verifiedAt: "2026-04-10",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Gilberto Kassab",
      nome_urna: "Gilberto Kassab",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Governador",
      estado: "SP",
    },
  },
  {
    slug: "guilherme-derrite",
    source:
      "Camara dos Deputados oficial 2026-04-02 + UOL 2025-05-19; FIX apply-current-factual-fixes consolidou pre-candidatura ao Senado por SP",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Guilherme Muraro Derrite",
      nome_urna: "Guilherme Derrite",
      partido_atual: "PP",
      partido_sigla: "PP",
      cargo_atual: "Deputado(a) Federal",
      cargo_disputado: "Senador",
      estado: "SP",
    },
  },
  {
    slug: "marcio-franca",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Marcio Luiz Franca Gomes",
      nome_urna: "Marcio Franca",
      partido_atual: "PSB",
      partido_sigla: "PSB",
      cargo_disputado: "Governador",
      estado: "SP",
    },
  },
  {
    slug: "amelio-cayres",
    source:
      "Conexao Tocantins 2026-05-16 + ALETO oficial; pre-candidatura a vice-governador oficialmente lancada em chapa de Vicentinho Junior",
    verifiedAt: "2026-05-20",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Amélio Antunes Cayres",
      nome_urna: "Amelio Cayres",
      cargo_atual: "Presidente da Assembleia Legislativa do Tocantins",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_disputado: "Vice-Governador",
      estado: "TO",
    },
  },
  {
    slug: "ataides-oliveira",
    source:
      "FIX apply-current-factual-fixes mantém partido 'incerto' (ex-senador TO; filiacao partidaria e pleito 2026 permanecem incertos na curadoria atual); substitui 'filiacao NOVO set/2025 confirmada' nao corroborada",
    verifiedAt: "2026-04-14",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Ataídes de Oliveira Leite",
      nome_urna: "Ataides Oliveira",
      cargo_disputado: "Governador",
      estado: "TO",
    },
  },
  {
    slug: "laurez-moreira",
    source: "Voz do Bico 2025-12-11",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Laurez da Rocha Moreira",
      nome_urna: "Laurez Moreira",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Governador",
      estado: "TO",
    },
  },
  {
    slug: "professora-dorinha",
    source: "Senado Federal oficial + Uniao Brasil 2026-03-26",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Maria Auxiliadora Seabra Rezende",
      nome_urna: "Professora Dorinha",
      partido_atual: "Uniao Brasil",
      partido_sigla: "UNIAO",
      cargo_atual: "Senador(a)",
      cargo_disputado: "Governador",
      estado: "TO",
    },
  },
  {
    slug: "vicentinho-junior",
    source: "Camara dos Deputados oficial + Jornal Opcao TO 2026-02-20",
    verifiedAt: "2026-04-02",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Vicente Alves de Oliveira Júnior",
      nome_urna: "Vicentinho Junior",
      partido_atual: "Partido da Social Democracia Brasileira",
      partido_sigla: "PSDB",
      cargo_atual: "Deputado(a) Federal",
      cargo_disputado: "Governador",
      estado: "TO",
    },
  },
]

export const CANDIDATE_ASSERTIONS: CandidateAssertion[] = RAW_CANDIDATE_ASSERTIONS.map((item) => {
  const { expected_cargos: rawCargos, ...rest } = item
  const expected_cargos = normalizeExpectedCargos(rawCargos)
  return {
    ...rest,
    expected: sanitizeExpectedSnapshot(rest.expected),
    verifiedAt: item.verifiedAt ?? inferVerifiedAt(item.source),
    ...(expected_cargos !== undefined ? { expected_cargos } : {}),
  }
})

export const ASSERTIONS_MAP = new Map(
  CANDIDATE_ASSERTIONS.map((item) => [item.slug, item])
)

export function getAssertionSlugsForCohort(cohort: AssertionCohort): string[] {
  const normalizedCohort =
    cohort === "alto-trafego-editorial" ? "alto-trafego" : cohort

  return CANDIDATE_ASSERTIONS.filter((item) => item.cohorts.includes(normalizedCohort)).map(
    (item) => item.slug
  )
}
