/**
 * Closed list of template patterns generated by pipeline scripts.
 * NOT a generic autocorrect. Only matches known pipeline-generated strings.
 */
const TEMPLATE_FIXES: Array<[string, string]> = [
  // ingest-tse-historico.ts
  ["mudanca observada entre eleicoes", "Mudança observada entre eleições"],
  ["NAO ELEITO", "NÃO ELEITO"],

  // enrich-wiki-historico.ts (must run before "nao determinado" to avoid partial match)
  ["Periodo nao", "Período não"],

  // Legacy anchor/timeline sync outputs (scripts removed in chore/remove-dead-scripts)
  ["Filiacao atual observada na atualizacao", "Filiação atual observada na atualização"],
  ["atualizacao do perfil", "atualização do perfil"],
  ["mudanca anterior", "mudança anterior"],
  ["nao determinada", "não determinada"],
  ["nao determinado", "não determinado"],
  ["historico partidario", "histórico partidário"],
  ["inicio do mandato", "início do mandato"],
  ["filiacao atual", "filiação atual"],

  // ingest-filiacao.ts / ingest-wikidata-politico.ts
  ["filiacao inicial conhecida", "filiação inicial conhecida"],
  ["janela partidaria", "janela partidária"],
]

export function sanitizeTemplateText(text: string): string {
  let result = text
  for (const [from, to] of TEMPLATE_FIXES) {
    if (result.includes(from)) {
      result = result.split(from).join(to)
    }
  }
  return result
}
