-- ============================================
-- Legislacao full-site: paula-belmonte / Camara Dados Abertos / projetos_lei
-- Coverage ampliado parcial: Lote A autoria principal Camara
-- ============================================
-- Fonte oficial: Camara dos Deputados - Dados Abertos
--   https://dadosabertos.camara.leg.br/api/v2/deputados/204377
--   https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id}
--   https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id}/autores
--
-- Artefato de auditoria:
--   fonte interna de curadoria
--
-- Coverage:
--   coverage_id    = paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506
--   coverage_scope = inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506
--
-- Filtro factual: das 100 rows Camara legacy existentes, somente 72
-- foram marcadas com coverage_id porque a API oficial confirmou
-- idDeputado=204377, tipo Deputado(a), ordemAssinatura=1.
-- 28 rows permanecem sem coverage por coautoria/sem autoria verificavel.
--
-- Esta migration NAO escreve em legislacao_mandato_executivo.
-- Esta migration NAO insere, deleta ou trunca rows.
-- ============================================

DO $$
DECLARE
  cand_id uuid;
  total_pl int;
  target_present int;
  target_with_other_coverage int;
  lme_count int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'paula-belmonte';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'paula-belmonte: candidato ausente neste banco local/CI minimo; coverage Camara pulado';
    RETURN;
  END IF;

  SELECT count(*) INTO total_pl FROM projetos_lei WHERE candidato_id = cand_id;
  IF total_pl <> 100 THEN
    RAISE EXCEPTION 'Pre-condicao paula-belmonte: esperadas 100 rows legacy em projetos_lei, encontradas %', total_pl;
  END IF;

  SELECT count(*) INTO target_present
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND fonte = 'Camara'
    AND proposicao_id_api IN ('2343123', '2344567', '2343124', '2342905', '2341150', '2345019', '2343128', '2343122', '2342335', '2341983', '2341042', '2340765', '2340573', '2340043', '2339963', '2339956', '2339129', '2336405', '2342307', '2340204', '2339961', '2339888', '2337395', '2336394', '2335204', '2334198', '2332832', '2332321', '2330783', '2327780', '2340985', '2340572', '2337398', '2336401', '2335265', '2334199', '2334192', '2333032', '2332322', '2328331', '2323759', '2339965', '2339150', '2334386', '2334194', '2333871', '2332515', '2331331', '2329009', '2336435', '2336077', '2334195', '2333872', '2332831', '2330764', '2329013', '2334385', '2334193', '2333040', '2331019', '2328332', '2342320', '2339962', '2339955', '2339954', '2339952', '2333873', '2326383', '2334983', '2329410', '2336434', '2336229');
  IF target_present <> 72 THEN
    RAISE EXCEPTION 'Pre-condicao paula-belmonte: esperadas 72 rows alvo Camara presentes, encontradas %', target_present;
  END IF;

  SELECT count(*) INTO target_with_other_coverage
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND proposicao_id_api IN ('2343123', '2344567', '2343124', '2342905', '2341150', '2345019', '2343128', '2343122', '2342335', '2341983', '2341042', '2340765', '2340573', '2340043', '2339963', '2339956', '2339129', '2336405', '2342307', '2340204', '2339961', '2339888', '2337395', '2336394', '2335204', '2334198', '2332832', '2332321', '2330783', '2327780', '2340985', '2340572', '2337398', '2336401', '2335265', '2334199', '2334192', '2333032', '2332322', '2328331', '2323759', '2339965', '2339150', '2334386', '2334194', '2333871', '2332515', '2331331', '2329009', '2336435', '2336077', '2334195', '2333872', '2332831', '2330764', '2329013', '2334385', '2334193', '2333040', '2331019', '2328332', '2342320', '2339962', '2339955', '2339954', '2339952', '2333873', '2326383', '2334983', '2329410', '2336434', '2336229')
    AND coverage_id IS NOT NULL
    AND coverage_id <> 'paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506';
  IF target_with_other_coverage <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao paula-belmonte: % rows alvo ja tem coverage_id divergente', target_with_other_coverage;
  END IF;

  SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao paula-belmonte: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;
END $$;

CREATE TEMP TABLE _coverage_paula_belmonte_camara_lote_a ON COMMIT DROP AS
SELECT *
FROM (
  VALUES
    ('2343123', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343123', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343123/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343123', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2343123","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343123","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343123/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343123","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2344567', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2344567', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2344567/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2344567', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2344567","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2344567","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2344567/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2344567","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2343124', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343124', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343124/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343124', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2343124","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343124","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343124/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343124","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2342905', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342905', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342905/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342905', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2342905","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342905","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342905/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342905","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2341150', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341150', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341150/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341150', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2341150","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341150","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341150/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341150","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2345019', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2345019', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2345019/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2345019', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2345019","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2345019","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2345019/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2345019","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2343128', 1, 3, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343128', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343128/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343128', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2343128","ordem_assinatura":1,"total_autores":3,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343128","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343128/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343128","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2343122', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343122', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343122/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343122', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2343122","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343122","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343122/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2343122","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2342335', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342335', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342335/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342335', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2342335","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342335","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342335/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342335","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2341983', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341983', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341983/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341983', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2341983","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341983","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341983/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341983","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2341042', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341042', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341042/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341042', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2341042","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341042","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341042/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341042","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2340765', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340765', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340765/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340765', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2340765","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340765","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340765/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340765","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2340573', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340573', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340573/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340573', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2340573","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340573","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340573/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340573","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2340043', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340043', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340043/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340043', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2340043","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340043","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340043/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340043","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2339963', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339963', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339963/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339963', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2339963","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339963","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339963/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339963","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2339956', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339956', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339956/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339956', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2339956","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339956","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339956/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339956","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2339129', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339129', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339129/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339129', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2339129","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339129","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339129/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339129","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2336405', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336405', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336405/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336405', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2336405","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336405","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336405/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336405","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2342307', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342307', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342307/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342307', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2342307","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342307","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342307/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342307","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2340204', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340204', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340204/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340204', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2340204","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340204","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340204/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340204","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2339961', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339961', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339961/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339961', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2339961","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339961","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339961/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339961","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2339888', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339888', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339888/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339888', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2339888","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339888","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339888/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339888","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2337395', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2337395', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2337395/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2337395', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2337395","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2337395","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2337395/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2337395","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2336394', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336394', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336394/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336394', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2336394","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336394","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336394/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336394","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2335204', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2335204', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2335204/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2335204', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2335204","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2335204","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2335204/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2335204","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2334198', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334198', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334198/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334198', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2334198","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334198","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334198/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334198","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2332832', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332832', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332832/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332832', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2332832","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332832","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332832/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332832","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2332321', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332321', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332321/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332321', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2332321","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332321","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332321/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332321","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2330783', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2330783', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2330783/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2330783', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2330783","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2330783","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2330783/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2330783","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2327780', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327780', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327780/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327780', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2327780","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327780","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327780/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327780","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2340985', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340985', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340985/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340985', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2340985","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340985","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340985/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340985","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2340572', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340572', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340572/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340572', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2340572","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340572","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340572/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2340572","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2337398', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2337398', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2337398/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2337398', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2337398","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2337398","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2337398/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2337398","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2336401', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336401', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336401/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336401', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2336401","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336401","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336401/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336401","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2335265', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2335265', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2335265/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2335265', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2335265","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2335265","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2335265/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2335265","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2334199', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334199', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334199/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334199', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2334199","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334199","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334199/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334199","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2334192', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334192', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334192/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334192', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2334192","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334192","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334192/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334192","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2333032', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333032', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333032/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333032', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2333032","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333032","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333032/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333032","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2332322', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332322', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332322/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332322', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2332322","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332322","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332322/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332322","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2328331', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2328331', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2328331/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2328331', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2328331","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2328331","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2328331/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2328331","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2323759', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2323759', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2323759/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2323759', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2323759","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2323759","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2323759/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2323759","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2339965', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339965', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339965/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339965', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2339965","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339965","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339965/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339965","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2339150', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339150', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339150/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339150', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2339150","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339150","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339150/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339150","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2334386', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334386', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334386/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334386', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2334386","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334386","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334386/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334386","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2334194', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334194', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334194/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334194', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2334194","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334194","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334194/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334194","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2333871', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333871', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333871/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333871', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2333871","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333871","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333871/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333871","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2332515', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332515', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332515/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332515', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2332515","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332515","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332515/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332515","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2331331', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2331331', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2331331/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2331331', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2331331","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2331331","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2331331/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2331331","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2329009', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329009', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329009/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329009', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2329009","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329009","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329009/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329009","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2336435', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336435', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336435/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336435', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2336435","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336435","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336435/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336435","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2336077', 1, 12, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336077', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336077/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336077', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2336077","ordem_assinatura":1,"total_autores":12,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336077","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336077/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336077","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2334195', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334195', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334195/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334195', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2334195","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334195","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334195/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334195","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2333872', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333872', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333872/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333872', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2333872","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333872","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333872/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333872","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2332831', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332831', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332831/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332831', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2332831","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332831","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332831/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332831","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2330764', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2330764', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2330764/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2330764', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2330764","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2330764","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2330764/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2330764","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2329013', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329013', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329013/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329013', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2329013","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329013","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329013/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329013","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2334385', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334385', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334385/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334385', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2334385","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334385","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334385/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334385","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2334193', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334193', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334193/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334193', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2334193","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334193","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334193/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334193","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2333040', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333040', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333040/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333040', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2333040","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333040","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333040/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333040","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2331019', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2331019', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2331019/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2331019', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2331019","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2331019","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2331019/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2331019","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2328332', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2328332', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2328332/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2328332', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2328332","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2328332","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2328332/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2328332","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2342320', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342320', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342320/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342320', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2342320","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342320","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342320/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342320","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2339962', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339962', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339962/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339962', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2339962","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339962","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339962/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339962","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2339955', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339955', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339955/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339955', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2339955","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339955","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339955/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339955","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2339954', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339954', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339954/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339954', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2339954","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339954","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339954/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339954","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2339952', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339952', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339952/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339952', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2339952","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339952","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339952/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2339952","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2333873', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333873', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333873/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333873', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2333873","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333873","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333873/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333873","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2326383', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2326383', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2326383/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2326383', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2326383","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2326383","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2326383/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2326383","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2334983', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334983', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334983/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334983', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2334983","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334983","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334983/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334983","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2329410', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329410', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329410/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329410', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2329410","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329410","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329410/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329410","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2336434', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336434', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336434/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336434', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2336434","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336434","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336434/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336434","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb),
    ('2336229', 1, 1, 'Paula Belmonte', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336229', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336229/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336229', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paula-belmonte-camara-lote-a-20260506","coverage_id":"paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204377,"proposicao_id_api":"2336229","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paula Belmonte","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336229","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336229/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2336229","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:06:21.831Z"}'::jsonb)
) AS v(
  proposicao_id_api,
  ordem_assinatura,
  total_autores,
  autor_nome,
  autor_tipo,
  detalhe_endpoint,
  autores_endpoint,
  public_url,
  metadata_patch
);

WITH target AS (
  SELECT c.id AS candidato_id
  FROM candidatos c
  WHERE c.slug = 'paula-belmonte'
)
UPDATE projetos_lei pl
SET
  coverage_id = 'paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506',
  coverage_scope = 'inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506',
  metadata = COALESCE(pl.metadata, '{}'::jsonb) || seed.metadata_patch
FROM target
JOIN _coverage_paula_belmonte_camara_lote_a seed ON TRUE
WHERE pl.candidato_id = target.candidato_id
  AND pl.fonte = 'Camara'
  AND pl.proposicao_id_api = seed.proposicao_id_api
  AND (pl.coverage_id IS NULL OR pl.coverage_id = 'paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506');

DO $$
DECLARE
  cand_id uuid;
  with_target_coverage int;
  remaining_null int;
  lme_count int;
  other_slugs_with_target int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'paula-belmonte';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'paula-belmonte: pos-condicao pulada porque candidato nao existe neste banco local/CI minimo';
    RETURN;
  END IF;

  SELECT count(*) INTO with_target_coverage
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id = 'paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506'
    AND coverage_scope = 'inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506';
  IF with_target_coverage <> 72 THEN
    RAISE EXCEPTION 'Pos-apply paula-belmonte: esperadas 72 rows com coverage_id alvo, encontradas %', with_target_coverage;
  END IF;

  SELECT count(*) INTO remaining_null
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id IS NULL;
  IF remaining_null <> 28 THEN
    RAISE EXCEPTION 'Pos-apply paula-belmonte: esperadas 28 rows sem coverage por limite documentado, encontradas %', remaining_null;
  END IF;

  SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pos-apply paula-belmonte: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;

  SELECT count(*) INTO other_slugs_with_target
  FROM projetos_lei
  WHERE candidato_id <> cand_id
    AND coverage_id = 'paula-belmonte-camara-autoria-principal-ampliado-parcial-lote-a-20260506';
  IF other_slugs_with_target <> 0 THEN
    RAISE EXCEPTION 'Pos-apply paula-belmonte: % rows de outros slugs com coverage_id alvo', other_slugs_with_target;
  END IF;

  RAISE NOTICE 'Pos-apply paula-belmonte Camara Lote A: coverage=% sem_coverage=% lme=%', with_target_coverage, remaining_null, lme_count;
END $$;
