-- ============================================
-- Legislacao full-site: vicentinho-junior / Camara Dados Abertos / projetos_lei
-- Coverage ampliado parcial: Lote A autoria principal Camara
-- ============================================
-- Fonte oficial: Camara dos Deputados - Dados Abertos
--   https://dadosabertos.camara.leg.br/api/v2/deputados/137070
--   https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id}
--   https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id}/autores
--
-- Artefato de auditoria:
--   fonte interna de curadoria
--
-- Coverage:
--   coverage_id    = vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506
--   coverage_scope = inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506
--
-- Filtro factual: das 100 rows Camara legacy existentes, somente 27
-- foram marcadas com coverage_id porque a API oficial confirmou
-- idDeputado=137070, tipo Deputado(a), ordemAssinatura=1.
-- 73 rows permanecem sem coverage por coautoria/sem autoria verificavel.
--
-- Esta migration NAO escreve em legislacao_mandato_executivo.
-- Esta migration NAO insere, deleta ou trunca rows.
-- ============================================

DO $$
DECLARE
  cand_id uuid;
  total_pl int;
  target_present int;
  target_with_other_coverage int;
  lme_count int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'vicentinho-junior';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'vicentinho-junior: candidato ausente neste banco local/CI minimo; coverage Camara pulado';
    RETURN;
  END IF;

  SELECT count(*) INTO total_pl FROM projetos_lei WHERE candidato_id = cand_id;
  IF total_pl <> 100 THEN
    RAISE EXCEPTION 'Pre-condicao vicentinho-junior: esperadas 100 rows legacy em projetos_lei, encontradas %', total_pl;
  END IF;

  SELECT count(*) INTO target_present
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND fonte = 'Camara'
    AND proposicao_id_api IN ('2529805', '2523386', '2513530', '2554670', '2541075', '2599996', '2593743', '2590320', '2599994', '2590299', '2600987', '2593745', '2590323', '2588982', '2599998', '2593744', '2590322', '2593746', '2590324', '2589028', '2568799', '2567541', '2572950', '2568758', '2543649', '2608306', '2513362');
  IF target_present <> 27 THEN
    RAISE EXCEPTION 'Pre-condicao vicentinho-junior: esperadas 27 rows alvo Camara presentes, encontradas %', target_present;
  END IF;

  SELECT count(*) INTO target_with_other_coverage
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND proposicao_id_api IN ('2529805', '2523386', '2513530', '2554670', '2541075', '2599996', '2593743', '2590320', '2599994', '2590299', '2600987', '2593745', '2590323', '2588982', '2599998', '2593744', '2590322', '2593746', '2590324', '2589028', '2568799', '2567541', '2572950', '2568758', '2543649', '2608306', '2513362')
    AND coverage_id IS NOT NULL
    AND coverage_id <> 'vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506';
  IF target_with_other_coverage <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao vicentinho-junior: % rows alvo ja tem coverage_id divergente', target_with_other_coverage;
  END IF;

  SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao vicentinho-junior: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;
END $$;

CREATE TEMP TABLE _coverage_vicentinho_junior_camara_lote_a ON COMMIT DROP AS
SELECT *
FROM (
  VALUES
    ('2529805', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2529805', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2529805/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2529805', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2529805","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2529805","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2529805/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2529805","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2523386', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2523386', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2523386/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2523386', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2523386","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2523386","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2523386/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2523386","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2513530', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2513530', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2513530/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2513530', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2513530","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2513530","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2513530/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2513530","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2554670', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554670', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554670/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554670', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2554670","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554670","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554670/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554670","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2541075', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2541075', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2541075/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2541075', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2541075","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2541075","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2541075/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2541075","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2599996', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2599996', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2599996/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2599996', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2599996","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2599996","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2599996/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2599996","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2593743', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593743', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593743/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593743', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2593743","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593743","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593743/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593743","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2590320', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590320', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590320/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590320', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2590320","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590320","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590320/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590320","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2599994', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2599994', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2599994/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2599994', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2599994","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2599994","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2599994/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2599994","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2590299', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590299', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590299/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590299', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2590299","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590299","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590299/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590299","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2600987', 1, 11, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2600987', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2600987/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2600987', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2600987","ordem_assinatura":1,"total_autores":11,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2600987","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2600987/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2600987","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2593745', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593745', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593745/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593745', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2593745","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593745","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593745/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593745","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2590323', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590323', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590323/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590323', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2590323","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590323","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590323/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590323","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2588982', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2588982', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2588982/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2588982', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2588982","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2588982","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2588982/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2588982","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2599998', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2599998', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2599998/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2599998', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2599998","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2599998","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2599998/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2599998","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2593744', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593744', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593744/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593744', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2593744","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593744","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593744/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593744","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2590322', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590322', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590322/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590322', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2590322","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590322","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590322/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590322","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2593746', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593746', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593746/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593746', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2593746","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593746","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593746/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2593746","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2590324', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590324', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590324/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590324', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2590324","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590324","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590324/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590324","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2589028', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2589028', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2589028/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2589028', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2589028","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2589028","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2589028/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2589028","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2568799', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2568799', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2568799/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2568799', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2568799","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2568799","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2568799/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2568799","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2567541', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567541', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567541/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567541', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2567541","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567541","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567541/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567541","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2572950', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2572950', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2572950/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2572950', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2572950","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2572950","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2572950/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2572950","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2568758', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2568758', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2568758/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2568758', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2568758","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2568758","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2568758/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2568758","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2543649', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2543649', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2543649/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2543649', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2543649","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2543649","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2543649/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2543649","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2608306', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2608306', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2608306/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2608306', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2608306","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2608306","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2608306/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2608306","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb),
    ('2513362', 1, 1, 'Vicentinho Júnior', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2513362', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2513362/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2513362', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"vicentinho-junior-camara-lote-a-20260506","coverage_id":"vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":137070,"proposicao_id_api":"2513362","ordem_assinatura":1,"total_autores":1,"autor_nome":"Vicentinho Júnior","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2513362","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2513362/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2513362","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:37:54.726Z"}'::jsonb)
) AS v(
  proposicao_id_api,
  ordem_assinatura,
  total_autores,
  autor_nome,
  autor_tipo,
  detalhe_endpoint,
  autores_endpoint,
  public_url,
  metadata_patch
);

WITH target AS (
  SELECT c.id AS candidato_id
  FROM candidatos c
  WHERE c.slug = 'vicentinho-junior'
)
UPDATE projetos_lei pl
SET
  coverage_id = 'vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506',
  coverage_scope = 'inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506',
  metadata = COALESCE(pl.metadata, '{}'::jsonb) || seed.metadata_patch
FROM target
JOIN _coverage_vicentinho_junior_camara_lote_a seed ON TRUE
WHERE pl.candidato_id = target.candidato_id
  AND pl.fonte = 'Camara'
  AND pl.proposicao_id_api = seed.proposicao_id_api
  AND (pl.coverage_id IS NULL OR pl.coverage_id = 'vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506');

DO $$
DECLARE
  cand_id uuid;
  with_target_coverage int;
  remaining_null int;
  lme_count int;
  other_slugs_with_target int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'vicentinho-junior';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'vicentinho-junior: pos-condicao pulada porque candidato nao existe neste banco local/CI minimo';
    RETURN;
  END IF;

  SELECT count(*) INTO with_target_coverage
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id = 'vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506'
    AND coverage_scope = 'inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506';
  IF with_target_coverage <> 27 THEN
    RAISE EXCEPTION 'Pos-apply vicentinho-junior: esperadas 27 rows com coverage_id alvo, encontradas %', with_target_coverage;
  END IF;

  SELECT count(*) INTO remaining_null
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id IS NULL;
  IF remaining_null <> 73 THEN
    RAISE EXCEPTION 'Pos-apply vicentinho-junior: esperadas 73 rows sem coverage por limite documentado, encontradas %', remaining_null;
  END IF;

  SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pos-apply vicentinho-junior: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;

  SELECT count(*) INTO other_slugs_with_target
  FROM projetos_lei
  WHERE candidato_id <> cand_id
    AND coverage_id = 'vicentinho-junior-camara-autoria-principal-ampliado-parcial-lote-a-20260506';
  IF other_slugs_with_target <> 0 THEN
    RAISE EXCEPTION 'Pos-apply vicentinho-junior: % rows de outros slugs com coverage_id alvo', other_slugs_with_target;
  END IF;

  RAISE NOTICE 'Pos-apply vicentinho-junior Camara Lote A: coverage=% sem_coverage=% lme=%', with_target_coverage, remaining_null, lme_count;
END $$;
