-- Reconcile official TSE money rows discovered by the 2026-07-11 read-only
-- ingest for Jenilson Leite and Wanderlei Barbosa. Donor document identifiers
-- are deliberately excluded; public-safe names, values and types are retained.

INSERT INTO public.patrimonio (candidato_id, ano_eleicao, valor_total, bens, fonte)
SELECT c.id, v.ano_eleicao, v.valor_total, v.bens, 'TSE'
FROM public.candidatos c
JOIN (VALUES
  ('jenilson-leite', 2014, 120000, '[{"tipo":"Bem relacionado com o exercício da atividade autônoma","descricao":"UM APARELHO DE ULTRASONOGRAFIA","valor":70000},{"tipo":"Veículo automotor terrestre: caminhão, automóvel, moto, etc.","descricao":"CARRO HONDA CIVIC ANO 2012/2013,COR PRETA,PLACA:NAC:5672","valor":50000}]'::jsonb),
  ('jenilson-leite', 2018, 370000, '[{"tipo":"Outros bens móveis","descricao":"#NULO#","valor":70000},{"tipo":"Veículo automotor terrestre: caminhão, automóvel, moto, etc.","descricao":"#NULO#","valor":100000},{"tipo":"Outros bens imóveis","descricao":"#NULO#","valor":200000}]'::jsonb),
  ('jenilson-leite', 2022, 367210.29, '[{"tipo":"Veículo automotor terrestre: caminhão, automóvel, moto, etc.","descricao":"AUTOMOVEL COROLLA XEI 2.0 TOYOTA ANO 2019 PLACA QLY 8989","valor":90000},{"tipo":"Quotas ou quinhões de capital","descricao":"NA COOP DE CREDITO","valor":9864.67},{"tipo":"OUTROS BENS E DIREITOS","descricao":"FUNDO DE INVESTIMENTO","valor":950.84},{"tipo":"OUTROS BENS E DIREITOS","descricao":"CAIXA ECONOMICA FEDERAL","valor":18443.94},{"tipo":"OUTROS BENS E DIREITOS","descricao":"SICOOB","valor":37165.09},{"tipo":"OUTROS BENS E DIREITOS","descricao":"BANCO DO BRASIL","valor":1005.75},{"tipo":"Veículo automotor terrestre: caminhão, automóvel, moto, etc.","descricao":"UM AUTOMOVEL FORD RANGER XLT 3.2 20V 4X4 CD DIESEL, PLACA: QWO1D01 ANO 2020/2020","valor":209780}]'::jsonb),
  ('jenilson-leite', 2024, 307380.55, '[{"tipo":"Outras aplicações e Investimentos","descricao":"CAPITAL SOCIAL SICOOB","valor":11873.11},{"tipo":"Quotas ou quinhões de capital","descricao":"PARTICIPAÇÃO SOCIETÁRIA EMPRESA G O HAGE   CIA","valor":100000},{"tipo":"Outras aplicações e Investimentos","descricao":"BANCO SICOOB","valor":90.17},{"tipo":"Fundos: Ações, Mútuos de Privatização, Invest. Empresas Emergentes, Invest.Participação e Invest. Índice Mercado","descricao":"FUNDO DE INVESTIMENTO","valor":17.07},{"tipo":"Outras aplicações e Investimentos","descricao":"SALDO CAIXA ECONOMICA","valor":400.2},{"tipo":"Veículo automotor terrestre: caminhão, automóvel, moto, etc.","descricao":"CAMINHONETE FORD RANGER ANO 2020/2020 COR CINZA DIESEL","valor":195000}]'::jsonb),
  ('wanderlei-barbosa', 2010, 431920, '[{"tipo":"Outros bens imóveis","descricao":"02 SALAS COMERCIAIS, EDF. OFFICE CENTER, SALAS 504 E 506, PALMAS-TO","valor":80000},{"tipo":"Casa","descricao":"CASA, SITUADA NA RUA 7. DISTRITO DE TAQUARUÇU-TO","valor":65000},{"tipo":"Terra nua","descricao":"CHÁCARA SHALON, COM 512 HAC, LOTEAMENTO SANTA FÉ, LT. 35/01, TAQUARUÇU-TO","valor":25000},{"tipo":"Terra nua","descricao":"FAZENDA DOIS BREJOS, LT 115, LOT. SÃO SILVESTRE- AP. RIO NEGRO-TO COM 118,196HAC","valor":24420},{"tipo":"Terra nua","descricao":"FAZENDA DOIS BREJOS, LT 114, LOT. SÃO SILVESTRE- AP. RIO NEGRO-TO COM 130,859HAC","valor":27500},{"tipo":"Outros bens móveis","descricao":"300 CABEÇAS GADO BOVINO","valor":210000}]'::jsonb),
  ('wanderlei-barbosa', 2018, 1579100, '[{"tipo":"Sala ou conjunto","descricao":"SALA COMERCIAL N 504 LOCALIZADO NO EDIF OFFICE CENTER AV TEOTONIO SEGURADO LT 06 CENTRO PALMAS TO","valor":150000},{"tipo":"Sala ou conjunto","descricao":"SALA COMERCIAL N 506 LOCALIZADO NO EDIF OFFICE CENTER AV TEOTONIO SEGURADO LT 06 CENTRO PALMAS TO","valor":150000},{"tipo":"Casa","descricao":"CASA RESIDENCIAL SITUADA NA RUA 07 N 641 DISTRITO DE TAQUARUÇU PALMAS TO","valor":350000},{"tipo":"OUTROS BENS E DIREITOS","descricao":"SEMOVENTES/REBANHO BOVINO BEZERROS","valor":28800},{"tipo":"OUTROS BENS E DIREITOS","descricao":"SEMOVENTES/REBANHO BOVINO ADULTOS","valor":318000},{"tipo":"OUTROS BENS E DIREITOS","descricao":"SEMOVENTES/REBANHA BOVINO TOURO REPRODUTOR","valor":7300},{"tipo":"Outros bens imóveis","descricao":"CHACARA  COM 51,2 HAC NO LOTEAMENTO SANTA FE LOTE 35/01 E 35/02 EM TAQUARUÇU PALMAS TO","valor":170000},{"tipo":"Outros bens imóveis","descricao":"FAZENDA DENOMINADA DOIS BREJOS LOCALIZADA NO LOTE 115 DO LOTEAMENTO SAO SILVESTRE 5 ETAPA COM 118,196 HAC, EM APARECIDA DO RIO NEGRO TO","valor":185000},{"tipo":"Outros bens imóveis","descricao":"FAZENDA DENOMINADA DOIS BREJOS LOCALIZADA NO LOTE 114 DO LOTEAMENTO SAO SILVESTRE 5 ETAPA COM 130.8596 HAC EM APARECIDA DO RIO NEGRO TO","valor":220000}]'::jsonb),
  ('wanderlei-barbosa', 2022, 2200646.94, '[{"tipo":"Casa","descricao":"IMÓVEL","valor":350000},{"tipo":"Outros bens imóveis","descricao":"Chácara","valor":220000},{"tipo":"Outros bens imóveis","descricao":"Fazenda","valor":170000},{"tipo":"Outros bens imóveis","descricao":"Fazenda","valor":185000},{"tipo":"Sala ou conjunto","descricao":"Salas comerciais","valor":300000},{"tipo":"OUTROS BENS E DIREITOS","descricao":"Animais Bovinos","valor":740000},{"tipo":"Depósito bancário em conta corrente no País","descricao":"Saldo em Conta Corrente  - Banco do Brasil","valor":2316.38},{"tipo":"Depósito bancário em conta corrente no País","descricao":"Saldo em Conta Salário Banco do Brasil","valor":13330.56},{"tipo":"Veículo automotor terrestre: caminhão, automóvel, moto, etc.","descricao":"Trator Agrícola","valor":220000}]'::jsonb)
) AS v(slug, ano_eleicao, valor_total, bens) ON c.slug = v.slug
ON CONFLICT (candidato_id, ano_eleicao) DO UPDATE SET
  valor_total = EXCLUDED.valor_total, bens = EXCLUDED.bens, fonte = EXCLUDED.fonte;

INSERT INTO public.financiamento (candidato_id, ano_eleicao, total_arrecadado, total_fundo_partidario, total_fundo_eleitoral, total_pessoa_fisica, total_recursos_proprios, maiores_doadores, fonte)
SELECT c.id, v.ano_eleicao, v.total_arrecadado, v.total_fundo_partidario, v.total_fundo_eleitoral, v.total_pessoa_fisica, v.total_recursos_proprios, v.maiores_doadores, 'TSE'
FROM public.candidatos c
JOIN (VALUES
  ('jenilson-leite', 2014, 140748, 0, 0, 0, 0, '[{"nome":"TL ENGENHARIA LTDA","valor":39400,"tipo":"PJ"},{"nome":"Comitê Financeiro para Deputado Estadual","valor":17900,"tipo":"PJ"},{"nome":"GLAUCIA DE OLIVEIRA HAGE","valor":15150,"tipo":"PF"},{"nome":"JOELZA SILVA ALVES","valor":13800,"tipo":"PF"},{"nome":"RFRANCISCO DAS CHAGAS BATISTA","valor":10000,"tipo":"PF"},{"nome":"MARCOS PAULO PARENTE ARAUJO","valor":5500,"tipo":"PF"},{"nome":"MARIA LUCENIR SOUZA DA SILVA","valor":5000,"tipo":"PF"},{"nome":"JANILSON LOPES LEITE","valor":4500,"tipo":"PF"},{"nome":"Direção Estadual/Distrital","valor":4008,"tipo":"PJ"},{"nome":"RIO BRANCO AEROTAXI - LTDA","valor":3570,"tipo":"PJ"}]'::jsonb),
  ('jenilson-leite', 2018, 100295.73, 0, 0, 0, 0, '[{"nome":"JANILSON LOPES LEITE","valor":24497.73,"tipo":"PF"},{"nome":"SAMAYRA MARIA SARAIVA LESSA","valor":11700,"tipo":"PF"},{"nome":"ELEIÇÃO 2018 JORGE NEY VIANA MACEDO NEVES SENADOR","valor":10000,"tipo":"PJ"},{"nome":"DENIS JOSE ALVES DA COSTA","valor":6654,"tipo":"PF"},{"nome":"LIS DINIZ LIMA","valor":5000,"tipo":"PF"},{"nome":"EVANDRO JOSÉ DA SILVA","valor":3000,"tipo":"PF"},{"nome":"ANDRESSA KALYNE DUTRA DE MOURA","valor":2654,"tipo":"PF"},{"nome":"MARIA DO SOCORRO LOPES CARDOSO DA MOTA","valor":2000,"tipo":"PF"},{"nome":"JOSIVALDO DOS SANTOS NASCIMENTO","valor":2000,"tipo":"PF"},{"nome":"ICARO DE SOUZA PASSOS","valor":2000,"tipo":"PF"}]'::jsonb),
  ('jenilson-leite', 2022, 1779935, 0, 0, 0, 0, '[{"nome":"Direção Nacional","valor":1627000,"tipo":"PJ"},{"nome":"JANILSON LOPES LEITE","valor":19500,"tipo":"PF"},{"nome":"JARLEIANNE DA SILVA FADUL","valor":8000,"tipo":"PF"},{"nome":"ISMEL DE OLIVEIRA QUEIROZ","valor":3000,"tipo":"PF"},{"nome":"PEDRO PONTES DA SILVA","valor":3000,"tipo":"PF"},{"nome":"CARLOS CAIRAN LIMA DA COSTA","valor":3000,"tipo":"PF"},{"nome":"MARIA DE NAZARETH DE OLIVEIRA REBOUCAS","valor":3000,"tipo":"PF"},{"nome":"ALEXANDRE DOS SANTOS SAMPAIO","valor":3000,"tipo":"PF"},{"nome":"ANTONIO CARLOS NONATO DE FRANCA","valor":3000,"tipo":"PF"},{"nome":"JUCELIO DOS SANTOS TAUMATURGO","valor":3000,"tipo":"PF"}]'::jsonb),
  ('jenilson-leite', 2024, 171263.27, 0, 0, 0, 0, '[{"nome":"Direção Municipal/Comissão Provisória","valor":100668.27,"tipo":"PJ"},{"nome":"Direção Nacional","valor":50000,"tipo":"PJ"},{"nome":"EDINALDO MUNIZ DOS SANTOS","valor":10000,"tipo":"PF"},{"nome":"Direção Estadual/Distrital","valor":4595,"tipo":"PJ"},{"nome":"JANILSON LOPES LEITE","valor":4000,"tipo":"PF"},{"nome":"DAVILENE ANAISSI MENENZES","valor":2000,"tipo":"PF"}]'::jsonb),
  ('wanderlei-barbosa', 2010, 320343.66, 0, 0, 0, 0, '[{"nome":"Comitê Financeiro Único","valor":157349.67,"tipo":"PJ"},{"nome":"ELEIÇÃO 2010 DARCI MARTINS COELHO DEPUTADO FEDERAL","valor":77000,"tipo":"PJ"},{"nome":"WANDERLEI BARBOSA CASTRO","valor":38577.99,"tipo":"PF"},{"nome":"ELEIÇÃO 2010 MARCELO DE CARVALHO MIRANDA SENADOR","valor":25000,"tipo":"PJ"},{"nome":"MILTON NERIS SANTANA","valor":15000,"tipo":"PF"},{"nome":"SOLNA GRÁFICA E EDITORA LTDA EPP","valor":4900,"tipo":"PJ"},{"nome":"BLANDINA VIEIRA LEITE CASTRO","valor":1500,"tipo":"PF"},{"nome":"JORNAL FOLHA DO JALAPÃO LTDA","valor":500,"tipo":"PJ"},{"nome":"ELEIÇÃO 2010 LAUREZ DA ROCHA MOREIRA DEPUTADO FEDERAL","valor":444,"tipo":"PJ"},{"nome":"ELEIÇÃO 2010 LAUREZ DA ROCHA MOREIRA DEPUTADO FEDERAL PSB","valor":72,"tipo":"PJ"}]'::jsonb),
  ('wanderlei-barbosa', 2022, 6594172.83, 0, 0, 0, 0, '[{"nome":"Direção Nacional","valor":6351972.83,"tipo":"PJ"},{"nome":"HELENA SPONHOLZ MINIKOVSKI","valor":20000,"tipo":"PF"},{"nome":"RICARDO ANTONIO MINIKOVSKI","valor":20000,"tipo":"PF"},{"nome":"DENISE ROCHA DOMINGUES","valor":17000,"tipo":"PF"},{"nome":"YURI DOS SANTOS MASSOLI","valor":12000,"tipo":"PF"},{"nome":"ERNANDES ANDRE SOUSA","valor":10000,"tipo":"PF"},{"nome":"KLEDSON DE MOURA LIMA","valor":10000,"tipo":"PF"},{"nome":"JAHYR CUNHA SPONHOLZ","valor":10000,"tipo":"PF"},{"nome":"GILSON SOUSA SILVA","valor":10000,"tipo":"PF"},{"nome":"EVA VENANCIO GOMES CALDEIRA","valor":10000,"tipo":"PF"}]'::jsonb)
) AS v(slug, ano_eleicao, total_arrecadado, total_fundo_partidario, total_fundo_eleitoral, total_pessoa_fisica, total_recursos_proprios, maiores_doadores) ON c.slug = v.slug
ON CONFLICT (candidato_id, ano_eleicao) DO UPDATE SET
  total_arrecadado = EXCLUDED.total_arrecadado,
  total_fundo_partidario = EXCLUDED.total_fundo_partidario,
  total_fundo_eleitoral = EXCLUDED.total_fundo_eleitoral,
  total_pessoa_fisica = EXCLUDED.total_pessoa_fisica,
  total_recursos_proprios = EXCLUDED.total_recursos_proprios,
  maiores_doadores = EXCLUDED.maiores_doadores,
  fonte = EXCLUDED.fonte;

DO $$
DECLARE missing_patrimonio integer; missing_financiamento integer;
BEGIN
  SELECT count(*) INTO missing_patrimonio
  FROM (VALUES ('jenilson-leite', 2014), ('jenilson-leite', 2018), ('jenilson-leite', 2022), ('jenilson-leite', 2024), ('wanderlei-barbosa', 2010), ('wanderlei-barbosa', 2018), ('wanderlei-barbosa', 2022)) AS expected(slug, ano)
  LEFT JOIN public.candidatos c ON c.slug = expected.slug
  LEFT JOIN public.patrimonio p ON p.candidato_id = c.id AND p.ano_eleicao = expected.ano
  WHERE p.id IS NULL;

  SELECT count(*) INTO missing_financiamento
  FROM (VALUES ('jenilson-leite', 2014), ('jenilson-leite', 2018), ('jenilson-leite', 2022), ('jenilson-leite', 2024), ('wanderlei-barbosa', 2010), ('wanderlei-barbosa', 2022)) AS expected(slug, ano)
  LEFT JOIN public.candidatos c ON c.slug = expected.slug
  LEFT JOIN public.financiamento f ON f.candidato_id = c.id AND f.ano_eleicao = expected.ano
  WHERE f.id IS NULL;

  IF missing_patrimonio <> 0 OR missing_financiamento <> 0 THEN
    RAISE EXCEPTION 'TSE money reconciliation incomplete: patrimonio %, financiamento %', missing_patrimonio, missing_financiamento;
  END IF;
END $$;
