-- ============================================
-- Legislacao full-site: margarete-coelho / Camara Dados Abertos / projetos_lei
-- Coverage ampliado parcial: Lote A autoria principal Camara
-- ============================================
-- Fonte oficial: Camara dos Deputados - Dados Abertos
--   https://dadosabertos.camara.leg.br/api/v2/deputados/204430
--   https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id}
--   https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id}/autores
--
-- Artefato de auditoria:
--   fonte interna de curadoria
--
-- Coverage:
--   coverage_id    = margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506
--   coverage_scope = inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506
--
-- Filtro factual: das 100 rows Camara legacy existentes, somente 61
-- foram marcadas com coverage_id porque a API oficial confirmou
-- idDeputado=204430, tipo Deputado(a), ordemAssinatura=1.
-- 39 rows permanecem sem coverage por coautoria/sem autoria verificavel.
--
-- Esta migration NAO escreve em legislacao_mandato_executivo.
-- Esta migration NAO insere, deleta ou trunca rows.
-- ============================================

DO $$
DECLARE
  cand_id uuid;
  total_pl int;
  target_present int;
  target_with_other_coverage int;
  lme_count int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'margarete-coelho';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'margarete-coelho: candidato ausente neste banco local/CI minimo; coverage Camara pulado';
    RETURN;
  END IF;

  SELECT count(*) INTO total_pl FROM projetos_lei WHERE candidato_id = cand_id;
  IF total_pl <> 100 THEN
    RAISE EXCEPTION 'Pre-condicao margarete-coelho: esperadas 100 rows legacy em projetos_lei, encontradas %', total_pl;
  END IF;

  SELECT count(*) INTO target_present
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND fonte = 'Camara'
    AND proposicao_id_api IN ('2342326', '2333890', '2317872', '2313291', '2306836', '2334429', '2342324', '2334428', '2320547', '2317756', '2342323', '2333936', '2319624', '2317880', '2317755', '2341643', '2333931', '2317878', '2304833', '2321496', '2317757', '2304161', '2300345', '2298940', '2298115', '2297672', '2297072', '2294452', '2304835', '2303556', '2298937', '2298108', '2297554', '2291546', '2300346', '2299965', '2298505', '2297883', '2297513', '2294677', '2300143', '2298506', '2298058', '2297547', '2295792', '2293285', '2298931', '2297553', '2295793', '2344639', '2318842', '2304581', '2293284', '2342331', '2342325', '2342330', '2342329', '2310697', '2300144', '2298073', '2342328');
  IF target_present <> 61 THEN
    RAISE EXCEPTION 'Pre-condicao margarete-coelho: esperadas 61 rows alvo Camara presentes, encontradas %', target_present;
  END IF;

  SELECT count(*) INTO target_with_other_coverage
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND proposicao_id_api IN ('2342326', '2333890', '2317872', '2313291', '2306836', '2334429', '2342324', '2334428', '2320547', '2317756', '2342323', '2333936', '2319624', '2317880', '2317755', '2341643', '2333931', '2317878', '2304833', '2321496', '2317757', '2304161', '2300345', '2298940', '2298115', '2297672', '2297072', '2294452', '2304835', '2303556', '2298937', '2298108', '2297554', '2291546', '2300346', '2299965', '2298505', '2297883', '2297513', '2294677', '2300143', '2298506', '2298058', '2297547', '2295792', '2293285', '2298931', '2297553', '2295793', '2344639', '2318842', '2304581', '2293284', '2342331', '2342325', '2342330', '2342329', '2310697', '2300144', '2298073', '2342328')
    AND coverage_id IS NOT NULL
    AND coverage_id <> 'margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506';
  IF target_with_other_coverage <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao margarete-coelho: % rows alvo ja tem coverage_id divergente', target_with_other_coverage;
  END IF;

  SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao margarete-coelho: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;
END $$;

CREATE TEMP TABLE _coverage_margarete_coelho_camara_lote_a ON COMMIT DROP AS
SELECT *
FROM (
  VALUES
    ('2342326', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342326', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342326/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342326', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2342326","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342326","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342326/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342326","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2333890', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333890', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333890/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333890', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2333890","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333890","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333890/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333890","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2317872', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317872', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317872/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317872', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2317872","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317872","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317872/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317872","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2313291', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2313291', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2313291/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2313291', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2313291","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2313291","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2313291/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2313291","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2306836', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306836', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306836/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306836', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2306836","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306836","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306836/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306836","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2334429', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334429', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334429/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334429', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2334429","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334429","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334429/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334429","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2342324', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342324', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342324/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342324', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2342324","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342324","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342324/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342324","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2334428', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334428', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334428/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334428', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2334428","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334428","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334428/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2334428","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2320547', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2320547', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2320547/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2320547', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2320547","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2320547","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2320547/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2320547","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2317756', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317756', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317756/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317756', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2317756","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317756","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317756/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317756","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2342323', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342323', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342323/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342323', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2342323","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342323","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342323/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342323","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2333936', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333936', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333936/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333936', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2333936","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333936","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333936/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333936","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2319624', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319624', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319624/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319624', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2319624","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319624","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319624/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319624","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2317880', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317880', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317880/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317880', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2317880","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317880","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317880/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317880","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2317755', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317755', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317755/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317755', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2317755","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317755","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317755/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317755","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2341643', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341643', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341643/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341643', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2341643","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341643","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341643/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2341643","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2333931', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333931', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333931/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333931', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2333931","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333931","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333931/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2333931","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2317878', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317878', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317878/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317878', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2317878","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317878","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317878/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317878","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2304833', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304833', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304833/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304833', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2304833","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304833","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304833/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304833","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2321496', 1, 7, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2321496', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2321496/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2321496', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2321496","ordem_assinatura":1,"total_autores":7,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2321496","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2321496/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2321496","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2317757', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317757', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317757/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317757', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2317757","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317757","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317757/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317757","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2304161', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304161', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304161/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304161', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2304161","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304161","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304161/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304161","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2300345', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300345', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300345/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300345', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2300345","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300345","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300345/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300345","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2298940', 1, 3, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298940', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298940/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298940', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2298940","ordem_assinatura":1,"total_autores":3,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298940","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298940/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298940","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2298115', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298115', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298115/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298115', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2298115","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298115","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298115/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298115","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2297672', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297672', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297672/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297672', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2297672","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297672","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297672/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297672","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2297072', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297072', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297072/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297072', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2297072","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297072","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297072/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297072","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2294452', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2294452', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2294452/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2294452', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2294452","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2294452","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2294452/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2294452","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2304835', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304835', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304835/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304835', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2304835","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304835","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304835/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304835","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2303556', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2303556', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2303556/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2303556', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2303556","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2303556","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2303556/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2303556","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2298937', 1, 3, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298937', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298937/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298937', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2298937","ordem_assinatura":1,"total_autores":3,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298937","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298937/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298937","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2298108', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298108', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298108/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298108', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2298108","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298108","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298108/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298108","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2297554', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297554', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297554/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297554', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2297554","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297554","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297554/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297554","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2291546', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2291546', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2291546/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2291546', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2291546","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2291546","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2291546/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2291546","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2300346', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300346', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300346/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300346', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2300346","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300346","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300346/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300346","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2299965', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2299965', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2299965/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2299965', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2299965","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2299965","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2299965/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2299965","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2298505', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298505', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298505/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298505', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2298505","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298505","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298505/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298505","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2297883', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297883', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297883/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297883', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2297883","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297883","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297883/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297883","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2297513', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297513', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297513/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297513', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2297513","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297513","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297513/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297513","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2294677', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2294677', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2294677/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2294677', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2294677","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2294677","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2294677/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2294677","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2300143', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300143', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300143/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300143', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2300143","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300143","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300143/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300143","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2298506', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298506', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298506/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298506', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2298506","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298506","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298506/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298506","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2298058', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298058', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298058/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298058', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2298058","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298058","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298058/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298058","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2297547', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297547', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297547/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297547', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2297547","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297547","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297547/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297547","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2295792', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295792', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295792/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295792', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2295792","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295792","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295792/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295792","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2293285', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2293285', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2293285/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2293285', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2293285","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2293285","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2293285/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2293285","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2298931', 1, 3, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298931', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298931/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298931', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2298931","ordem_assinatura":1,"total_autores":3,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298931","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298931/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298931","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2297553', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297553', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297553/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297553', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2297553","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297553","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297553/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2297553","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2295793', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295793', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295793/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295793', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2295793","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295793","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295793/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295793","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2344639', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2344639', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2344639/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2344639', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2344639","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2344639","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2344639/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2344639","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2318842', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318842', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318842/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318842', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2318842","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318842","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318842/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318842","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2304581', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304581', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304581/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304581', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2304581","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304581","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304581/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304581","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2293284', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2293284', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2293284/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2293284', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2293284","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2293284","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2293284/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2293284","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2342331', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342331', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342331/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342331', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2342331","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342331","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342331/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342331","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2342325', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342325', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342325/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342325', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2342325","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342325","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342325/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342325","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2342330', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342330', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342330/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342330', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2342330","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342330","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342330/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342330","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2342329', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342329', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342329/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342329', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2342329","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342329","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342329/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342329","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2310697', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310697', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310697/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310697', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2310697","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310697","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310697/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310697","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2300144', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300144', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300144/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300144', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2300144","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300144","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300144/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2300144","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2298073', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298073', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298073/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298073', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2298073","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298073","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298073/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298073","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb),
    ('2342328', 1, 1, 'Margarete Coelho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342328', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342328/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342328', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"margarete-coelho-camara-lote-a-20260506","coverage_id":"margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":204430,"proposicao_id_api":"2342328","ordem_assinatura":1,"total_autores":1,"autor_nome":"Margarete Coelho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342328","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342328/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2342328","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T07:45:25.473Z"}'::jsonb)
) AS v(
  proposicao_id_api,
  ordem_assinatura,
  total_autores,
  autor_nome,
  autor_tipo,
  detalhe_endpoint,
  autores_endpoint,
  public_url,
  metadata_patch
);

WITH target AS (
  SELECT c.id AS candidato_id
  FROM candidatos c
  WHERE c.slug = 'margarete-coelho'
)
UPDATE projetos_lei pl
SET
  coverage_id = 'margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506',
  coverage_scope = 'inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506',
  metadata = COALESCE(pl.metadata, '{}'::jsonb) || seed.metadata_patch
FROM target
JOIN _coverage_margarete_coelho_camara_lote_a seed ON TRUE
WHERE pl.candidato_id = target.candidato_id
  AND pl.fonte = 'Camara'
  AND pl.proposicao_id_api = seed.proposicao_id_api
  AND (pl.coverage_id IS NULL OR pl.coverage_id = 'margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506');

DO $$
DECLARE
  cand_id uuid;
  with_target_coverage int;
  remaining_null int;
  lme_count int;
  other_slugs_with_target int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'margarete-coelho';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'margarete-coelho: pos-condicao pulada porque candidato nao existe neste banco local/CI minimo';
    RETURN;
  END IF;

  SELECT count(*) INTO with_target_coverage
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id = 'margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506'
    AND coverage_scope = 'inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506';
  IF with_target_coverage <> 61 THEN
    RAISE EXCEPTION 'Pos-apply margarete-coelho: esperadas 61 rows com coverage_id alvo, encontradas %', with_target_coverage;
  END IF;

  SELECT count(*) INTO remaining_null
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id IS NULL;
  IF remaining_null <> 39 THEN
    RAISE EXCEPTION 'Pos-apply margarete-coelho: esperadas 39 rows sem coverage por limite documentado, encontradas %', remaining_null;
  END IF;

  SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pos-apply margarete-coelho: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;

  SELECT count(*) INTO other_slugs_with_target
  FROM projetos_lei
  WHERE candidato_id <> cand_id
    AND coverage_id = 'margarete-coelho-camara-autoria-principal-ampliado-parcial-lote-a-20260506';
  IF other_slugs_with_target <> 0 THEN
    RAISE EXCEPTION 'Pos-apply margarete-coelho: % rows de outros slugs com coverage_id alvo', other_slugs_with_target;
  END IF;

  RAISE NOTICE 'Pos-apply margarete-coelho Camara Lote A: coverage=% sem_coverage=% lme=%', with_target_coverage, remaining_null, lme_count;
END $$;
