-- ============================================
-- Legislacao full-site: adriana-accorsi / Camara Dados Abertos / projetos_lei
-- Coverage ampliado parcial: Lote A autoria principal Camara
-- ============================================
-- Fonte oficial: Camara dos Deputados - Dados Abertos
--   https://dadosabertos.camara.leg.br/api/v2/deputados/220565
--   https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id}
--   https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id}/autores
--
-- Artefato de auditoria:
--   fonte interna de curadoria
--
-- Coverage:
--   coverage_id    = adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505
--   coverage_scope = inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505
--
-- Filtro factual: das 100 rows Camara legacy existentes, somente 56
-- foram marcadas com coverage_id porque a API oficial confirmou
-- idDeputado=220565, tipo Deputado(a), ordemAssinatura=1.
-- 44 rows permanecem sem coverage por coautoria/sem autoria verificavel.
--
-- Esta migration NAO escreve em legislacao_mandato_executivo.
-- Esta migration NAO insere, deleta ou trunca rows.
-- ============================================

DO $$
DECLARE
  cand_id uuid;
  total_pl int;
  target_present int;
  target_with_other_coverage int;
  lme_count int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'adriana-accorsi';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'adriana-accorsi: candidato ausente neste banco local/CI minimo; coverage Camara pulado';
    RETURN;
  END IF;

  SELECT count(*) INTO total_pl FROM projetos_lei WHERE candidato_id = cand_id;
  IF total_pl <> 100 THEN
    RAISE EXCEPTION 'Pre-condicao adriana-accorsi: esperadas 100 rows legacy em projetos_lei, encontradas %', total_pl;
  END IF;

  SELECT count(*) INTO target_present
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND fonte = 'Camara'
    AND proposicao_id_api IN ('2611367', '2590013', '2567675', '2611419', '2607441', '2590136', '2565100', '2596320', '2591492', '2589505', '2567557', '2564147', '2548865', '2596319', '2590139', '2567553', '2563271', '2548861', '2541104', '2534298', '2528214', '2527879', '2526855', '2526442', '2579985', '2568004', '2555266', '2549737', '2545295', '2539901', '2528058', '2527869', '2526483', '2525450', '2566200', '2539900', '2529041', '2528054', '2526858', '2526482', '2527872', '2526853', '2525455', '2529029', '2528039', '2526857', '2526452', '2589471', '2541022', '2590134', '2565099', '2555265', '2549235', '2561384', '2537001', '2528212');
  IF target_present <> 56 THEN
    RAISE EXCEPTION 'Pre-condicao adriana-accorsi: esperadas 56 rows alvo Camara presentes, encontradas %', target_present;
  END IF;

  SELECT count(*) INTO target_with_other_coverage
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND proposicao_id_api IN ('2611367', '2590013', '2567675', '2611419', '2607441', '2590136', '2565100', '2596320', '2591492', '2589505', '2567557', '2564147', '2548865', '2596319', '2590139', '2567553', '2563271', '2548861', '2541104', '2534298', '2528214', '2527879', '2526855', '2526442', '2579985', '2568004', '2555266', '2549737', '2545295', '2539901', '2528058', '2527869', '2526483', '2525450', '2566200', '2539900', '2529041', '2528054', '2526858', '2526482', '2527872', '2526853', '2525455', '2529029', '2528039', '2526857', '2526452', '2589471', '2541022', '2590134', '2565099', '2555265', '2549235', '2561384', '2537001', '2528212')
    AND coverage_id IS NOT NULL
    AND coverage_id <> 'adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505';
  IF target_with_other_coverage <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao adriana-accorsi: % rows alvo ja tem coverage_id divergente', target_with_other_coverage;
  END IF;

  SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao adriana-accorsi: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;
END $$;

CREATE TEMP TABLE _coverage_adriana_accorsi_camara_lote_a ON COMMIT DROP AS
SELECT *
FROM (
  VALUES
    ('2611367', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611367', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611367/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611367', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2611367","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611367","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611367/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611367","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2590013', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590013', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590013/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590013', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2590013","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590013","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590013/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590013","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2567675', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567675', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567675/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567675', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2567675","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567675","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567675/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567675","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2611419', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611419', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611419/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611419', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2611419","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611419","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611419/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611419","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2607441', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2607441', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2607441/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2607441', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2607441","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2607441","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2607441/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2607441","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2590136', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590136', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590136/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590136', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2590136","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590136","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590136/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590136","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2565100', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565100', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565100/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565100', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2565100","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565100","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565100/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565100","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2596320', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2596320', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2596320/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2596320', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2596320","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2596320","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2596320/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2596320","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2591492', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2591492', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2591492/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2591492', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2591492","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2591492","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2591492/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2591492","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2589505', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2589505', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2589505/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2589505', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2589505","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2589505","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2589505/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2589505","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2567557', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567557', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567557/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567557', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2567557","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567557","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567557/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567557","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2564147', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564147', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564147/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564147', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2564147","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564147","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564147/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564147","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2548865', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548865', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548865/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548865', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2548865","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548865","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548865/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548865","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2596319', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2596319', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2596319/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2596319', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2596319","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2596319","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2596319/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2596319","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2590139', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590139', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590139/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590139', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2590139","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590139","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590139/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590139","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2567553', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567553', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567553/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567553', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2567553","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567553","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567553/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567553","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2563271', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563271', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563271/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563271', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2563271","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563271","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563271/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563271","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2548861', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548861', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548861/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548861', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2548861","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548861","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548861/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548861","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2541104', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2541104', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2541104/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2541104', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2541104","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2541104","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2541104/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2541104","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2534298', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2534298', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2534298/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2534298', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2534298","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2534298","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2534298/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2534298","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2528214', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528214', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528214/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528214', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2528214","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528214","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528214/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528214","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2527879', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2527879', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2527879/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2527879', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2527879","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2527879","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2527879/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2527879","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2526855', 1, 2, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526855', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526855/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526855', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2526855","ordem_assinatura":1,"total_autores":2,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526855","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526855/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526855","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2526442', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526442', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526442/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526442', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2526442","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526442","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526442/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526442","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2579985', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2579985', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2579985/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2579985', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2579985","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2579985","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2579985/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2579985","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2568004', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2568004', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2568004/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2568004', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2568004","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2568004","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2568004/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2568004","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2555266', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2555266', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2555266/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2555266', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2555266","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2555266","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2555266/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2555266","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2549737', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2549737', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2549737/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2549737', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2549737","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2549737","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2549737/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2549737","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2545295', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2545295', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2545295/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2545295', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2545295","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2545295","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2545295/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2545295","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2539901', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2539901', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2539901/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2539901', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2539901","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2539901","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2539901/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2539901","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2528058', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528058', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528058/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528058', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2528058","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528058","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528058/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528058","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2527869', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2527869', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2527869/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2527869', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2527869","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2527869","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2527869/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2527869","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2526483', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526483', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526483/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526483', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2526483","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526483","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526483/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526483","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2525450', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2525450', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2525450/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2525450', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2525450","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2525450","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2525450/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2525450","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2566200', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2566200', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2566200/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2566200', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2566200","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2566200","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2566200/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2566200","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2539900', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2539900', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2539900/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2539900', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2539900","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2539900","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2539900/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2539900","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2529041', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2529041', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2529041/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2529041', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2529041","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2529041","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2529041/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2529041","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2528054', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528054', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528054/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528054', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2528054","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528054","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528054/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528054","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2526858', 1, 2, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526858', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526858/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526858', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2526858","ordem_assinatura":1,"total_autores":2,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526858","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526858/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526858","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2526482', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526482', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526482/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526482', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2526482","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526482","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526482/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526482","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2527872', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2527872', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2527872/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2527872', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2527872","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2527872","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2527872/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2527872","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2526853', 1, 2, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526853', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526853/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526853', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2526853","ordem_assinatura":1,"total_autores":2,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526853","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526853/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526853","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2525455', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2525455', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2525455/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2525455', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2525455","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2525455","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2525455/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2525455","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2529029', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2529029', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2529029/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2529029', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2529029","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2529029","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2529029/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2529029","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2528039', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528039', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528039/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528039', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2528039","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528039","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528039/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528039","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2526857', 1, 2, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526857', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526857/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526857', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2526857","ordem_assinatura":1,"total_autores":2,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526857","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526857/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526857","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2526452', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526452', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526452/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526452', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2526452","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526452","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526452/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2526452","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2589471', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2589471', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2589471/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2589471', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2589471","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2589471","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2589471/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2589471","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2541022', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2541022', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2541022/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2541022', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2541022","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2541022","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2541022/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2541022","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2590134', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590134', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590134/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590134', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2590134","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590134","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590134/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2590134","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2565099', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565099', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565099/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565099', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2565099","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565099","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565099/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565099","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2555265', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2555265', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2555265/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2555265', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2555265","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2555265","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2555265/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2555265","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2549235', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2549235', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2549235/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2549235', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2549235","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2549235","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2549235/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2549235","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2561384', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561384', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561384/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561384', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2561384","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561384","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561384/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561384","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2537001', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2537001', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2537001/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2537001', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2537001","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2537001","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2537001/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2537001","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb),
    ('2528212', 1, 1, 'Delegada Adriana Accorsi', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528212', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528212/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528212', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"adriana-accorsi-camara-lote-a-20260505","coverage_id":"adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220565,"proposicao_id_api":"2528212","ordem_assinatura":1,"total_autores":1,"autor_nome":"Delegada Adriana Accorsi","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528212","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528212/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2528212","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T02:39:39.950Z"}'::jsonb)
) AS v(
  proposicao_id_api,
  ordem_assinatura,
  total_autores,
  autor_nome,
  autor_tipo,
  detalhe_endpoint,
  autores_endpoint,
  public_url,
  metadata_patch
);

WITH target AS (
  SELECT c.id AS candidato_id
  FROM candidatos c
  WHERE c.slug = 'adriana-accorsi'
)
UPDATE projetos_lei pl
SET
  coverage_id = 'adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505',
  coverage_scope = 'inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505',
  metadata = COALESCE(pl.metadata, '{}'::jsonb) || seed.metadata_patch
FROM target
JOIN _coverage_adriana_accorsi_camara_lote_a seed ON TRUE
WHERE pl.candidato_id = target.candidato_id
  AND pl.fonte = 'Camara'
  AND pl.proposicao_id_api = seed.proposicao_id_api
  AND (pl.coverage_id IS NULL OR pl.coverage_id = 'adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505');

DO $$
DECLARE
  cand_id uuid;
  with_target_coverage int;
  remaining_null int;
  lme_count int;
  other_slugs_with_target int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'adriana-accorsi';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'adriana-accorsi: pos-condicao pulada porque candidato nao existe neste banco local/CI minimo';
    RETURN;
  END IF;

  SELECT count(*) INTO with_target_coverage
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id = 'adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505'
    AND coverage_scope = 'inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260505';
  IF with_target_coverage <> 56 THEN
    RAISE EXCEPTION 'Pos-apply adriana-accorsi: esperadas 56 rows com coverage_id alvo, encontradas %', with_target_coverage;
  END IF;

  SELECT count(*) INTO remaining_null
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id IS NULL;
  IF remaining_null <> 44 THEN
    RAISE EXCEPTION 'Pos-apply adriana-accorsi: esperadas 44 rows sem coverage por limite documentado, encontradas %', remaining_null;
  END IF;

  SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pos-apply adriana-accorsi: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;

  SELECT count(*) INTO other_slugs_with_target
  FROM projetos_lei
  WHERE candidato_id <> cand_id
    AND coverage_id = 'adriana-accorsi-camara-autoria-principal-ampliado-parcial-lote-a-20260505';
  IF other_slugs_with_target <> 0 THEN
    RAISE EXCEPTION 'Pos-apply adriana-accorsi: % rows de outros slugs com coverage_id alvo', other_slugs_with_target;
  END IF;

  RAISE NOTICE 'Pos-apply adriana-accorsi Camara Lote A: coverage=% sem_coverage=% lme=%', with_target_coverage, remaining_null, lme_count;
END $$;
