-- ============================================
-- Legislacao full-site: teresa-surita / Camara Dados Abertos / projetos_lei
-- Coverage ampliado parcial: Lote A autoria principal Camara
-- ============================================
-- Fonte oficial: Camara dos Deputados - Dados Abertos
--   https://dadosabertos.camara.leg.br/api/v2/deputados/160608
--   https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id}
--   https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id}/autores
--
-- Artefato de auditoria:
--   fonte interna de curadoria
--
-- Coverage:
--   coverage_id    = teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506
--   coverage_scope = inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506
--
-- Filtro factual: das 88 rows Camara legacy existentes, somente 77
-- foram marcadas com coverage_id porque a API oficial confirmou
-- idDeputado=160608, tipo Deputado(a), ordemAssinatura=1.
-- 11 rows permanecem sem coverage por coautoria/sem autoria verificavel.
--
-- Esta migration NAO escreve em legislacao_mandato_executivo.
-- Esta migration NAO insere, deleta ou trunca rows.
-- ============================================

DO $$
DECLARE
  cand_id uuid;
  total_pl int;
  target_present int;
  target_with_other_coverage int;
  lme_count int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'teresa-surita';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'teresa-surita: candidato ausente neste banco local/CI minimo; coverage Camara pulado';
    RETURN;
  END IF;

  SELECT count(*) INTO total_pl FROM projetos_lei WHERE candidato_id = cand_id;
  IF total_pl <> 88 THEN
    RAISE EXCEPTION 'Pre-condicao teresa-surita: esperadas 88 rows legacy em projetos_lei, encontradas %', total_pl;
  END IF;

  SELECT count(*) INTO target_present
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND fonte = 'Camara'
    AND proposicao_id_api IN ('560644', '550128', '550129', '543070', '531893', '527225', '560587', '550833', '522798', '495439', '550837', '549504', '549501', '543680', '543076', '538749', '545373', '531892', '527124', '521563', '518425', '512504', '510919', '509082', '507752', '507708', '507701', '505021', '493173', '169829', '537810', '530297', '522800', '519366', '515396', '512376', '509108', '507758', '507748', '507705', '507699', '499495', '234019', '15801', '537809', '530087', '522799', '519364', '514572', '512374', '509084', '507757', '507745', '507704', '507698', '497042', '191118', '526255', '523411', '521453', '509407', '507760', '507751', '507706', '507700', '241888', '169464', '519363', '514025', '512373', '509083', '507756', '507710', '507703', '507695', '181003', '518070');
  IF target_present <> 77 THEN
    RAISE EXCEPTION 'Pre-condicao teresa-surita: esperadas 77 rows alvo Camara presentes, encontradas %', target_present;
  END IF;

  SELECT count(*) INTO target_with_other_coverage
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND proposicao_id_api IN ('560644', '550128', '550129', '543070', '531893', '527225', '560587', '550833', '522798', '495439', '550837', '549504', '549501', '543680', '543076', '538749', '545373', '531892', '527124', '521563', '518425', '512504', '510919', '509082', '507752', '507708', '507701', '505021', '493173', '169829', '537810', '530297', '522800', '519366', '515396', '512376', '509108', '507758', '507748', '507705', '507699', '499495', '234019', '15801', '537809', '530087', '522799', '519364', '514572', '512374', '509084', '507757', '507745', '507704', '507698', '497042', '191118', '526255', '523411', '521453', '509407', '507760', '507751', '507706', '507700', '241888', '169464', '519363', '514025', '512373', '509083', '507756', '507710', '507703', '507695', '181003', '518070')
    AND coverage_id IS NOT NULL
    AND coverage_id <> 'teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506';
  IF target_with_other_coverage <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao teresa-surita: % rows alvo ja tem coverage_id divergente', target_with_other_coverage;
  END IF;

  SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao teresa-surita: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;
END $$;

CREATE TEMP TABLE _coverage_teresa_surita_camara_lote_a ON COMMIT DROP AS
SELECT *
FROM (
  VALUES
    ('560644', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/560644', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/560644/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/560644', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"560644","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/560644","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/560644/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/560644","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('550128', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/550128', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/550128/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/550128', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"550128","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/550128","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/550128/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/550128","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('550129', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/550129', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/550129/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/550129', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"550129","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/550129","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/550129/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/550129","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('543070', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/543070', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/543070/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/543070', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"543070","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/543070","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/543070/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/543070","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('531893', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/531893', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/531893/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/531893', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"531893","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/531893","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/531893/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/531893","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('527225', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/527225', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/527225/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/527225', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"527225","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/527225","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/527225/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/527225","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('560587', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/560587', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/560587/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/560587', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"560587","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/560587","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/560587/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/560587","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('550833', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/550833', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/550833/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/550833', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"550833","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/550833","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/550833/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/550833","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('522798', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/522798', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/522798/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/522798', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"522798","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/522798","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/522798/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/522798","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('495439', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/495439', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/495439/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/495439', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"495439","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/495439","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/495439/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/495439","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('550837', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/550837', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/550837/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/550837', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"550837","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/550837","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/550837/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/550837","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('549504', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549504', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549504/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549504', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"549504","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549504","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549504/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549504","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('549501', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549501', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549501/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549501', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"549501","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549501","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549501/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549501","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('543680', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/543680', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/543680/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/543680', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"543680","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/543680","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/543680/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/543680","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('543076', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/543076', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/543076/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/543076', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"543076","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/543076","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/543076/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/543076","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('538749', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/538749', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/538749/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/538749', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"538749","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/538749","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/538749/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/538749","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('545373', 1, 9, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/545373', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/545373/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/545373', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"545373","ordem_assinatura":1,"total_autores":9,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/545373","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/545373/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/545373","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('531892', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/531892', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/531892/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/531892', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"531892","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/531892","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/531892/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/531892","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('527124', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/527124', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/527124/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/527124', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"527124","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/527124","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/527124/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/527124","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('521563', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/521563', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/521563/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/521563', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"521563","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/521563","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/521563/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/521563","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('518425', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/518425', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/518425/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/518425', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"518425","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/518425","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/518425/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/518425","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('512504', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/512504', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/512504/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/512504', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"512504","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/512504","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/512504/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/512504","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('510919', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/510919', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/510919/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/510919', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"510919","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/510919","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/510919/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/510919","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('509082', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/509082', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/509082/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/509082', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"509082","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/509082","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/509082/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/509082","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('507752', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507752', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507752/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507752', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"507752","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507752","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507752/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507752","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('507708', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507708', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507708/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507708', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"507708","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507708","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507708/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507708","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('507701', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507701', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507701/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507701', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"507701","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507701","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507701/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507701","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('505021', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/505021', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/505021/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/505021', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"505021","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/505021","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/505021/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/505021","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('493173', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/493173', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/493173/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/493173', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"493173","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/493173","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/493173/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/493173","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('169829', 1, 1, 'TERESA JUCA', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/169829', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/169829/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/169829', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"169829","ordem_assinatura":1,"total_autores":1,"autor_nome":"TERESA JUCA","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/169829","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/169829/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/169829","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('537810', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/537810', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/537810/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/537810', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"537810","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/537810","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/537810/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/537810","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('530297', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/530297', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/530297/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/530297', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"530297","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/530297","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/530297/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/530297","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('522800', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/522800', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/522800/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/522800', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"522800","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/522800","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/522800/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/522800","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('519366', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/519366', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/519366/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/519366', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"519366","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/519366","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/519366/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/519366","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('515396', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/515396', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/515396/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/515396', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"515396","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/515396","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/515396/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/515396","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('512376', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/512376', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/512376/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/512376', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"512376","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/512376","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/512376/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/512376","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('509108', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/509108', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/509108/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/509108', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"509108","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/509108","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/509108/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/509108","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('507758', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507758', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507758/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507758', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"507758","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507758","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507758/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507758","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('507748', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507748', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507748/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507748', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"507748","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507748","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507748/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507748","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('507705', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507705', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507705/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507705', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"507705","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507705","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507705/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507705","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('507699', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507699', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507699/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507699', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"507699","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507699","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507699/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507699","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('499495', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/499495', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/499495/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/499495', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"499495","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/499495","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/499495/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/499495","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('234019', 1, 1, 'TERESA JUCA', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/234019', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/234019/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/234019', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"234019","ordem_assinatura":1,"total_autores":1,"autor_nome":"TERESA JUCA","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/234019","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/234019/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/234019","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('15801', 1, 1, 'TERESA JUCA', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/15801', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/15801/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/15801', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"15801","ordem_assinatura":1,"total_autores":1,"autor_nome":"TERESA JUCA","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/15801","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/15801/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/15801","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('537809', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/537809', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/537809/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/537809', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"537809","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/537809","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/537809/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/537809","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('530087', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/530087', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/530087/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/530087', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"530087","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/530087","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/530087/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/530087","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('522799', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/522799', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/522799/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/522799', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"522799","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/522799","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/522799/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/522799","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('519364', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/519364', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/519364/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/519364', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"519364","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/519364","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/519364/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/519364","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('514572', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/514572', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/514572/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/514572', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"514572","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/514572","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/514572/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/514572","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('512374', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/512374', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/512374/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/512374', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"512374","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/512374","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/512374/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/512374","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('509084', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/509084', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/509084/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/509084', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"509084","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/509084","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/509084/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/509084","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('507757', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507757', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507757/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507757', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"507757","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507757","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507757/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507757","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('507745', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507745', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507745/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507745', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"507745","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507745","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507745/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507745","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('507704', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507704', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507704/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507704', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"507704","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507704","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507704/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507704","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('507698', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507698', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507698/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507698', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"507698","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507698","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507698/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507698","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('497042', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/497042', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/497042/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/497042', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"497042","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/497042","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/497042/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/497042","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('191118', 1, 1, 'TERESA JUCA', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/191118', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/191118/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/191118', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"191118","ordem_assinatura":1,"total_autores":1,"autor_nome":"TERESA JUCA","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/191118","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/191118/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/191118","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('526255', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/526255', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/526255/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/526255', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"526255","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/526255","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/526255/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/526255","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('523411', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/523411', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/523411/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/523411', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"523411","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/523411","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/523411/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/523411","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('521453', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/521453', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/521453/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/521453', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"521453","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/521453","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/521453/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/521453","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('509407', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/509407', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/509407/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/509407', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"509407","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/509407","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/509407/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/509407","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('507760', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507760', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507760/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507760', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"507760","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507760","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507760/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507760","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('507751', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507751', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507751/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507751', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"507751","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507751","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507751/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507751","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('507706', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507706', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507706/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507706', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"507706","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507706","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507706/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507706","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('507700', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507700', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507700/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507700', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"507700","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507700","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507700/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507700","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('241888', 1, 1, 'TERESA JUCA', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/241888', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/241888/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/241888', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"241888","ordem_assinatura":1,"total_autores":1,"autor_nome":"TERESA JUCA","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/241888","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/241888/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/241888","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('169464', 1, 1, 'TERESA JUCA', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/169464', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/169464/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/169464', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"169464","ordem_assinatura":1,"total_autores":1,"autor_nome":"TERESA JUCA","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/169464","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/169464/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/169464","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('519363', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/519363', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/519363/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/519363', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"519363","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/519363","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/519363/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/519363","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('514025', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/514025', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/514025/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/514025', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"514025","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/514025","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/514025/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/514025","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('512373', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/512373', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/512373/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/512373', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"512373","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/512373","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/512373/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/512373","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('509083', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/509083', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/509083/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/509083', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"509083","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/509083","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/509083/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/509083","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('507756', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507756', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507756/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507756', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"507756","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507756","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507756/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507756","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('507710', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507710', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507710/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507710', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"507710","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507710","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507710/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507710","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('507703', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507703', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507703/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507703', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"507703","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507703","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507703/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507703","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('507695', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507695', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507695/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/507695', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"507695","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507695","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507695/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/507695","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('181003', 1, 1, 'TERESA JUCA', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/181003', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/181003/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/181003', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"181003","ordem_assinatura":1,"total_autores":1,"autor_nome":"TERESA JUCA","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/181003","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/181003/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/181003","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb),
    ('518070', 1, 1, 'Teresa Surita', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/518070', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/518070/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/518070', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"teresa-surita-camara-lote-a-20260506","coverage_id":"teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160608,"proposicao_id_api":"518070","ordem_assinatura":1,"total_autores":1,"autor_nome":"Teresa Surita","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/518070","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/518070/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/518070","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:21:24.831Z"}'::jsonb)
) AS v(
  proposicao_id_api,
  ordem_assinatura,
  total_autores,
  autor_nome,
  autor_tipo,
  detalhe_endpoint,
  autores_endpoint,
  public_url,
  metadata_patch
);

WITH target AS (
  SELECT c.id AS candidato_id
  FROM candidatos c
  WHERE c.slug = 'teresa-surita'
)
UPDATE projetos_lei pl
SET
  coverage_id = 'teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506',
  coverage_scope = 'inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506',
  metadata = COALESCE(pl.metadata, '{}'::jsonb) || seed.metadata_patch
FROM target
JOIN _coverage_teresa_surita_camara_lote_a seed ON TRUE
WHERE pl.candidato_id = target.candidato_id
  AND pl.fonte = 'Camara'
  AND pl.proposicao_id_api = seed.proposicao_id_api
  AND (pl.coverage_id IS NULL OR pl.coverage_id = 'teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506');

DO $$
DECLARE
  cand_id uuid;
  with_target_coverage int;
  remaining_null int;
  lme_count int;
  other_slugs_with_target int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'teresa-surita';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'teresa-surita: pos-condicao pulada porque candidato nao existe neste banco local/CI minimo';
    RETURN;
  END IF;

  SELECT count(*) INTO with_target_coverage
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id = 'teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506'
    AND coverage_scope = 'inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506';
  IF with_target_coverage <> 77 THEN
    RAISE EXCEPTION 'Pos-apply teresa-surita: esperadas 77 rows com coverage_id alvo, encontradas %', with_target_coverage;
  END IF;

  SELECT count(*) INTO remaining_null
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id IS NULL;
  IF remaining_null <> 11 THEN
    RAISE EXCEPTION 'Pos-apply teresa-surita: esperadas 11 rows sem coverage por limite documentado, encontradas %', remaining_null;
  END IF;

  SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pos-apply teresa-surita: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;

  SELECT count(*) INTO other_slugs_with_target
  FROM projetos_lei
  WHERE candidato_id <> cand_id
    AND coverage_id = 'teresa-surita-camara-autoria-principal-ampliado-parcial-lote-a-20260506';
  IF other_slugs_with_target <> 0 THEN
    RAISE EXCEPTION 'Pos-apply teresa-surita: % rows de outros slugs com coverage_id alvo', other_slugs_with_target;
  END IF;

  RAISE NOTICE 'Pos-apply teresa-surita Camara Lote A: coverage=% sem_coverage=% lme=%', with_target_coverage, remaining_null, lme_count;
END $$;
