-- ============================================
-- Legislacao full-site: paulo-martins-gov-pr / Camara Dados Abertos / projetos_lei
-- Coverage ampliado parcial: Lote A autoria principal Camara
-- ============================================
-- Fonte oficial: Camara dos Deputados - Dados Abertos
--   https://dadosabertos.camara.leg.br/api/v2/deputados/193726
--   https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id}
--   https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id}/autores
--
-- Artefato de auditoria:
--   fonte interna de curadoria
--
-- Coverage:
--   coverage_id    = paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506
--   coverage_scope = inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506
--
-- Filtro factual: das 100 rows Camara legacy existentes, somente 75
-- foram marcadas com coverage_id porque a API oficial confirmou
-- idDeputado=193726, tipo Deputado(a), ordemAssinatura=1.
-- 25 rows permanecem sem coverage por coautoria/sem autoria verificavel.
--
-- Esta migration NAO escreve em legislacao_mandato_executivo.
-- Esta migration NAO insere, deleta ou trunca rows.
-- ============================================

DO $$
DECLARE
  cand_id uuid;
  total_pl int;
  target_present int;
  target_with_other_coverage int;
  lme_count int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'paulo-martins-gov-pr';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'paulo-martins-gov-pr: candidato ausente neste banco local/CI minimo; coverage Camara pulado';
    RETURN;
  END IF;

  SELECT count(*) INTO total_pl FROM projetos_lei WHERE candidato_id = cand_id;
  IF total_pl <> 100 THEN
    RAISE EXCEPTION 'Pre-condicao paulo-martins-gov-pr: esperadas 100 rows legacy em projetos_lei, encontradas %', total_pl;
  END IF;

  SELECT count(*) INTO target_present
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND fonte = 'Camara'
    AND proposicao_id_api IN ('2344534', '2330107', '2327145', '2319757', '2319350', '2317941', '2316870', '2316311', '2310637', '2306268', '2305845', '2305609', '2305535', '2303401', '2301809', '2329645', '2326663', '2322412', '2319756', '2319312', '2316622', '2310542', '2308198', '2307450', '2306258', '2305818', '2305608', '2305532', '2303348', '2301787', '2326317', '2319755', '2318835', '2317505', '2316621', '2310161', '2308197', '2307144', '2306250', '2305657', '2305565', '2302465', '2301211', '2327147', '2318400', '2317482', '2316620', '2309780', '2306270', '2305847', '2305650', '2305540', '2304334', '2302464', '2327146', '2319351', '2318399', '2317481', '2316618', '2310638', '2309580', '2307454', '2306269', '2305846', '2305613', '2305538', '2304217', '2302242', '2319610', '2317940', '2332369', '2332179', '2325268', '2307453', '2320125');
  IF target_present <> 75 THEN
    RAISE EXCEPTION 'Pre-condicao paulo-martins-gov-pr: esperadas 75 rows alvo Camara presentes, encontradas %', target_present;
  END IF;

  SELECT count(*) INTO target_with_other_coverage
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND proposicao_id_api IN ('2344534', '2330107', '2327145', '2319757', '2319350', '2317941', '2316870', '2316311', '2310637', '2306268', '2305845', '2305609', '2305535', '2303401', '2301809', '2329645', '2326663', '2322412', '2319756', '2319312', '2316622', '2310542', '2308198', '2307450', '2306258', '2305818', '2305608', '2305532', '2303348', '2301787', '2326317', '2319755', '2318835', '2317505', '2316621', '2310161', '2308197', '2307144', '2306250', '2305657', '2305565', '2302465', '2301211', '2327147', '2318400', '2317482', '2316620', '2309780', '2306270', '2305847', '2305650', '2305540', '2304334', '2302464', '2327146', '2319351', '2318399', '2317481', '2316618', '2310638', '2309580', '2307454', '2306269', '2305846', '2305613', '2305538', '2304217', '2302242', '2319610', '2317940', '2332369', '2332179', '2325268', '2307453', '2320125')
    AND coverage_id IS NOT NULL
    AND coverage_id <> 'paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506';
  IF target_with_other_coverage <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao paulo-martins-gov-pr: % rows alvo ja tem coverage_id divergente', target_with_other_coverage;
  END IF;

  SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao paulo-martins-gov-pr: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;
END $$;

CREATE TEMP TABLE _coverage_paulo_martins_gov_pr_camara_lote_a ON COMMIT DROP AS
SELECT *
FROM (
  VALUES
    ('2344534', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2344534', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2344534/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2344534', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2344534","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2344534","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2344534/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2344534","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2330107', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2330107', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2330107/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2330107', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2330107","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2330107","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2330107/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2330107","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2327145', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327145', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327145/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327145', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2327145","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327145","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327145/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327145","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2319757', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319757', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319757/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319757', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2319757","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319757","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319757/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319757","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2319350', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319350', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319350/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319350', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2319350","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319350","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319350/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319350","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2317941', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317941', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317941/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317941', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2317941","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317941","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317941/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317941","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2316870', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316870', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316870/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316870', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2316870","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316870","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316870/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316870","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2316311', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316311', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316311/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316311', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2316311","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316311","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316311/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316311","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2310637', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310637', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310637/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310637', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2310637","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310637","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310637/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310637","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2306268', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306268', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306268/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306268', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2306268","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306268","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306268/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306268","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2305845', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305845', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305845/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305845', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2305845","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305845","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305845/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305845","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2305609', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305609', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305609/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305609', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2305609","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305609","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305609/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305609","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2305535', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305535', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305535/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305535', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2305535","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305535","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305535/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305535","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2303401', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2303401', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2303401/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2303401', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2303401","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2303401","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2303401/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2303401","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2301809', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301809', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301809/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301809', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2301809","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301809","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301809/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301809","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2329645', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329645', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329645/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329645', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2329645","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329645","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329645/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2329645","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2326663', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2326663', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2326663/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2326663', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2326663","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2326663","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2326663/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2326663","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2322412', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2322412', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2322412/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2322412', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2322412","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2322412","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2322412/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2322412","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2319756', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319756', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319756/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319756', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2319756","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319756","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319756/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319756","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2319312', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319312', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319312/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319312', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2319312","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319312","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319312/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319312","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2316622', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316622', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316622/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316622', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2316622","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316622","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316622/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316622","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2310542', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310542', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310542/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310542', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2310542","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310542","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310542/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310542","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2308198', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308198', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308198/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308198', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2308198","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308198","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308198/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308198","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2307450', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307450', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307450/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307450', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2307450","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307450","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307450/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307450","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2306258', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306258', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306258/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306258', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2306258","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306258","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306258/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306258","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2305818', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305818', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305818/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305818', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2305818","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305818","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305818/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305818","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2305608', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305608', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305608/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305608', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2305608","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305608","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305608/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305608","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2305532', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305532', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305532/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305532', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2305532","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305532","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305532/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305532","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2303348', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2303348', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2303348/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2303348', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2303348","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2303348","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2303348/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2303348","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2301787', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301787', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301787/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301787', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2301787","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301787","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301787/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301787","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2326317', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2326317', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2326317/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2326317', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2326317","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2326317","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2326317/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2326317","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2319755', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319755', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319755/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319755', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2319755","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319755","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319755/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319755","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2318835', 1, 2, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318835', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318835/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318835', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2318835","ordem_assinatura":1,"total_autores":2,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318835","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318835/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318835","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2317505', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317505', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317505/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317505', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2317505","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317505","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317505/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317505","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2316621', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316621', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316621/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316621', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2316621","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316621","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316621/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316621","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2310161', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310161', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310161/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310161', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2310161","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310161","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310161/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310161","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2308197', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308197', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308197/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308197', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2308197","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308197","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308197/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308197","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2307144', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307144', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307144/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307144', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2307144","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307144","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307144/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307144","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2306250', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306250', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306250/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306250', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2306250","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306250","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306250/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306250","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2305657', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305657', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305657/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305657', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2305657","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305657","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305657/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305657","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2305565', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305565', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305565/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305565', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2305565","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305565","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305565/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305565","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2302465', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302465', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302465/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302465', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2302465","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302465","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302465/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302465","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2301211', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301211', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301211/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301211', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2301211","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301211","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301211/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301211","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2327147', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327147', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327147/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327147', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2327147","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327147","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327147/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327147","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2318400', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318400', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318400/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318400', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2318400","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318400","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318400/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318400","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2317482', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317482', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317482/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317482', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2317482","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317482","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317482/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317482","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2316620', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316620', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316620/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316620', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2316620","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316620","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316620/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316620","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2309780', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2309780', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2309780/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2309780', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2309780","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2309780","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2309780/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2309780","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2306270', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306270', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306270/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306270', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2306270","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306270","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306270/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306270","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2305847', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305847', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305847/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305847', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2305847","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305847","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305847/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305847","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2305650', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305650', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305650/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305650', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2305650","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305650","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305650/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305650","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2305540', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305540', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305540/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305540', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2305540","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305540","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305540/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305540","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2304334', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304334', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304334/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304334', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2304334","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304334","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304334/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304334","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2302464', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302464', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302464/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302464', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2302464","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302464","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302464/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302464","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2327146', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327146', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327146/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327146', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2327146","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327146","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327146/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2327146","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2319351', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319351', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319351/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319351', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2319351","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319351","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319351/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319351","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2318399', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318399', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318399/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318399', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2318399","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318399","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318399/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2318399","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2317481', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317481', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317481/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317481', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2317481","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317481","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317481/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317481","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2316618', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316618', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316618/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316618', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2316618","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316618","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316618/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2316618","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2310638', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310638', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310638/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310638', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2310638","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310638","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310638/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2310638","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2309580', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2309580', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2309580/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2309580', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2309580","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2309580","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2309580/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2309580","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2307454', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307454', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307454/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307454', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2307454","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307454","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307454/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307454","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2306269', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306269', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306269/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306269', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2306269","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306269","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306269/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2306269","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2305846', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305846', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305846/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305846', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2305846","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305846","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305846/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305846","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2305613', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305613', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305613/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305613', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2305613","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305613","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305613/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305613","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2305538', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305538', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305538/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305538', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2305538","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305538","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305538/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2305538","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2304217', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304217', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304217/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304217', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2304217","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304217","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304217/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2304217","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2302242', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302242', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302242/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302242', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2302242","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302242","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302242/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302242","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2319610', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319610', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319610/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319610', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2319610","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319610","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319610/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2319610","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2317940', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317940', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317940/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317940', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2317940","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317940","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317940/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2317940","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2332369', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332369', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332369/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332369', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2332369","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332369","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332369/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332369","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2332179', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332179', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332179/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332179', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2332179","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332179","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332179/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2332179","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2325268', 1, 12, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325268', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325268/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325268', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2325268","ordem_assinatura":1,"total_autores":12,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325268","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325268/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325268","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2307453', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307453', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307453/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307453', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2307453","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307453","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307453/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2307453","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb),
    ('2320125', 1, 1, 'Paulo Eduardo Martins', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2320125', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2320125/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2320125', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"paulo-martins-gov-pr-camara-lote-a-20260506","coverage_id":"paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":193726,"proposicao_id_api":"2320125","ordem_assinatura":1,"total_autores":1,"autor_nome":"Paulo Eduardo Martins","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2320125","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2320125/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2320125","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:16:37.309Z"}'::jsonb)
) AS v(
  proposicao_id_api,
  ordem_assinatura,
  total_autores,
  autor_nome,
  autor_tipo,
  detalhe_endpoint,
  autores_endpoint,
  public_url,
  metadata_patch
);

WITH target AS (
  SELECT c.id AS candidato_id
  FROM candidatos c
  WHERE c.slug = 'paulo-martins-gov-pr'
)
UPDATE projetos_lei pl
SET
  coverage_id = 'paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506',
  coverage_scope = 'inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506',
  metadata = COALESCE(pl.metadata, '{}'::jsonb) || seed.metadata_patch
FROM target
JOIN _coverage_paulo_martins_gov_pr_camara_lote_a seed ON TRUE
WHERE pl.candidato_id = target.candidato_id
  AND pl.fonte = 'Camara'
  AND pl.proposicao_id_api = seed.proposicao_id_api
  AND (pl.coverage_id IS NULL OR pl.coverage_id = 'paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506');

DO $$
DECLARE
  cand_id uuid;
  with_target_coverage int;
  remaining_null int;
  lme_count int;
  other_slugs_with_target int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'paulo-martins-gov-pr';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'paulo-martins-gov-pr: pos-condicao pulada porque candidato nao existe neste banco local/CI minimo';
    RETURN;
  END IF;

  SELECT count(*) INTO with_target_coverage
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id = 'paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506'
    AND coverage_scope = 'inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506';
  IF with_target_coverage <> 75 THEN
    RAISE EXCEPTION 'Pos-apply paulo-martins-gov-pr: esperadas 75 rows com coverage_id alvo, encontradas %', with_target_coverage;
  END IF;

  SELECT count(*) INTO remaining_null
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id IS NULL;
  IF remaining_null <> 25 THEN
    RAISE EXCEPTION 'Pos-apply paulo-martins-gov-pr: esperadas 25 rows sem coverage por limite documentado, encontradas %', remaining_null;
  END IF;

  SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pos-apply paulo-martins-gov-pr: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;

  SELECT count(*) INTO other_slugs_with_target
  FROM projetos_lei
  WHERE candidato_id <> cand_id
    AND coverage_id = 'paulo-martins-gov-pr-camara-autoria-principal-ampliado-parcial-lote-a-20260506';
  IF other_slugs_with_target <> 0 THEN
    RAISE EXCEPTION 'Pos-apply paulo-martins-gov-pr: % rows de outros slugs com coverage_id alvo', other_slugs_with_target;
  END IF;

  RAISE NOTICE 'Pos-apply paulo-martins-gov-pr Camara Lote A: coverage=% sem_coverage=% lme=%', with_target_coverage, remaining_null, lme_count;
END $$;
