-- ============================================
-- Legislacao full-site: ampliado_parcial -> completo_provado escopado
-- Generated by scripts/generate-legislacao-ampliados-completos-final-20260512.ts
-- Artifact: fonte interna de curadoria
-- ============================================
-- Esta migration e UPDATE-only sobre public.projetos_lei.
-- Esta migration NAO escreve em legislacao_mandato_executivo.
-- Esta migration NAO altera historico_politico.
-- Este recorte nao e inventario global da vida politica.
-- ============================================

CREATE TEMP TABLE _ampliados_completos_final_20260512 (
  slug text NOT NULL,
  expected_count int NOT NULL,
  previous_coverage_id text NOT NULL,
  coverage_id text NOT NULL,
  coverage_scope text NOT NULL,
  metadata_patch jsonb NOT NULL
) ON COMMIT DROP;

INSERT INTO _ampliados_completos_final_20260512 (
  slug,
  expected_count,
  previous_coverage_id,
  coverage_id,
  coverage_scope,
  metadata_patch
)
VALUES
  ('adailton-furia', 14, 'legislacao-unblock-26-projetos-lei-lote-a-20260508', 'adailton-furia-sapl-alro-completo-autoria-principal-plo-2019-2020-cutoff-20260512', 'inventario_completo_sapl_alro_autoria_principal_plo_2019_2020_cutoff_20260512', '{"data_real":true,"fluxo":"Legislacao full-site","slug":"adailton-furia","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"legislacao-ampliados-completos-final-20260512","migration_version":"20260512213000","coverage_id":"adailton-furia-sapl-alro-completo-autoria-principal-plo-2019-2020-cutoff-20260512","coverage_scope":"inventario_completo_sapl_alro_autoria_principal_plo_2019_2020_cutoff_20260512","previous_coverage_id":"legislacao-unblock-26-projetos-lei-lote-a-20260508","previous_coverage_scope":"inventario_ampliado_parcial_fontes_oficiais_estaduais_municipais_lote_a_20260508","coverage_status":"completo_escopado","coverage_public_status":"parlamentar_complete","coverage_policy":"sapl_alro_autoria_literal_primeiro_nome_plo_v1","coverage_cutoff":"2026-05-12","source_artifact":"fonte interna de curadoria","recorte_publico":"autoria parlamentar principal de Adailton Fúria na Assembleia Legislativa de Rondônia/SAPL ALRO em Projeto de Lei Ordinária (PLO), no recorte 2019-2020","exclusoes_publicas":["inventário global da vida política","mandatos de Vereador e Prefeito","atos do Executivo municipal","proposições fora de PLO/tipo=1 no SAPL ALRO","proposições em que Adailton Fúria não aparece como primeiro nome da autoria literal","superfícies fora do SAPL ALRO"],"fonte_oficial":"SAPL ALRO","official_source_url":"https://sapl.al.ro.leg.br/materia/pesquisar-materia?format=json&tipo=1&ano=&numero=&ementa=&autoria__autor=&autoria__autor__tipo=&data_apresentacao_0=&data_apresentacao_1=&salvar=Pesquisar","official_source_title":"SAPL ALRO - enumeração oficial do recorte"}'::jsonb),
  ('dr-furlan', 73, 'legislacao-p0a2-lote-d-projetos-lei-residuais-20260508', 'dr-furlan-alap-elegis-completo-autoria-principal-pl-2014-2020-cutoff-20260512', 'inventario_completo_alap_elegis_autoria_principal_pl_2014_2020_cutoff_20260512', '{"data_real":true,"fluxo":"Legislacao full-site","slug":"dr-furlan","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"legislacao-ampliados-completos-final-20260512","migration_version":"20260512213000","coverage_id":"dr-furlan-alap-elegis-completo-autoria-principal-pl-2014-2020-cutoff-20260512","coverage_scope":"inventario_completo_alap_elegis_autoria_principal_pl_2014_2020_cutoff_20260512","previous_coverage_id":"legislacao-p0a2-lote-d-projetos-lei-residuais-20260508","previous_coverage_scope":"inventario_ampliado_parcial_alap_dr_furlan_p0a2_lote_d_20260508","coverage_status":"completo_escopado","coverage_public_status":"parlamentar_complete","coverage_policy":"alap_elegis_origem_dr_furlan_tipo_1_autoria_singular_v1","coverage_cutoff":"2026-05-12","source_artifact":"fonte interna de curadoria","recorte_publico":"autoria parlamentar principal de Dr. Furlan na Assembleia Legislativa do Amapá/eLegis em Projeto de Lei Ordinária (PL), no recorte 2014-2020","exclusoes_publicas":["inventário global da vida política","Prefeitura de Macapá","atos do Executivo municipal","PEC, Projeto de Decreto Legislativo, Projeto de Resolução e demais tipos fora de tipo_proposicao=1","proposições anteriores ao mandato parlamentar compatível","proposições em que Dr. Furlan não aparece como autoria principal singular","superfícies fora do eLegis ALAP"],"fonte_oficial":"eLegis ALAP","official_source_url":"https://elegis.al.ap.leg.br/portal/proposicoes?tipo_proposicao=1&origem=Dr.%20Furlan&origem_select=Dr.%20Furlan","official_source_title":"eLegis ALAP - enumeração oficial do recorte"}'::jsonb);

DO $$
DECLARE
  rec record;
  cand_id uuid;
  current_pl_count int;
  current_lme_count int;
  old_coverage_count int;
  new_coverage_count int;
BEGIN
  FOR rec IN SELECT * FROM _ampliados_completos_final_20260512 LOOP
    SELECT id INTO cand_id FROM candidatos WHERE slug = rec.slug AND publicavel = true;

    IF cand_id IS NULL THEN
      RAISE NOTICE '%: pre-condicao pulada porque candidato publico nao existe neste banco local/CI minimo', rec.slug;
      CONTINUE;
    END IF;

    SELECT count(*) INTO current_pl_count FROM projetos_lei WHERE candidato_id = cand_id;
    SELECT count(*) INTO current_lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
    SELECT count(*) INTO old_coverage_count
    FROM projetos_lei
    WHERE candidato_id = cand_id
      AND coverage_id = rec.previous_coverage_id;
    SELECT count(*) INTO new_coverage_count
    FROM projetos_lei
    WHERE candidato_id = cand_id
      AND coverage_id = rec.coverage_id;

    IF current_pl_count NOT IN (rec.expected_count) THEN
      RAISE EXCEPTION 'Pre-condicao %: projetos_lei esperado %, encontrado %', rec.slug, rec.expected_count, current_pl_count;
    END IF;

    IF NOT (old_coverage_count = rec.expected_count OR new_coverage_count = rec.expected_count) THEN
      RAISE EXCEPTION 'Pre-condicao %: esperado coverage antigo ou novo com %, antigo %, novo %', rec.slug, rec.expected_count, old_coverage_count, new_coverage_count;
    END IF;

    IF current_lme_count <> 0 THEN
      RAISE EXCEPTION 'Pre-condicao %: legislacao_mandato_executivo esperado 0 para promocao parlamentar pura, encontrado %', rec.slug, current_lme_count;
    END IF;
  END LOOP;
END $$;

WITH target AS (
  SELECT
    c.id AS candidato_id,
    seed.*
  FROM _ampliados_completos_final_20260512 seed
  JOIN candidatos c ON c.slug = seed.slug
  WHERE c.publicavel = true
)
UPDATE projetos_lei p
SET
  coverage_id = target.coverage_id,
  coverage_scope = target.coverage_scope,
  metadata = coalesce(p.metadata, '{}'::jsonb)
    || target.metadata_patch
    || jsonb_build_object(
      'proposicao_id_api', p.proposicao_id_api,
      'source_verified_at', now()
    )
FROM target
WHERE p.candidato_id = target.candidato_id
  AND p.coverage_id IN (target.previous_coverage_id, target.coverage_id);

DO $$
DECLARE
  rec record;
  cand_id uuid;
  target_count int;
  metadata_ok_count int;
  lme_count int;
BEGIN
  FOR rec IN SELECT * FROM _ampliados_completos_final_20260512 LOOP
    SELECT id INTO cand_id FROM candidatos WHERE slug = rec.slug AND publicavel = true;

    IF cand_id IS NULL THEN
      RAISE NOTICE '%: pos-apply pulado porque candidato publico nao existe neste banco local/CI minimo', rec.slug;
      CONTINUE;
    END IF;

    SELECT count(*) INTO target_count
    FROM projetos_lei
    WHERE candidato_id = cand_id
      AND coverage_id = rec.coverage_id;

    SELECT count(*) INTO metadata_ok_count
    FROM projetos_lei
    WHERE candidato_id = cand_id
      AND coverage_id = rec.coverage_id
      AND coverage_scope = rec.coverage_scope
      AND metadata->>'coverage_id' = rec.coverage_id
      AND metadata->>'coverage_status' = 'completo_escopado'
      AND metadata->>'coverage_public_status' = 'parlamentar_complete'
      AND metadata->>'tabela_alvo' = 'projetos_lei'
      AND coalesce(metadata->>'legislacao_mandato_executivo_mixed', 'false') = 'false';

    SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;

    IF target_count <> rec.expected_count THEN
      RAISE EXCEPTION 'Pos-apply %: esperadas % rows alvo em projetos_lei, encontradas %', rec.slug, rec.expected_count, target_count;
    END IF;

    IF metadata_ok_count <> rec.expected_count THEN
      RAISE EXCEPTION 'Pos-apply %: metadata/copy esperado %, encontrado %', rec.slug, rec.expected_count, metadata_ok_count;
    END IF;

    IF lme_count <> 0 THEN
      RAISE EXCEPTION 'Pos-apply %: LME esperado 0, encontrado %', rec.slug, lme_count;
    END IF;
  END LOOP;
END $$;

DO $$
BEGIN
  RAISE NOTICE 'Promocao ampliados completos final 20260512 aplicada em projetos_lei: % rows', (
    SELECT count(*)
    FROM projetos_lei p
    JOIN candidatos c ON c.id = p.candidato_id
    JOIN _ampliados_completos_final_20260512 seed ON seed.slug = c.slug
    WHERE p.coverage_id = seed.coverage_id
  );
END $$;
