-- ============================================
-- Legislacao full-site: renan-filho / Camara Dados Abertos / projetos_lei
-- Coverage ampliado parcial: Lote A autoria principal Camara
-- ============================================
-- Fonte oficial: Camara dos Deputados - Dados Abertos
--   https://dadosabertos.camara.leg.br/api/v2/deputados/160623
--   https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id}
--   https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id}/autores
--
-- Artefato de auditoria:
--   fonte interna de curadoria
--
-- Coverage:
--   coverage_id    = renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506
--   coverage_scope = inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506
--
-- Filtro factual: das 100 rows Camara legacy existentes, somente 68
-- foram marcadas com coverage_id porque a API oficial confirmou
-- idDeputado=160623, tipo Deputado(a), ordemAssinatura=1.
-- 32 rows permanecem sem coverage por coautoria/sem autoria verificavel.
--
-- Esta migration NAO escreve em legislacao_mandato_executivo.
-- Esta migration NAO insere, deleta ou trunca rows.
-- ============================================

DO $$
DECLARE
  cand_id uuid;
  total_pl int;
  target_present int;
  target_with_other_coverage int;
  lme_count int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'renan-filho';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'renan-filho: candidato ausente neste banco local/CI minimo; coverage Camara pulado';
    RETURN;
  END IF;

  SELECT count(*) INTO total_pl FROM projetos_lei WHERE candidato_id = cand_id;
  IF total_pl <> 100 THEN
    RAISE EXCEPTION 'Pre-condicao renan-filho: esperadas 100 rows legacy em projetos_lei, encontradas %', total_pl;
  END IF;

  SELECT count(*) INTO target_present
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND fonte = 'Camara'
    AND proposicao_id_api IN ('523141', '521288', '514289', '514334', '504540', '504539', '610702', '600168', '580438', '858737', '612576', '610173', '562366', '559300', '557078', '553225', '549869', '610703', '600169', '564035', '559853', '557479', '555698', '549854', '619499', '611386', '600639', '571411', '560046', '558568', '555714', '551929', '549856', '520766', '517929', '509326', '504538', '611987', '610172', '561784', '559299', '555743', '553224', '549868', '545666', '527615', '562368', '557477', '555193', '549870', '514352', '504541', '504536', '499490', '496204', '520518', '514532', '508793', '504537', '502272', '496206', '504535', '498024', '504534', '497877', '504533', '497871', '559511');
  IF target_present <> 68 THEN
    RAISE EXCEPTION 'Pre-condicao renan-filho: esperadas 68 rows alvo Camara presentes, encontradas %', target_present;
  END IF;

  SELECT count(*) INTO target_with_other_coverage
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND proposicao_id_api IN ('523141', '521288', '514289', '514334', '504540', '504539', '610702', '600168', '580438', '858737', '612576', '610173', '562366', '559300', '557078', '553225', '549869', '610703', '600169', '564035', '559853', '557479', '555698', '549854', '619499', '611386', '600639', '571411', '560046', '558568', '555714', '551929', '549856', '520766', '517929', '509326', '504538', '611987', '610172', '561784', '559299', '555743', '553224', '549868', '545666', '527615', '562368', '557477', '555193', '549870', '514352', '504541', '504536', '499490', '496204', '520518', '514532', '508793', '504537', '502272', '496206', '504535', '498024', '504534', '497877', '504533', '497871', '559511')
    AND coverage_id IS NOT NULL
    AND coverage_id <> 'renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506';
  IF target_with_other_coverage <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao renan-filho: % rows alvo ja tem coverage_id divergente', target_with_other_coverage;
  END IF;

  SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao renan-filho: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;
END $$;

CREATE TEMP TABLE _coverage_renan_filho_camara_lote_a ON COMMIT DROP AS
SELECT *
FROM (
  VALUES
    ('523141', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/523141', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/523141/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/523141', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"523141","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/523141","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/523141/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/523141","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('521288', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/521288', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/521288/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/521288', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"521288","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/521288","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/521288/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/521288","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('514289', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/514289', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/514289/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/514289', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"514289","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/514289","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/514289/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/514289","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('514334', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/514334', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/514334/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/514334', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"514334","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/514334","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/514334/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/514334","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('504540', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504540', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504540/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504540', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"504540","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504540","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504540/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504540","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('504539', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504539', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504539/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504539', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"504539","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504539","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504539/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504539","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('610702', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/610702', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/610702/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/610702', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"610702","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/610702","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/610702/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/610702","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('600168', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/600168', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/600168/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/600168', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"600168","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/600168","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/600168/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/600168","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('580438', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/580438', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/580438/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/580438', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"580438","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/580438","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/580438/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/580438","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('858737', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/858737', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/858737/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/858737', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"858737","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/858737","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/858737/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/858737","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('612576', 1, 2, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/612576', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/612576/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/612576', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"612576","ordem_assinatura":1,"total_autores":2,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/612576","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/612576/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/612576","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('610173', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/610173', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/610173/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/610173', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"610173","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/610173","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/610173/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/610173","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('562366', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/562366', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/562366/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/562366', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"562366","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/562366","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/562366/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/562366","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('559300', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/559300', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/559300/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/559300', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"559300","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/559300","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/559300/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/559300","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('557078', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/557078', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/557078/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/557078', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"557078","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/557078","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/557078/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/557078","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('553225', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/553225', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/553225/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/553225', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"553225","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/553225","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/553225/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/553225","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('549869', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549869', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549869/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549869', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"549869","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549869","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549869/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549869","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('610703', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/610703', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/610703/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/610703', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"610703","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/610703","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/610703/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/610703","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('600169', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/600169', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/600169/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/600169', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"600169","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/600169","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/600169/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/600169","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('564035', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/564035', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/564035/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/564035', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"564035","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/564035","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/564035/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/564035","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('559853', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/559853', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/559853/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/559853', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"559853","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/559853","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/559853/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/559853","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('557479', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/557479', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/557479/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/557479', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"557479","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/557479","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/557479/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/557479","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('555698', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/555698', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/555698/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/555698', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"555698","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/555698","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/555698/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/555698","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('549854', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549854', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549854/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549854', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"549854","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549854","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549854/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549854","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('619499', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/619499', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/619499/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/619499', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"619499","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/619499","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/619499/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/619499","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('611386', 1, 2, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/611386', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/611386/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/611386', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"611386","ordem_assinatura":1,"total_autores":2,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/611386","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/611386/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/611386","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('600639', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/600639', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/600639/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/600639', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"600639","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/600639","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/600639/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/600639","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('571411', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/571411', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/571411/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/571411', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"571411","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/571411","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/571411/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/571411","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('560046', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/560046', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/560046/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/560046', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"560046","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/560046","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/560046/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/560046","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('558568', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/558568', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/558568/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/558568', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"558568","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/558568","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/558568/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/558568","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('555714', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/555714', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/555714/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/555714', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"555714","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/555714","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/555714/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/555714","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('551929', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/551929', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/551929/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/551929', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"551929","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/551929","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/551929/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/551929","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('549856', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549856', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549856/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549856', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"549856","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549856","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549856/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549856","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('520766', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/520766', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/520766/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/520766', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"520766","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/520766","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/520766/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/520766","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('517929', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/517929', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/517929/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/517929', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"517929","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/517929","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/517929/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/517929","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('509326', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/509326', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/509326/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/509326', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"509326","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/509326","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/509326/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/509326","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('504538', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504538', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504538/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504538', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"504538","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504538","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504538/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504538","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('611987', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/611987', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/611987/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/611987', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"611987","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/611987","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/611987/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/611987","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('610172', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/610172', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/610172/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/610172', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"610172","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/610172","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/610172/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/610172","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('561784', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/561784', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/561784/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/561784', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"561784","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/561784","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/561784/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/561784","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('559299', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/559299', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/559299/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/559299', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"559299","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/559299","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/559299/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/559299","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('555743', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/555743', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/555743/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/555743', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"555743","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/555743","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/555743/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/555743","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('553224', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/553224', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/553224/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/553224', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"553224","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/553224","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/553224/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/553224","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('549868', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549868', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549868/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549868', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"549868","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549868","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549868/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549868","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('545666', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/545666', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/545666/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/545666', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"545666","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/545666","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/545666/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/545666","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('527615', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/527615', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/527615/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/527615', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"527615","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/527615","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/527615/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/527615","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('562368', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/562368', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/562368/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/562368', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"562368","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/562368","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/562368/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/562368","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('557477', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/557477', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/557477/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/557477', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"557477","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/557477","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/557477/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/557477","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('555193', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/555193', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/555193/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/555193', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"555193","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/555193","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/555193/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/555193","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('549870', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549870', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549870/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/549870', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"549870","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549870","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549870/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/549870","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('514352', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/514352', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/514352/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/514352', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"514352","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/514352","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/514352/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/514352","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('504541', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504541', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504541/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504541', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"504541","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504541","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504541/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504541","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('504536', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504536', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504536/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504536', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"504536","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504536","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504536/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504536","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('499490', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/499490', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/499490/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/499490', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"499490","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/499490","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/499490/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/499490","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('496204', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/496204', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/496204/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/496204', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"496204","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/496204","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/496204/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/496204","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('520518', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/520518', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/520518/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/520518', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"520518","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/520518","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/520518/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/520518","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('514532', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/514532', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/514532/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/514532', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"514532","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/514532","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/514532/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/514532","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('508793', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/508793', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/508793/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/508793', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"508793","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/508793","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/508793/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/508793","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('504537', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504537', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504537/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504537', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"504537","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504537","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504537/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504537","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('502272', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/502272', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/502272/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/502272', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"502272","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/502272","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/502272/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/502272","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('496206', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/496206', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/496206/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/496206', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"496206","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/496206","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/496206/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/496206","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('504535', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504535', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504535/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504535', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"504535","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504535","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504535/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504535","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('498024', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/498024', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/498024/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/498024', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"498024","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/498024","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/498024/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/498024","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('504534', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504534', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504534/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504534', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"504534","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504534","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504534/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504534","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('497877', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/497877', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/497877/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/497877', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"497877","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/497877","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/497877/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/497877","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('504533', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504533', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504533/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/504533', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"504533","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504533","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504533/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/504533","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('497871', 1, 5, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/497871', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/497871/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/497871', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"497871","ordem_assinatura":1,"total_autores":5,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/497871","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/497871/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/497871","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb),
    ('559511', 1, 1, 'Renan Filho', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/559511', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/559511/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/559511', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"renan-filho-camara-lote-a-20260506","coverage_id":"renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":160623,"proposicao_id_api":"559511","ordem_assinatura":1,"total_autores":1,"autor_nome":"Renan Filho","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/559511","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/559511/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/559511","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T08:56:57.839Z"}'::jsonb)
) AS v(
  proposicao_id_api,
  ordem_assinatura,
  total_autores,
  autor_nome,
  autor_tipo,
  detalhe_endpoint,
  autores_endpoint,
  public_url,
  metadata_patch
);

WITH target AS (
  SELECT c.id AS candidato_id
  FROM candidatos c
  WHERE c.slug = 'renan-filho'
)
UPDATE projetos_lei pl
SET
  coverage_id = 'renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506',
  coverage_scope = 'inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506',
  metadata = COALESCE(pl.metadata, '{}'::jsonb) || seed.metadata_patch
FROM target
JOIN _coverage_renan_filho_camara_lote_a seed ON TRUE
WHERE pl.candidato_id = target.candidato_id
  AND pl.fonte = 'Camara'
  AND pl.proposicao_id_api = seed.proposicao_id_api
  AND (pl.coverage_id IS NULL OR pl.coverage_id = 'renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506');

DO $$
DECLARE
  cand_id uuid;
  with_target_coverage int;
  remaining_null int;
  lme_count int;
  other_slugs_with_target int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'renan-filho';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'renan-filho: pos-condicao pulada porque candidato nao existe neste banco local/CI minimo';
    RETURN;
  END IF;

  SELECT count(*) INTO with_target_coverage
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id = 'renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506'
    AND coverage_scope = 'inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506';
  IF with_target_coverage <> 68 THEN
    RAISE EXCEPTION 'Pos-apply renan-filho: esperadas 68 rows com coverage_id alvo, encontradas %', with_target_coverage;
  END IF;

  SELECT count(*) INTO remaining_null
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id IS NULL;
  IF remaining_null <> 32 THEN
    RAISE EXCEPTION 'Pos-apply renan-filho: esperadas 32 rows sem coverage por limite documentado, encontradas %', remaining_null;
  END IF;

  SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pos-apply renan-filho: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;

  SELECT count(*) INTO other_slugs_with_target
  FROM projetos_lei
  WHERE candidato_id <> cand_id
    AND coverage_id = 'renan-filho-camara-autoria-principal-ampliado-parcial-lote-a-20260506';
  IF other_slugs_with_target <> 0 THEN
    RAISE EXCEPTION 'Pos-apply renan-filho: % rows de outros slugs com coverage_id alvo', other_slugs_with_target;
  END IF;

  RAISE NOTICE 'Pos-apply renan-filho Camara Lote A: coverage=% sem_coverage=% lme=%', with_target_coverage, remaining_null, lme_count;
END $$;
