-- ============================================
-- Legislacao full-site: thiago-de-joaldo / Camara Dados Abertos / projetos_lei
-- Coverage ampliado parcial: Lote A autoria principal Camara
-- ============================================
-- Fonte oficial: Camara dos Deputados - Dados Abertos
--   https://dadosabertos.camara.leg.br/api/v2/deputados/220560
--   https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id}
--   https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id}/autores
--
-- Artefato de auditoria:
--   fonte interna de curadoria
--
-- Coverage:
--   coverage_id    = thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506
--   coverage_scope = inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506
--
-- Filtro factual: das 100 rows Camara legacy existentes, somente 63
-- foram marcadas com coverage_id porque a API oficial confirmou
-- idDeputado=220560, tipo Deputado(a), ordemAssinatura=1.
-- 37 rows permanecem sem coverage por coautoria/sem autoria verificavel.
--
-- Esta migration NAO escreve em legislacao_mandato_executivo.
-- Esta migration NAO insere, deleta ou trunca rows.
-- ============================================

DO $$
DECLARE
  cand_id uuid;
  total_pl int;
  target_present int;
  target_with_other_coverage int;
  lme_count int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'thiago-de-joaldo';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'thiago-de-joaldo: candidato ausente neste banco local/CI minimo; coverage Camara pulado';
    RETURN;
  END IF;

  SELECT count(*) INTO total_pl FROM projetos_lei WHERE candidato_id = cand_id;
  IF total_pl <> 100 THEN
    RAISE EXCEPTION 'Pre-condicao thiago-de-joaldo: esperadas 100 rows legacy em projetos_lei, encontradas %', total_pl;
  END IF;

  SELECT count(*) INTO target_present
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND fonte = 'Camara'
    AND proposicao_id_api IN ('2611359', '2611024', '2609830', '2609638', '2591498', '2586705', '2569253', '2600831', '2582236', '2581991', '2571048', '2563536', '2562277', '2558239', '2554483', '2550182', '2548423', '2592837', '2586678', '2584173', '2582233', '2571680', '2569275', '2565925', '2564314', '2563264', '2561275', '2554565', '2554480', '2548887', '2586672', '2576587', '2571083', '2565918', '2563202', '2558240', '2554486', '2552721', '2548427', '2582235', '2579604', '2570896', '2564464', '2561924', '2558238', '2556070', '2554482', '2549597', '2548419', '2584533', '2582234', '2567124', '2565926', '2564461', '2563267', '2561923', '2558237', '2555502', '2548892', '2609826', '2603142', '2586698', '2554481');
  IF target_present <> 63 THEN
    RAISE EXCEPTION 'Pre-condicao thiago-de-joaldo: esperadas 63 rows alvo Camara presentes, encontradas %', target_present;
  END IF;

  SELECT count(*) INTO target_with_other_coverage
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND proposicao_id_api IN ('2611359', '2611024', '2609830', '2609638', '2591498', '2586705', '2569253', '2600831', '2582236', '2581991', '2571048', '2563536', '2562277', '2558239', '2554483', '2550182', '2548423', '2592837', '2586678', '2584173', '2582233', '2571680', '2569275', '2565925', '2564314', '2563264', '2561275', '2554565', '2554480', '2548887', '2586672', '2576587', '2571083', '2565918', '2563202', '2558240', '2554486', '2552721', '2548427', '2582235', '2579604', '2570896', '2564464', '2561924', '2558238', '2556070', '2554482', '2549597', '2548419', '2584533', '2582234', '2567124', '2565926', '2564461', '2563267', '2561923', '2558237', '2555502', '2548892', '2609826', '2603142', '2586698', '2554481')
    AND coverage_id IS NOT NULL
    AND coverage_id <> 'thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506';
  IF target_with_other_coverage <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao thiago-de-joaldo: % rows alvo ja tem coverage_id divergente', target_with_other_coverage;
  END IF;

  SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao thiago-de-joaldo: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;
END $$;

CREATE TEMP TABLE _coverage_thiago_de_joaldo_camara_lote_a ON COMMIT DROP AS
SELECT *
FROM (
  VALUES
    ('2611359', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611359', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611359/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611359', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2611359","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611359","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611359/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611359","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2611024', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611024', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611024/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611024', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2611024","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611024","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611024/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2611024","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2609830', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2609830', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2609830/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2609830', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2609830","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2609830","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2609830/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2609830","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2609638', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2609638', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2609638/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2609638', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2609638","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2609638","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2609638/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2609638","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2591498', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2591498', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2591498/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2591498', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2591498","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2591498","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2591498/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2591498","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2586705', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586705', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586705/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586705', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2586705","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586705","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586705/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586705","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2569253', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2569253', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2569253/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2569253', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2569253","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2569253","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2569253/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2569253","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2600831', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2600831', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2600831/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2600831', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2600831","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2600831","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2600831/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2600831","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2582236', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582236', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582236/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582236', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2582236","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582236","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582236/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582236","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2581991', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2581991', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2581991/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2581991', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2581991","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2581991","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2581991/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2581991","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2571048', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2571048', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2571048/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2571048', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2571048","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2571048","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2571048/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2571048","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2563536', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563536', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563536/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563536', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2563536","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563536","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563536/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563536","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2562277', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2562277', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2562277/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2562277', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2562277","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2562277","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2562277/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2562277","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2558239', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558239', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558239/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558239', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2558239","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558239","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558239/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558239","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2554483', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554483', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554483/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554483', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2554483","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554483","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554483/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554483","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2550182', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2550182', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2550182/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2550182', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2550182","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2550182","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2550182/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2550182","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2548423', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548423', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548423/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548423', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2548423","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548423","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548423/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548423","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2592837', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2592837', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2592837/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2592837', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2592837","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2592837","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2592837/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2592837","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2586678', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586678', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586678/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586678', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2586678","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586678","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586678/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586678","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2584173', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2584173', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2584173/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2584173', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2584173","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2584173","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2584173/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2584173","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2582233', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582233', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582233/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582233', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2582233","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582233","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582233/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582233","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2571680', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2571680', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2571680/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2571680', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2571680","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2571680","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2571680/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2571680","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2569275', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2569275', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2569275/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2569275', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2569275","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2569275","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2569275/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2569275","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2565925', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565925', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565925/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565925', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2565925","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565925","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565925/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565925","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2564314', 1, 3, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564314', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564314/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564314', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2564314","ordem_assinatura":1,"total_autores":3,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564314","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564314/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564314","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2563264', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563264', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563264/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563264', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2563264","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563264","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563264/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563264","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2561275', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561275', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561275/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561275', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2561275","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561275","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561275/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561275","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2554565', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554565', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554565/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554565', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2554565","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554565","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554565/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554565","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2554480', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554480', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554480/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554480', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2554480","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554480","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554480/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554480","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2548887', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548887', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548887/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548887', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2548887","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548887","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548887/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548887","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2586672', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586672', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586672/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586672', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2586672","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586672","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586672/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586672","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2576587', 1, 2, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2576587', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2576587/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2576587', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2576587","ordem_assinatura":1,"total_autores":2,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2576587","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2576587/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2576587","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2571083', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2571083', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2571083/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2571083', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2571083","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2571083","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2571083/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2571083","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2565918', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565918', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565918/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565918', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2565918","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565918","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565918/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565918","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2563202', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563202', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563202/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563202', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2563202","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563202","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563202/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563202","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2558240', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558240', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558240/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558240', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2558240","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558240","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558240/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558240","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2554486', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554486', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554486/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554486', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2554486","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554486","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554486/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554486","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2552721', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2552721', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2552721/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2552721', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2552721","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2552721","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2552721/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2552721","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2548427', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548427', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548427/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548427', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2548427","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548427","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548427/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548427","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2582235', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582235', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582235/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582235', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2582235","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582235","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582235/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582235","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2579604', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2579604', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2579604/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2579604', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2579604","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2579604","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2579604/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2579604","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2570896', 1, 2, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2570896', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2570896/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2570896', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2570896","ordem_assinatura":1,"total_autores":2,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2570896","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2570896/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2570896","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2564464', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564464', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564464/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564464', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2564464","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564464","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564464/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564464","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2561924', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561924', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561924/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561924', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2561924","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561924","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561924/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561924","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2558238', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558238', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558238/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558238', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2558238","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558238","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558238/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558238","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2556070', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2556070', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2556070/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2556070', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2556070","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2556070","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2556070/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2556070","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2554482', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554482', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554482/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554482', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2554482","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554482","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554482/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554482","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2549597', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2549597', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2549597/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2549597', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2549597","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2549597","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2549597/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2549597","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2548419', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548419', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548419/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548419', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2548419","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548419","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548419/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548419","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2584533', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2584533', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2584533/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2584533', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2584533","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2584533","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2584533/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2584533","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2582234', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582234', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582234/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582234', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2582234","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582234","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582234/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2582234","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2567124', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567124', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567124/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567124', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2567124","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567124","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567124/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2567124","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2565926', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565926', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565926/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565926', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2565926","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565926","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565926/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2565926","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2564461', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564461', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564461/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564461', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2564461","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564461","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564461/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2564461","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2563267', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563267', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563267/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563267', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2563267","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563267","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563267/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2563267","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2561923', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561923', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561923/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561923', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2561923","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561923","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561923/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2561923","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2558237', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558237', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558237/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558237', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2558237","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558237","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558237/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2558237","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2555502', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2555502', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2555502/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2555502', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2555502","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2555502","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2555502/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2555502","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2548892', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548892', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548892/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548892', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2548892","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548892","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548892/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2548892","list_endpoint_page_1_contains_id":false,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2609826', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2609826', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2609826/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2609826', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2609826","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2609826","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2609826/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2609826","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2603142', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2603142', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2603142/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2603142', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2603142","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2603142","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2603142/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2603142","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2586698', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586698', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586698/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586698', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2586698","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586698","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586698/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2586698","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb),
    ('2554481', 1, 1, 'Thiago de Joaldo', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554481', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554481/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554481', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"thiago-de-joaldo-camara-lote-a-20260506","coverage_id":"thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":220560,"proposicao_id_api":"2554481","ordem_assinatura":1,"total_autores":1,"autor_nome":"Thiago de Joaldo","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554481","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554481/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2554481","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T09:28:24.261Z"}'::jsonb)
) AS v(
  proposicao_id_api,
  ordem_assinatura,
  total_autores,
  autor_nome,
  autor_tipo,
  detalhe_endpoint,
  autores_endpoint,
  public_url,
  metadata_patch
);

WITH target AS (
  SELECT c.id AS candidato_id
  FROM candidatos c
  WHERE c.slug = 'thiago-de-joaldo'
)
UPDATE projetos_lei pl
SET
  coverage_id = 'thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506',
  coverage_scope = 'inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506',
  metadata = COALESCE(pl.metadata, '{}'::jsonb) || seed.metadata_patch
FROM target
JOIN _coverage_thiago_de_joaldo_camara_lote_a seed ON TRUE
WHERE pl.candidato_id = target.candidato_id
  AND pl.fonte = 'Camara'
  AND pl.proposicao_id_api = seed.proposicao_id_api
  AND (pl.coverage_id IS NULL OR pl.coverage_id = 'thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506');

DO $$
DECLARE
  cand_id uuid;
  with_target_coverage int;
  remaining_null int;
  lme_count int;
  other_slugs_with_target int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'thiago-de-joaldo';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'thiago-de-joaldo: pos-condicao pulada porque candidato nao existe neste banco local/CI minimo';
    RETURN;
  END IF;

  SELECT count(*) INTO with_target_coverage
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id = 'thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506'
    AND coverage_scope = 'inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506';
  IF with_target_coverage <> 63 THEN
    RAISE EXCEPTION 'Pos-apply thiago-de-joaldo: esperadas 63 rows com coverage_id alvo, encontradas %', with_target_coverage;
  END IF;

  SELECT count(*) INTO remaining_null
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id IS NULL;
  IF remaining_null <> 37 THEN
    RAISE EXCEPTION 'Pos-apply thiago-de-joaldo: esperadas 37 rows sem coverage por limite documentado, encontradas %', remaining_null;
  END IF;

  SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pos-apply thiago-de-joaldo: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;

  SELECT count(*) INTO other_slugs_with_target
  FROM projetos_lei
  WHERE candidato_id <> cand_id
    AND coverage_id = 'thiago-de-joaldo-camara-autoria-principal-ampliado-parcial-lote-a-20260506';
  IF other_slugs_with_target <> 0 THEN
    RAISE EXCEPTION 'Pos-apply thiago-de-joaldo: % rows de outros slugs com coverage_id alvo', other_slugs_with_target;
  END IF;

  RAISE NOTICE 'Pos-apply thiago-de-joaldo Camara Lote A: coverage=% sem_coverage=% lme=%', with_target_coverage, remaining_null, lme_count;
END $$;
