-- ============================================
-- Legislacao full-site: ciro-gomes-gov-ce / Camara Dados Abertos / projetos_lei
-- Coverage ampliado parcial: Lote A autoria principal Camara
-- ============================================
-- Fonte oficial: Camara dos Deputados - Dados Abertos
--   https://dadosabertos.camara.leg.br/api/v2/deputados/141406
--   https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id}
--   https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id}/autores
--
-- Artefato de auditoria:
--   fonte interna de curadoria
--
-- Coverage:
--   coverage_id    = ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506
--   coverage_scope = inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506
--
-- Filtro factual: das 95 rows Camara legacy existentes, somente 42
-- foram marcadas com coverage_id porque a API oficial confirmou
-- idDeputado=141406, tipo Deputado(a), ordemAssinatura=1.
-- 53 rows permanecem sem coverage por coautoria/sem autoria verificavel.
--
-- Esta migration NAO escreve em legislacao_mandato_executivo.
-- Esta migration NAO insere, deleta ou trunca rows.
-- ============================================

DO $$
DECLARE
  cand_id uuid;
  total_pl int;
  target_present int;
  target_with_other_coverage int;
  lme_count int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'ciro-gomes-gov-ce';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'ciro-gomes-gov-ce: candidato ausente neste banco local/CI minimo; coverage Camara pulado';
    RETURN;
  END IF;

  SELECT count(*) INTO total_pl FROM projetos_lei WHERE candidato_id = cand_id;
  IF total_pl <> 95 THEN
    RAISE EXCEPTION 'Pre-condicao ciro-gomes-gov-ce: esperadas 95 rows legacy em projetos_lei, encontradas %', total_pl;
  END IF;

  SELECT count(*) INTO target_present
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND fonte = 'Camara'
    AND proposicao_id_api IN ('474247', '474238', '474236', '474233', '463933', '463902', '397417', '382413', '382408', '361607', '353854', '433186', '418262', '397780', '397379', '382412', '382407', '353426', '397073', '385929', '382410', '361824', '359274', '418260', '397779', '391446', '382411', '367011', '359275', '396724', '382409', '361608', '474338', '424929', '400234', '463904', '456882', '428765', '428767', '409284', '421746', '463903');
  IF target_present <> 42 THEN
    RAISE EXCEPTION 'Pre-condicao ciro-gomes-gov-ce: esperadas 42 rows alvo Camara presentes, encontradas %', target_present;
  END IF;

  SELECT count(*) INTO target_with_other_coverage
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND proposicao_id_api IN ('474247', '474238', '474236', '474233', '463933', '463902', '397417', '382413', '382408', '361607', '353854', '433186', '418262', '397780', '397379', '382412', '382407', '353426', '397073', '385929', '382410', '361824', '359274', '418260', '397779', '391446', '382411', '367011', '359275', '396724', '382409', '361608', '474338', '424929', '400234', '463904', '456882', '428765', '428767', '409284', '421746', '463903')
    AND coverage_id IS NOT NULL
    AND coverage_id <> 'ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506';
  IF target_with_other_coverage <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao ciro-gomes-gov-ce: % rows alvo ja tem coverage_id divergente', target_with_other_coverage;
  END IF;

  SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao ciro-gomes-gov-ce: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;
END $$;

CREATE TEMP TABLE _coverage_ciro_gomes_gov_ce_camara_lote_a ON COMMIT DROP AS
SELECT *
FROM (
  VALUES
    ('474247', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/474247', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/474247/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/474247', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"474247","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/474247","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/474247/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/474247","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('474238', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/474238', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/474238/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/474238', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"474238","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/474238","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/474238/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/474238","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('474236', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/474236', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/474236/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/474236', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"474236","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/474236","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/474236/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/474236","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('474233', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/474233', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/474233/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/474233', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"474233","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/474233","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/474233/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/474233","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('463933', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/463933', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/463933/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/463933', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"463933","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/463933","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/463933/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/463933","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('463902', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/463902', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/463902/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/463902', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"463902","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/463902","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/463902/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/463902","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('397417', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/397417', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/397417/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/397417', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"397417","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/397417","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/397417/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/397417","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('382413', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382413', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382413/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382413', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"382413","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382413","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382413/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382413","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('382408', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382408', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382408/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382408', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"382408","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382408","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382408/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382408","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('361607', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/361607', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/361607/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/361607', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"361607","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/361607","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/361607/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/361607","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('353854', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/353854', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/353854/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/353854', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"353854","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/353854","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/353854/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/353854","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('433186', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/433186', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/433186/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/433186', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"433186","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/433186","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/433186/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/433186","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('418262', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/418262', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/418262/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/418262', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"418262","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/418262","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/418262/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/418262","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('397780', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/397780', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/397780/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/397780', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"397780","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/397780","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/397780/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/397780","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('397379', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/397379', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/397379/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/397379', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"397379","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/397379","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/397379/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/397379","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('382412', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382412', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382412/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382412', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"382412","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382412","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382412/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382412","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('382407', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382407', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382407/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382407', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"382407","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382407","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382407/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382407","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('353426', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/353426', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/353426/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/353426', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"353426","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/353426","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/353426/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/353426","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('397073', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/397073', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/397073/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/397073', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"397073","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/397073","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/397073/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/397073","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('385929', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/385929', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/385929/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/385929', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"385929","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/385929","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/385929/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/385929","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('382410', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382410', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382410/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382410', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"382410","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382410","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382410/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382410","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('361824', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/361824', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/361824/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/361824', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"361824","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/361824","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/361824/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/361824","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('359274', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/359274', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/359274/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/359274', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"359274","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/359274","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/359274/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/359274","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('418260', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/418260', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/418260/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/418260', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"418260","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/418260","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/418260/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/418260","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('397779', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/397779', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/397779/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/397779', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"397779","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/397779","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/397779/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/397779","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('391446', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/391446', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/391446/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/391446', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"391446","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/391446","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/391446/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/391446","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('382411', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382411', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382411/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382411', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"382411","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382411","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382411/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382411","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('367011', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/367011', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/367011/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/367011', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"367011","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/367011","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/367011/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/367011","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('359275', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/359275', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/359275/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/359275', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"359275","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/359275","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/359275/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/359275","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('396724', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/396724', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/396724/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/396724', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"396724","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/396724","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/396724/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/396724","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('382409', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382409', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382409/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/382409', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"382409","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382409","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382409/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/382409","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('361608', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/361608', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/361608/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/361608', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"361608","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/361608","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/361608/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/361608","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('474338', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/474338', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/474338/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/474338', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"474338","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/474338","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/474338/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/474338","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('424929', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/424929', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/424929/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/424929', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"424929","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/424929","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/424929/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/424929","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('400234', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/400234', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/400234/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/400234', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"400234","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/400234","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/400234/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/400234","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('463904', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/463904', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/463904/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/463904', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"463904","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/463904","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/463904/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/463904","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('456882', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/456882', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/456882/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/456882', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"456882","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/456882","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/456882/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/456882","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('428765', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/428765', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/428765/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/428765', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"428765","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/428765","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/428765/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/428765","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('428767', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/428767', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/428767/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/428767', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"428767","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/428767","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/428767/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/428767","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('409284', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/409284', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/409284/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/409284', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"409284","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/409284","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/409284/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/409284","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('421746', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/421746', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/421746/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/421746', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"421746","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/421746","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/421746/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/421746","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb),
    ('463903', 1, 1, 'Ciro Gomes', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/463903', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/463903/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/463903', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ciro-gomes-gov-ce-camara-lote-a-20260506","coverage_id":"ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":141406,"proposicao_id_api":"463903","ordem_assinatura":1,"total_autores":1,"autor_nome":"Ciro Gomes","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/463903","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/463903/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/463903","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T03:43:08.253Z"}'::jsonb)
) AS v(
  proposicao_id_api,
  ordem_assinatura,
  total_autores,
  autor_nome,
  autor_tipo,
  detalhe_endpoint,
  autores_endpoint,
  public_url,
  metadata_patch
);

WITH target AS (
  SELECT c.id AS candidato_id
  FROM candidatos c
  WHERE c.slug = 'ciro-gomes-gov-ce'
)
UPDATE projetos_lei pl
SET
  coverage_id = 'ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506',
  coverage_scope = 'inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506',
  metadata = COALESCE(pl.metadata, '{}'::jsonb) || seed.metadata_patch
FROM target
JOIN _coverage_ciro_gomes_gov_ce_camara_lote_a seed ON TRUE
WHERE pl.candidato_id = target.candidato_id
  AND pl.fonte = 'Camara'
  AND pl.proposicao_id_api = seed.proposicao_id_api
  AND (pl.coverage_id IS NULL OR pl.coverage_id = 'ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506');

DO $$
DECLARE
  cand_id uuid;
  with_target_coverage int;
  remaining_null int;
  lme_count int;
  other_slugs_with_target int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'ciro-gomes-gov-ce';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'ciro-gomes-gov-ce: pos-condicao pulada porque candidato nao existe neste banco local/CI minimo';
    RETURN;
  END IF;

  SELECT count(*) INTO with_target_coverage
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id = 'ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506'
    AND coverage_scope = 'inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506';
  IF with_target_coverage <> 42 THEN
    RAISE EXCEPTION 'Pos-apply ciro-gomes-gov-ce: esperadas 42 rows com coverage_id alvo, encontradas %', with_target_coverage;
  END IF;

  SELECT count(*) INTO remaining_null
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id IS NULL;
  IF remaining_null <> 53 THEN
    RAISE EXCEPTION 'Pos-apply ciro-gomes-gov-ce: esperadas 53 rows sem coverage por limite documentado, encontradas %', remaining_null;
  END IF;

  SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pos-apply ciro-gomes-gov-ce: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;

  SELECT count(*) INTO other_slugs_with_target
  FROM projetos_lei
  WHERE candidato_id <> cand_id
    AND coverage_id = 'ciro-gomes-gov-ce-camara-autoria-principal-ampliado-parcial-lote-a-20260506';
  IF other_slugs_with_target <> 0 THEN
    RAISE EXCEPTION 'Pos-apply ciro-gomes-gov-ce: % rows de outros slugs com coverage_id alvo', other_slugs_with_target;
  END IF;

  RAISE NOTICE 'Pos-apply ciro-gomes-gov-ce Camara Lote A: coverage=% sem_coverage=% lme=%', with_target_coverage, remaining_null, lme_count;
END $$;
