-- ============================================
-- Legislacao full-site: fabio-mitidieri / Camara Dados Abertos / projetos_lei
-- Coverage ampliado parcial: Lote A autoria principal Camara
-- ============================================
-- Fonte oficial: Camara dos Deputados - Dados Abertos
--   https://dadosabertos.camara.leg.br/api/v2/deputados/178969
--   https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id}
--   https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id}/autores
--
-- Artefato de auditoria:
--   fonte interna de curadoria
--
-- Coverage:
--   coverage_id    = fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506
--   coverage_scope = inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506
--
-- Filtro factual: das 100 rows Camara legacy existentes, somente 71
-- foram marcadas com coverage_id porque a API oficial confirmou
-- idDeputado=178969, tipo Deputado(a), ordemAssinatura=1.
-- 29 rows permanecem sem coverage por coautoria/sem autoria verificavel.
--
-- Esta migration NAO escreve em legislacao_mandato_executivo.
-- Esta migration NAO insere, deleta ou trunca rows.
-- ============================================

DO $$
DECLARE
  cand_id uuid;
  total_pl int;
  target_present int;
  target_with_other_coverage int;
  lme_count int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'fabio-mitidieri';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'fabio-mitidieri: candidato ausente neste banco local/CI minimo; coverage Camara pulado';
    RETURN;
  END IF;

  SELECT count(*) INTO total_pl FROM projetos_lei WHERE candidato_id = cand_id;
  IF total_pl <> 100 THEN
    RAISE EXCEPTION 'Pre-condicao fabio-mitidieri: esperadas 100 rows legacy em projetos_lei, encontradas %', total_pl;
  END IF;

  SELECT count(*) INTO target_present
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND fonte = 'Camara'
    AND proposicao_id_api IN ('2325027', '2313281', '2308548', '2308474', '2301540', '2295349', '2325030', '2283019', '2325929', '2325927', '2325072', '2325028', '2325024', '2313282', '2308551', '2308549', '2308478', '2308476', '2308472', '2308470', '2308467', '2308462', '2302194', '2302191', '2325025', '2308545', '2308473', '2308468', '2301632', '2299012', '2293794', '2287256', '2282688', '2277501', '2234474', '2225794', '2314046', '2308550', '2308477', '2308471', '2308466', '2302193', '2301542', '2295802', '2286305', '2285154', '2279607', '2276636', '2260656', '2229249', '2308469', '2308036', '2302190', '2294204', '2289523', '2286217', '2279488', '2234575', '2226395', '2301631', '2298990', '2282391', '2276708', '2229250', '2225123', '2279604', '2275922', '2242711', '2226648', '2286301', '2325073');
  IF target_present <> 71 THEN
    RAISE EXCEPTION 'Pre-condicao fabio-mitidieri: esperadas 71 rows alvo Camara presentes, encontradas %', target_present;
  END IF;

  SELECT count(*) INTO target_with_other_coverage
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND proposicao_id_api IN ('2325027', '2313281', '2308548', '2308474', '2301540', '2295349', '2325030', '2283019', '2325929', '2325927', '2325072', '2325028', '2325024', '2313282', '2308551', '2308549', '2308478', '2308476', '2308472', '2308470', '2308467', '2308462', '2302194', '2302191', '2325025', '2308545', '2308473', '2308468', '2301632', '2299012', '2293794', '2287256', '2282688', '2277501', '2234474', '2225794', '2314046', '2308550', '2308477', '2308471', '2308466', '2302193', '2301542', '2295802', '2286305', '2285154', '2279607', '2276636', '2260656', '2229249', '2308469', '2308036', '2302190', '2294204', '2289523', '2286217', '2279488', '2234575', '2226395', '2301631', '2298990', '2282391', '2276708', '2229250', '2225123', '2279604', '2275922', '2242711', '2226648', '2286301', '2325073')
    AND coverage_id IS NOT NULL
    AND coverage_id <> 'fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506';
  IF target_with_other_coverage <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao fabio-mitidieri: % rows alvo ja tem coverage_id divergente', target_with_other_coverage;
  END IF;

  SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao fabio-mitidieri: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;
END $$;

CREATE TEMP TABLE _coverage_fabio_mitidieri_camara_lote_a ON COMMIT DROP AS
SELECT *
FROM (
  VALUES
    ('2325027', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325027', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325027/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325027', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2325027","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325027","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325027/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325027","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2313281', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2313281', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2313281/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2313281', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2313281","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2313281","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2313281/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2313281","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2308548', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308548', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308548/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308548', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2308548","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308548","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308548/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308548","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2308474', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308474', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308474/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308474', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2308474","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308474","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308474/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308474","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2301540', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301540', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301540/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301540', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2301540","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301540","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301540/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301540","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2295349', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295349', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295349/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295349', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2295349","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295349","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295349/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295349","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2325030', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325030', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325030/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325030', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2325030","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325030","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325030/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325030","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2283019', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2283019', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2283019/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2283019', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2283019","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2283019","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2283019/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2283019","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2325929', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325929', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325929/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325929', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2325929","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325929","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325929/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325929","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2325927', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325927', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325927/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325927', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2325927","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325927","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325927/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325927","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2325072', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325072', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325072/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325072', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2325072","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325072","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325072/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325072","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2325028', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325028', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325028/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325028', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2325028","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325028","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325028/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325028","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2325024', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325024', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325024/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325024', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2325024","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325024","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325024/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325024","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2313282', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2313282', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2313282/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2313282', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2313282","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2313282","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2313282/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2313282","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2308551', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308551', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308551/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308551', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2308551","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308551","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308551/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308551","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2308549', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308549', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308549/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308549', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2308549","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308549","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308549/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308549","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2308478', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308478', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308478/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308478', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2308478","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308478","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308478/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308478","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2308476', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308476', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308476/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308476', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2308476","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308476","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308476/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308476","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2308472', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308472', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308472/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308472', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2308472","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308472","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308472/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308472","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2308470', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308470', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308470/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308470', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2308470","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308470","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308470/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308470","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2308467', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308467', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308467/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308467', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2308467","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308467","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308467/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308467","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2308462', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308462', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308462/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308462', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2308462","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308462","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308462/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308462","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2302194', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302194', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302194/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302194', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2302194","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302194","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302194/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302194","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2302191', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302191', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302191/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302191', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2302191","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302191","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302191/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302191","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2325025', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325025', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325025/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325025', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2325025","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325025","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325025/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325025","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2308545', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308545', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308545/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308545', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2308545","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308545","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308545/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308545","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2308473', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308473', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308473/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308473', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2308473","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308473","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308473/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308473","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2308468', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308468', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308468/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308468', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2308468","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308468","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308468/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308468","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2301632', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301632', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301632/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301632', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2301632","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301632","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301632/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301632","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2299012', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2299012', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2299012/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2299012', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2299012","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2299012","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2299012/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2299012","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2293794', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2293794', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2293794/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2293794', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2293794","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2293794","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2293794/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2293794","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2287256', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2287256', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2287256/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2287256', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2287256","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2287256","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2287256/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2287256","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2282688', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2282688', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2282688/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2282688', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2282688","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2282688","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2282688/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2282688","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2277501', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2277501', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2277501/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2277501', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2277501","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2277501","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2277501/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2277501","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2234474', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2234474', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2234474/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2234474', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2234474","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2234474","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2234474/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2234474","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2225794', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2225794', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2225794/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2225794', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2225794","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2225794","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2225794/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2225794","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2314046', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2314046', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2314046/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2314046', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2314046","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2314046","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2314046/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2314046","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2308550', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308550', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308550/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308550', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2308550","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308550","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308550/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308550","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2308477', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308477', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308477/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308477', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2308477","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308477","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308477/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308477","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2308471', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308471', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308471/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308471', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2308471","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308471","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308471/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308471","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2308466', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308466', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308466/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308466', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2308466","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308466","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308466/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308466","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2302193', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302193', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302193/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302193', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2302193","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302193","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302193/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302193","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2301542', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301542', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301542/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301542', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2301542","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301542","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301542/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301542","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2295802', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295802', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295802/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295802', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2295802","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295802","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295802/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2295802","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2286305', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2286305', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2286305/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2286305', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2286305","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2286305","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2286305/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2286305","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2285154', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2285154', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2285154/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2285154', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2285154","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2285154","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2285154/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2285154","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2279607', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2279607', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2279607/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2279607', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2279607","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2279607","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2279607/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2279607","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2276636', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2276636', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2276636/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2276636', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2276636","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2276636","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2276636/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2276636","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2260656', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2260656', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2260656/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2260656', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2260656","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2260656","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2260656/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2260656","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2229249', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2229249', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2229249/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2229249', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2229249","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2229249","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2229249/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2229249","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2308469', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308469', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308469/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308469', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2308469","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308469","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308469/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308469","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2308036', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308036', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308036/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308036', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2308036","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308036","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308036/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2308036","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2302190', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302190', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302190/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302190', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2302190","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302190","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302190/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2302190","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2294204', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2294204', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2294204/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2294204', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2294204","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2294204","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2294204/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2294204","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2289523', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2289523', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2289523/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2289523', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2289523","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2289523","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2289523/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2289523","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2286217', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2286217', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2286217/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2286217', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2286217","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2286217","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2286217/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2286217","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2279488', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2279488', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2279488/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2279488', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2279488","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2279488","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2279488/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2279488","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2234575', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2234575', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2234575/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2234575', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2234575","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2234575","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2234575/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2234575","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2226395', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2226395', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2226395/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2226395', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2226395","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2226395","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2226395/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2226395","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2301631', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301631', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301631/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301631', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2301631","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301631","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301631/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2301631","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2298990', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298990', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298990/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298990', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2298990","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298990","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298990/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2298990","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2282391', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2282391', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2282391/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2282391', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2282391","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2282391","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2282391/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2282391","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2276708', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2276708', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2276708/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2276708', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2276708","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2276708","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2276708/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2276708","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2229250', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2229250', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2229250/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2229250', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2229250","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2229250","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2229250/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2229250","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2225123', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2225123', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2225123/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2225123', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2225123","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2225123","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2225123/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2225123","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2279604', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2279604', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2279604/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2279604', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2279604","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2279604","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2279604/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2279604","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2275922', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2275922', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2275922/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2275922', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2275922","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2275922","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2275922/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2275922","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2242711', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2242711', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2242711/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2242711', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2242711","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2242711","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2242711/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2242711","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2226648', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2226648', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2226648/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2226648', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2226648","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2226648","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2226648/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2226648","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2286301', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2286301', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2286301/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2286301', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2286301","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2286301","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2286301/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2286301","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb),
    ('2325073', 1, 1, 'Fábio Mitidieri', 'Deputado(a)', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325073', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325073/autores', 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325073', '{"source":"Camara Dados Abertos","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"fabio-mitidieri-camara-lote-a-20260506","coverage_id":"fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"camara_id_deputado":178969,"proposicao_id_api":"2325073","ordem_assinatura":1,"total_autores":1,"autor_nome":"Fábio Mitidieri","autor_tipo":"Deputado(a)","autoria_principal_verificada":true,"detalhe_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325073","autores_endpoint":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325073/autores","public_url":"https://dadosabertos.camara.leg.br/api/v2/proposicoes/2325073","list_endpoint_page_1_contains_id":true,"fonte_oficial_verificada_em":"2026-05-06T05:31:00.928Z"}'::jsonb)
) AS v(
  proposicao_id_api,
  ordem_assinatura,
  total_autores,
  autor_nome,
  autor_tipo,
  detalhe_endpoint,
  autores_endpoint,
  public_url,
  metadata_patch
);

WITH target AS (
  SELECT c.id AS candidato_id
  FROM candidatos c
  WHERE c.slug = 'fabio-mitidieri'
)
UPDATE projetos_lei pl
SET
  coverage_id = 'fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506',
  coverage_scope = 'inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506',
  metadata = COALESCE(pl.metadata, '{}'::jsonb) || seed.metadata_patch
FROM target
JOIN _coverage_fabio_mitidieri_camara_lote_a seed ON TRUE
WHERE pl.candidato_id = target.candidato_id
  AND pl.fonte = 'Camara'
  AND pl.proposicao_id_api = seed.proposicao_id_api
  AND (pl.coverage_id IS NULL OR pl.coverage_id = 'fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506');

DO $$
DECLARE
  cand_id uuid;
  with_target_coverage int;
  remaining_null int;
  lme_count int;
  other_slugs_with_target int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'fabio-mitidieri';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'fabio-mitidieri: pos-condicao pulada porque candidato nao existe neste banco local/CI minimo';
    RETURN;
  END IF;

  SELECT count(*) INTO with_target_coverage
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id = 'fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506'
    AND coverage_scope = 'inventario_ampliado_parcial_camara_autoria_principal_lote_a_20260506';
  IF with_target_coverage <> 71 THEN
    RAISE EXCEPTION 'Pos-apply fabio-mitidieri: esperadas 71 rows com coverage_id alvo, encontradas %', with_target_coverage;
  END IF;

  SELECT count(*) INTO remaining_null
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id IS NULL;
  IF remaining_null <> 29 THEN
    RAISE EXCEPTION 'Pos-apply fabio-mitidieri: esperadas 29 rows sem coverage por limite documentado, encontradas %', remaining_null;
  END IF;

  SELECT count(*) INTO lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pos-apply fabio-mitidieri: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;

  SELECT count(*) INTO other_slugs_with_target
  FROM projetos_lei
  WHERE candidato_id <> cand_id
    AND coverage_id = 'fabio-mitidieri-camara-autoria-principal-ampliado-parcial-lote-a-20260506';
  IF other_slugs_with_target <> 0 THEN
    RAISE EXCEPTION 'Pos-apply fabio-mitidieri: % rows de outros slugs com coverage_id alvo', other_slugs_with_target;
  END IF;

  RAISE NOTICE 'Pos-apply fabio-mitidieri Camara Lote A: coverage=% sem_coverage=% lme=%', with_target_coverage, remaining_null, lme_count;
END $$;
