-- Patrimonio declarado de 2026 das fichas novas de 03/08, lote 2 de 3.
-- Cabecalho completo com fonte, metodo e a armadilha do pacote esta no lote 1.
INSERT INTO public.patrimonio (candidato_id, ano_eleicao, valor_total, bens, fonte)
  SELECT id, 2026, 153493.09, '[{"tipo": "Caderneta de poupança", "valor": 599.19, "descricao": "SALDO EM CONTA POUPANÇA"}, {"tipo": "Veículo automotor terrestre: caminhão, automóvel, moto, etc.", "valor": 75000.0, "descricao": "SEDÃ MÉDIO"}, {"tipo": "Quotas ou quinhões de capital", "valor": 75000.0, "descricao": "QUOTAS DE CAPITAL DE EMPRESA"}, {"tipo": "Depósito bancário em conta corrente no País", "valor": 442.21, "descricao": "SALDO EM CONTA"}, {"tipo": "Depósito bancário em conta corrente no País", "valor": 98.21, "descricao": "SALDO EM CONTA"}, {"tipo": "Depósito bancário em conta corrente no País", "valor": 85.01, "descricao": "SALDO EM CONTA POUPANÇA"}, {"tipo": "Depósito bancário em conta corrente no País", "valor": 98.21, "descricao": "SALDO EM CONTA"}, {"tipo": "VGBL - Vida Gerador de Benefício Livre", "valor": 2157.25, "descricao": "SALDO EM VGBL"}, {"tipo": "Caderneta de poupança", "valor": 13.01, "descricao": "SALDO EM CONTA POUPANÇA"}]'::jsonb, 'TSE' FROM public.candidatos WHERE slug = 'larissa-rosado'
UNION ALL
  SELECT id, 2026, 1836.49, '[{"tipo": "Dinheiro em espécie - moeda nacional", "valor": 52.0, "descricao": "DINHEIRO"}, {"tipo": "Depósito bancário em conta corrente no País", "valor": 1784.49, "descricao": "DINHEIRO DEPOSITADO EM CONTA CORRENTE"}]'::jsonb, 'TSE' FROM public.candidatos WHERE slug = 'naf-nascimento'
UNION ALL
  SELECT id, 2026, 1322570.41, '[{"tipo": "Apartamento", "valor": 992570.41, "descricao": "50% de APARTAMENTO EM ARACAJU"}, {"tipo": "Veículo automotor terrestre: caminhão, automóvel, moto, etc.", "valor": 315000.0, "descricao": "H9 GWM"}, {"tipo": "Quotas ou quinhões de capital", "valor": 15000.0, "descricao": "sócia quotista da Sociedade Empresária Limitada Agropecuária e Incorporadora Esperança LTDA-ME, com 15.000 (quinze mil) quotas"}]'::jsonb, 'TSE' FROM public.candidatos WHERE slug = 'priscila-felizola'
UNION ALL
  SELECT id, 2026, 115000.00, '[{"tipo": "Casa", "valor": 115000.0, "descricao": "RESIDENCIAL"}]'::jsonb, 'TSE' FROM public.candidatos WHERE slug = 'prof-enfermeira-kaelly'
UNION ALL
  SELECT id, 2026, 391339.32, '[{"tipo": "Veículo automotor terrestre: caminhão, automóvel, moto, etc.", "valor": 55000.0, "descricao": "CARRO - RENAUT OROCH2.0 ANO 2016"}, {"tipo": "Caderneta de poupança", "valor": 5539.25, "descricao": "BANCO DO BRASIL"}, {"tipo": "Caderneta de poupança", "valor": 1498.45, "descricao": "POUPANÇA BANCO DO BRASIL"}, {"tipo": "Dinheiro em espécie - moeda estrangeira", "valor": 204.21, "descricao": "CRÉDITO CARTÃO - DOLAR"}, {"tipo": "Aplicação de renda fixa (CDB, RDB e outros)", "valor": 97.41, "descricao": "RENDA FIXA - BANCO DO BRASIL"}, {"tipo": "Aplicação de renda fixa (CDB, RDB e outros)", "valor": 169000.0, "descricao": "PREVIDENCIA - BANCO DO BRASIL"}, {"tipo": "Veículo automotor terrestre: caminhão, automóvel, moto, etc.", "valor": 140000.0, "descricao": "CHERY ITIGO SPORT - CINZA"}, {"tipo": "Caderneta de poupança", "valor": 20000.0, "descricao": "CONTA POUPANÇA CAIXA ECONÔMICA FEDERAL"}]'::jsonb, 'TSE' FROM public.candidatos WHERE slug = 'prof-meire-reis';;
