-- ============================================
-- Legislacao full-site: ivan-moraes / Recife OpenLegis / projetos_lei
-- Seed ampliado_parcial: autoria principal parlamentar municipal
-- ============================================
-- Fonte oficial:
--   https://publico.recife.pe.leg.br/consultas/materia
--   https://publico.recife.pe.leg.br/@@materias?ano={ano}&tipo={tipo}
--
-- Artefato de auditoria:
--   fonte interna de curadoria
--
-- Coverage:
--   coverage_id    = ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507
--   coverage_scope = inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507
--
-- Filtro factual: OpenLegis oficial com autoria firstAuthor=true para Ivan Moraes,
-- tipos aceitos 10/14, numero/ano/ementa/PDF presentes e zero escrita em legislacao_mandato_executivo.

DO $$
DECLARE
  cand_id uuid;
  current_pl_count int;
  current_lme_count int;
  mandato_count int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'ivan-moraes' AND publicavel = true;

  IF cand_id IS NULL THEN
    RAISE NOTICE 'ivan-moraes: pre-condicao pulada porque candidato publico nao existe neste banco local/CI minimo';
    RETURN;
  END IF;

  SELECT count(*) INTO current_pl_count FROM projetos_lei WHERE candidato_id = cand_id;
  SELECT count(*) INTO current_lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;

  IF current_pl_count <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao ivan-moraes: projetos_lei esperado 0, encontrado %', current_pl_count;
  END IF;

  IF current_lme_count <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao ivan-moraes: legislacao_mandato_executivo esperado 0, encontrado %', current_lme_count;
  END IF;

  SELECT count(*) INTO mandato_count
  FROM historico_politico hp
  WHERE hp.candidato_id = cand_id
    AND hp.tipo_evento = 'mandato'
    AND UPPER(COALESCE(hp.estado, '')) = 'PE'
    AND (hp.cargo ILIKE '%Vereador%' OR hp.cargo_canonico = 'Vereador')
    AND COALESCE(hp.periodo_inicio, 9999) <= 2024
    AND COALESCE(hp.periodo_fim, 0) >= 2017;

  IF mandato_count < 1 THEN
    RAISE EXCEPTION 'Pre-condicao ivan-moraes: mandato Vereador/Recife PE compativel com 2017-2024 nao encontrado';
  END IF;
END $$;

CREATE TEMP TABLE _seed_ivan_moraes_recife_openlegis_lote_a (
  tipo text NOT NULL,
  numero text NOT NULL,
  ano int NOT NULL,
  ementa text NOT NULL,
  fonte text NOT NULL,
  proposicao_id_api text NOT NULL,
  url_inteiro_teor text NOT NULL,
  coverage_id text NOT NULL,
  coverage_scope text NOT NULL,
  metadata jsonb NOT NULL
) ON COMMIT DROP;

INSERT INTO _seed_ivan_moraes_recife_openlegis_lote_a (
  tipo,
  numero,
  ano,
  ementa,
  fonte,
  proposicao_id_api,
  url_inteiro_teor,
  coverage_id,
  coverage_scope,
  metadata
)
VALUES
    ('PL', '214', 2024, 'Declara os "Festivais Pré No Reggae, Pré AMP, Pólo Hip Hop e Cena Peixinhos" como Patrimônio Cultural Imaterial do Município do Recife', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-157520', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/157520_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"157520","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2024&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/157520","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=157520","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/157520_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '210', 2024, 'Suprime o § 7º do art. 3º da Lei Municipal nº 18.936, de 08 de junho de 2022, que Disciplina o Benefício de Auxílio-Moradia no âmbito do Município do Recife.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-157211', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/157211_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"157211","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2024&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/157211","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=157211","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/157211_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '192', 2024, 'Declara Patrimônio Cultural Imaterial do Recife o “Bloco Afro Lamento Negro”.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-155745', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/155745_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"155745","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2024&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/155745","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=155745","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/155745_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '14', 2024, 'Denominar-se-á “Parque da Resistência Leonardo Cisneiros” o parque que será construído no Cais José Estelita, município do Recife.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-147937', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/147937_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"147937","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2024&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/147937","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=147937","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/147937_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '257', 2023, 'Institui no Calendário Oficial de Eventos do Município do Recife o “Dia em homenagem a Tibira Tupinambá”.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-145707', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/145707_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"145707","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2023&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/145707","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=145707","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/145707_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '99', 2023, 'Altera a Lei Municipal nº 16.243, de 13 de setembro de 1996, que Estabelece a Política do Meio Ambiente da Cidade do Recife e consolida a sua Legislação Ambiental, mediante a instituição do Código do Meio Ambiente e do Equilíbrio Ecológico da Cidade do Recife.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-138554', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/138554_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"138554","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2023&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/138554","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=138554","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/138554_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PELO', '3', 2023, 'Adiciona o art. 125-A à Lei Orgânica do Município do Recife para reconhecer a natureza como sujeito de direito.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-14:ID-141210', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/141210_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":14,"openlegis_id":"141210","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2023&tipo=14","official_item_url":"https://publico.recife.pe.leg.br/@@materias/141210","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=141210","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/141210_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '1', 2023, 'Declara de Utilidade Pública, no âmbito do Município do Recife, a Associação Católica dos Samaritanos.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-133292', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/133292_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"133292","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2023&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/133292","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=133292","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/133292_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '295', 2022, 'Declara a “Parada da Diversidade de Dois Unidos” como Patrimônio Cultural Imaterial do Município do Recife.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-131874', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/131874_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"131874","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2022&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/131874","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=131874","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/131874_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '256', 2022, 'Institui as bases para elaboração da “Política de Reconhecimento e Desenvolvimento Socioambiental das Comunidades Tradicionais Pesqueiras” no município do Recife.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-130241', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/130241_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"130241","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2022&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/130241","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=130241","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/130241_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '206', 2022, 'Institui a Semana Municipal dos Povos Indígenas no Calendário Oficial de Eventos do Município do Recife.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-126710', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/126710_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"126710","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2022&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/126710","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=126710","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/126710_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '197', 2022, 'Institui no Calendário Oficial de Eventos do Município do Recife o “Dia da Luta e Resistência dos Povos Indígenas”.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-125852', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/125852_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"125852","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2022&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/125852","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=125852","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/125852_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '192', 2022, 'Assegura à população transexual e travesti a reserva de 5% das vagas oferecidas nos cursos de formação profissional e no programa de Ensino de Jovens e Adultos oferecidos pelo Município do Recife.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-125644', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/125644_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"125644","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2022&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/125644","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=125644","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/125644_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '182', 2022, 'Assegura à população transexual e travesti a reserva de 5% das vagas oferecidas nos concursos públicos e seleções simplificadas para provimento de cargos e empregos públicos no Município do Recife.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-125043', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/125043_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"125043","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2022&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/125043","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=125043","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/125043_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '178', 2022, 'Estabelece a reserva de vagas para pessoas autodeclaradas transexuais e travestis por parte das empresas contratadas pela Administração Pública do Município do Recife.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-124854', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/124854_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"124854","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2022&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/124854","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=124854","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/124854_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '135', 2022, 'Assegura às pessoas com deficiência auditiva ou surdas, em atendimento nas instituições de saúde privada do Município de Recife, o direito a acompanhante ou atendente pessoal, e dá outras providências.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-123553', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/123553_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"123553","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2022&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/123553","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=123553","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/123553_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '134', 2022, 'Assegura às pessoas com deficiência auditiva ou surdas, em atendimento nas instituições de saúde pública do município de Recife, o direito a acompanhante ou atendente pessoal, e dá outras providências.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-123452', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/123452_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"123452","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2022&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/123452","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=123452","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/123452_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '103', 2022, 'Declara o “Afoxé” como Patrimônio Cultural Imaterial do Município do Recife.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-121909', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/121909_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"121909","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2022&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/121909","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=121909","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/121909_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '405', 2021, 'Institui a celebração do “Dia de Quem Cuida de Mim” nas creches e escolas públicas e privadas do município do Recife.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-117165', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/117165_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"117165","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2021&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/117165","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=117165","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/117165_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '370', 2021, 'Institui a gratuidade (Passe Livre) no sistema de transporte público coletivo para pessoas de baixa renda portadoras do Vírus da Síndrome da Imunodeficiência Adquirida (HIV/AIDS).', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-115896', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/115896_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"115896","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2021&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/115896","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=115896","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/115896_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '169', 2021, 'DENOMINAR-SE-Á "PARQUE DA RESISTÊNCIA LEONARDO CISNEIROS" O PARQUE QUE SERÁ CONSTRUÍDO NO CAIS JOSÉ ESTELITA, MUNICÍPIO DO RECIFE.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-107171', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/107171_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"107171","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2021&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/107171","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=107171","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/107171_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '114', 2021, 'DENOMINAR-SE-Á "VIA PARQUE LÚCIA MOURA" A VIA PARQUE QUE SERÁ CONSTRUÍDA NO BAIRRO DAS GRAÇAS, MUNICÍPIO DO RECIFE.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-105695', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/105695_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"105695","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2021&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/105695","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=105695","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/105695_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"},{"description":"Parlamentar","firstAuthor":false,"title":"Cida Pedrosa"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '110', 2021, 'SUSPENDE O CUMPRIMENTO DE MEDIDAS JUDICIAIS, EXTRAJUDICIAIS OU ADMINISTRATIVAS QUE RESULTEM EM DESPEJOS, DESOCUPAÇÕES OU REMOÇÕES FORÇADAS NO MUNICÍPIO DO RECIFE, ENQUANTO PERDURAR O ESTADO DE CALAMIDADE PÚBLICA DECORRENTE DA PANDEMIA DA COVID-19.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-105573', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/105573_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"105573","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2021&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/105573","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=105573","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/105573_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"},{"description":"Parlamentar","firstAuthor":false,"title":"Dani Portela"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '99', 2021, 'MODIFICA A LEI MUNICIPAL Nº 18.751, DE 15 DE SETEMBRO DE 2020, QUE DETERMINA QUE ESTABELECIMENTOS PRIVADOS INSTALADOS NO MUNICÍPIO DO RECIFE CONSIDERADOS COMO DE SERVIÇOS ESSENCIAIS FORNEÇAM MÁSCARAS, ÁLCOOL 70% E DISPONHAM DE PIA COM ÁGUA E SABÃO EM LOCAL DE FÁCIL ACESSO AOS SEUS FUNCIONÁRIOS.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-105360', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/105360_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"105360","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2021&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/105360","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=105360","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/105360_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '39', 2021, 'INSTITUI AS BASES PARA A ELABORAÇÃO DO "PROGRAMA DE ATENÇÃO HUMANIZADA AO ABORTO LEGAL E JURIDICAMENTE AUTORIZADO" NO ÂMBITO DO MUNICÍPIO DO RECIFE.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-103942', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/103942_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"103942","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2021&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/103942","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=103942","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/103942_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '24', 2021, 'INCLUI O "DIA DA VISIBILIDADE LÉSBICA" NO CALENDÁRIO OFICIAL DE EVENTOS DO MUNICÍPIO DO RECIFE.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-103230', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/103230_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"103230","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2021&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/103230","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=103230","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/103230_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '23', 2021, 'DISPÕE SOBRE A TRANSPARÊNCIA DOS SERVIÇOS DE PUBLICIDADE E PROPAGANDA CONTRATADOS PELOS PODERES EXECUTIVO E LEGISLATIVO MUNICIPAIS.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-103229', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/103229_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"103229","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2021&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/103229","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=103229","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/103229_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '22', 2021, 'DETERMINA QUE RESTAURANTES, PIZZARIAS, CHURRASCARIAS, BARES, CAFÉS, LANCHONETES, CASAS DE SUCOS E CASAS DE SHOW FORNEÇAM ÁGUA FILTRADA GRATUITAMENTE AOS SEUS CLIENTES.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-103228', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/103228_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"103228","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2021&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/103228","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=103228","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/103228_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '202', 2020, 'INSTITUI, NO CALENDÁRIO OFICIAL DE EVENTOS DO MUNICÍPIO DO RECIFE, "A SEMANA DA NÃO VIOLÊNCIA ATIVA".', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-102469', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/102469_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"102469","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2020&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/102469","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=102469","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/102469_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '201', 2020, 'MODIFICA O INCISO IV DO ART. 2º DA LEI MUNICIPAL Nº 16.192, DE 5 DE JUNHO DE 1996, QUE REGULAMENTA O ART. 177 DA LEI ORGÂNICA DO RECIFE, ESTABELECENDO NORMAS PARA DECLARAÇÃO DE UTILIDADE PÚBLICA E DÁ OUTRAS PROVIDÊNCIAS.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-102468', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/102468_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"102468","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2020&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/102468","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=102468","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/102468_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '198', 2020, 'INSTITUI AS BASES PARA A ELABORAÇÃO DA “POLÍTICA MUNICIPAL DE PROMOÇÃO DOS DIREITOS DOS MIGRANTES E REFUGIADOS” NO MUNICÍPIO DO RECIFE.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-102360', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/102360_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"102360","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2020&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/102360","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=102360","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/102360_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '191', 2020, 'DISPÕE SOBRE OS PONTOS DE APOIO PARA TRABALHADORES DE APLICATIVOS DE ENTREGA E DE TRANSPORTE INDIVIDUAL PRIVADO DE PASSAGEIROS NAS REGIÕES POLÍTICO-ADMINISTRATIVAS (RPAS) DO MUNICÍPIO DO RECIFE', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-102081', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/102081_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"102081","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2020&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/102081","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=102081","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/102081_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '117', 2020, 'DECLARA DE UTILIDADE PÚBLICA, NO ÂMBITO DO MUNICÍPIO DO RECIFE, A FEDERAÇÃO DE ÓRGÃOS PARA ASSISTÊNCIA SOCIAL E EDUCACIONAL (FASE).', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-97300', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/97300_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"97300","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2020&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/97300","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=97300","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/97300_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '79', 2020, 'ESTABELECE A OBRIGATORIEDADE DE OS BOLETINS EPIDEMIOLÓGICOS E OS DEMAIS DOCUMENTOS OFICIAIS DO MUNICÍPIO DO RECIFE APRESENTAREM INFORMAÇÕES DETALHADAS SOBRE A OCORRÊNCIA E A EVOLUÇÃO DO NOVO CORONAVÍRUS (COVID-19).', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-95832', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/95832_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"95832","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2020&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/95832","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=95832","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/95832_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '58', 2020, 'DETERMINA QUE ESTABELECIMENTOS PRIVADOS INSTALADOS NO MUNICÍPIO DO RECIFE CONSIDERADOS COMO DE SERVIÇOS ESSENCIAIS FORNEÇAM MÁSCARAS, ÁLCOOL 70% E DISPONHAM DE PIA COM ÁGUA E SABÃO EM LOCAL DE FÁCIL ACESSO AOS SEUS FUNCIONÁRIOS.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-95343', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/95343_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"95343","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2020&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/95343","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=95343","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/95343_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '20', 2020, 'INSTITUI A OBRIGATORIEDADE DA LIBERAÇÃO DA CATRACA OU ROLETA DE ACESSO PARA AS CRIANÇAS DE ATÉ 6 (SEIS) ANOS DE IDADE INCOMPLETOS USUÁRIAS DO TRANSPORTE PÚBLICO GRATUITO NO MUNICÍPIO DO RECIFE.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-94378', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/94378_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"94378","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2020&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/94378","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=94378","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/94378_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '329', 2019, 'INSTITUI, NO CALENDÁRIO OFICIAL DE EVENTOS DA CIDADE DO RECIFE, O “DIA MUNICIPAL EM HOMENAGEM AO POVO PALESTINO”', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-93772', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/93772_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"93772","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2019&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/93772","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=93772","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/93772_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"},{"description":"Parlamentar","firstAuthor":true,"title":"Jayme Asfora"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '259', 2019, 'ALTERA O ANEXO III DA LEI MUNICIPAL Nº 18.509, DE 23 DE JULHO DE 2018, QUE INSTITUI O PLANO DE CARGOS, CARREIRA, DESENVOLVIMENTO E VENCIMENTOS - PCCDV DO GRUPO OCUPACIONAL DE APOIO AO MAGISTÉRIO, E DÁ OUTRAS PROVIDÊNCIAS.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-91199', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/91199_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"91199","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2019&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/91199","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=91199","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/91199_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '206', 2019, 'OBRIGA TÁXIS E TODOS OS TRANSPORTES REMUNERADOS PRIVADOS INDIVIDUAIS DE PASSAGEIROS INTERMEDIADOS POR PLATAFORMAS DIGITAIS, NO ÂMBITO DO MUNICÍPIO DO RECIFE, A DIVULGAR CARTAZ QUE ESTIMULE DENÚNCIA CONTRA RACISMO, HOMOFOBIA E CRIMES CONTRA A DIGNIDADE SEXUAL COMETIDOS DENTRO DESSES TRANSPORTES.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-89479', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/89479_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"89479","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2019&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/89479","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=89479","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/89479_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '205', 2019, 'ALTERA A LEI MUNICIPAL Nº 17.765, DE 4 DE JANEIRO DE 2012, E DÁ OUTRAS PROVIDÊNCIAS.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-89477', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/89477_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"89477","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2019&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/89477","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=89477","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/89477_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '160', 2019, 'ASSEGURA, NOS LOCAIS QUE ESPECIFICA, O DIREITO AO USO DE INDUMENTÁRIA, OBJETOS E PINTURAS CORPORAIS E AO MODO DE SE PORTAR TÍPICOS E TRADICIONAIS DE UM POVO OU COMUNIDADE.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-88256', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/88256_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"88256","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2019&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/88256","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=88256","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/88256_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '134', 2018, 'CRIA O DOSSIÊ MULHER RECIFENSE NA FORMA QUE ESPECIFICA E DÁ OUTRAS PROVIDÊNCIAS', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-81054', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/81054_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"81054","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2018&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/81054","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=81054","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/81054_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '133', 2018, 'INCLUI O DIA DE TEREZA DE BENGUELA E DA MULHER NEGRA NO CALENDÁRIO OFICIAL DO MUNICÍPIO DE RECIFE.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-81053', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/81053_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"81053","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2018&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/81053","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=81053","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/81053_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '396', 2017, 'DISPÕE SOBRE A OBRIGATORIEDADE DA CONSTRUÇÃO OU ADAPTAÇÃO DE FRALDÁRIOS ACESSÍVEIS A FREQUENTADORES MASCULINOS EM SHOPPING CENTERS E ESTABELECIMENTOS SIMILARES, E DÁ OUTRAS PROVIDÊNCIAS.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-76160', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/76160_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"76160","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2017&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/76160","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=76160","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/76160_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '371', 2017, 'INSTITUI NO CALENDÁRIO OFICIAL DO RECIFE A SEMANA MUNICIPAL DA VIVÊNCIA E PRÁTICA DA CULTURA AFRO-INDÍGENA PERNAMBUCANA.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-75424', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/75424_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"75424","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2017&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/75424","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=75424","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/75424_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '340', 2017, 'INSTITUI, NO CALENDÁRIO OFICIAL DE EVENTOS DO MUNICÍPIO DO RECIFE, O "DIA MUNICIPAL DA COMUNICAÇÃO POPULAR".', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-74239', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/74239_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"74239","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2017&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/74239","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=74239","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/74239_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '276', 2017, 'DISPÕE SOBRE A OBRIGATORIEDADE DA INSTALAÇÃO, NO TRANSPORTE COLETIVO, DE ANÚNCIO SONORO DE PARADA DENTRO DOS VEÍCULOS DE PASSAGEIROS E DOS ÔNIBUS QUE CIRCULAM NO MUNICÍPIO DO RECIFE.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-72057', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/72057_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"72057","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2017&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/72057","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=72057","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/72057_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '273', 2017, 'DISPÕE SOBRE A OBRIGATORIEDADE DE PAINÉIS ELETRÔNICOS COM RECURSO DE CHAMADA POR VOZ EM ESTABLECIMENTOS PRIVADOS, QUE FAÇAM USO DESSE RECURSO NA CIDADE DO RECIFE.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-72030', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/72030_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"72030","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2017&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/72030","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=72030","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/72030_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '227', 2017, 'ACRESCENTA O ART. 1º-A À LEI MUNICIPAL Nº 18.067, DE 6 DE NOVEMBRO DE 2014, QUE DISPÕE SOBRE AS FARMÁCIAS DA CIDADE DO RECIFE QUE PARTICIPAM DO PROGRAMA FARMÁCIA POPULAR,DO GOVERNO FEDERAL, PARA INCLUIR PENALIDADES AO DESCUMPRIMENTO DA NORMA.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-70716', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/70716_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"70716","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2017&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/70716","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=70716","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/70716_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb),
    ('PL', '185', 2017, 'MODIFICA O ART. 1º E ACRESCENTA O ART. 1º - A À LEI MUNICIPAL Nº 16.709, DE 12 DE NOVEMBRO DE 2001, QUE DISPÕE SOBRE A AUTORIZAÇÃO DOS VEÍCULOS COLETIVOS, INTEGRANTES DA EMTU, NO MUNICÍPIO DO RECIFE A PARAREM FORA DOS PONTOS PRÉ - DETERMINADOS, NO HORÁRIO ENTRE 23H00H E 05:00H, E DÁ OUTRAS DISPOSIÇÕES.', 'Câmara Municipal do Recife - OpenLegis', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-69907', 'https://publico.recife.pe.leg.br/sapl_documentos/materia/69907_texto_integral.pdf', 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507', 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507', '{"source":"Câmara Municipal do Recife - OpenLegis","data_real":true,"fluxo":"Legislacao full-site","curation_batch_id":"ivan-moraes-recife-openlegis-lote-a-20260507","coverage_id":"ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507","coverage_scope":"inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"openlegis_author_code":"208","openlegis_author_name":"Ivan Moraes","openlegis_type_code":10,"openlegis_id":"69907","official_api_url":"https://publico.recife.pe.leg.br/@@materias?ano=2017&tipo=10","official_item_url":"https://publico.recife.pe.leg.br/@@materias/69907","official_remote_url":"https://publico.recife.pe.leg.br/consultas/materia/materia_mostrar_proc?cod_materia=69907","official_pdf_url":"https://publico.recife.pe.leg.br/sapl_documentos/materia/69907_texto_integral.pdf","authorship":[{"description":"Parlamentar","firstAuthor":true,"title":"Ivan Moraes"}],"autoria_principal_verificada":true,"fonte_oficial_verificada_em":"2026-05-07T23:03:59.546Z"}'::jsonb);

WITH target AS (
  SELECT c.id AS candidato_id
  FROM candidatos c
  WHERE c.slug = 'ivan-moraes' AND c.publicavel = true
)
INSERT INTO projetos_lei (
  candidato_id,
  tipo,
  numero,
  ano,
  ementa,
  fonte,
  proposicao_id_api,
  url_inteiro_teor,
  coverage_id,
  coverage_scope,
  metadata
)
SELECT
  target.candidato_id,
  seed.tipo,
  seed.numero,
  seed.ano,
  seed.ementa,
  seed.fonte,
  seed.proposicao_id_api,
  seed.url_inteiro_teor,
  seed.coverage_id,
  seed.coverage_scope,
  seed.metadata
FROM target
CROSS JOIN _seed_ivan_moraes_recife_openlegis_lote_a AS seed
ON CONFLICT (candidato_id, proposicao_id_api) DO UPDATE SET
  tipo = EXCLUDED.tipo,
  numero = EXCLUDED.numero,
  ano = EXCLUDED.ano,
  ementa = EXCLUDED.ementa,
  fonte = EXCLUDED.fonte,
  url_inteiro_teor = EXCLUDED.url_inteiro_teor,
  coverage_id = EXCLUDED.coverage_id,
  coverage_scope = EXCLUDED.coverage_scope,
  metadata = COALESCE(projetos_lei.metadata, '{}'::jsonb) || EXCLUDED.metadata
WHERE projetos_lei.coverage_id IS NULL
   OR projetos_lei.coverage_id = EXCLUDED.coverage_id;

DO $$
DECLARE
  cand_id uuid;
  total_count int;
  target_count int;
  coverage_count int;
  wrong_lme_count int;
  rejected_present_count int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'ivan-moraes' AND publicavel = true;

  IF cand_id IS NULL THEN
    RAISE NOTICE 'ivan-moraes: pos-condicao pulada porque candidato publico nao existe neste banco local/CI minimo';
    RETURN;
  END IF;

  SELECT count(*) INTO total_count FROM projetos_lei WHERE candidato_id = cand_id;
  SELECT count(*) INTO target_count FROM projetos_lei WHERE candidato_id = cand_id AND proposicao_id_api IN ('RECIFE-OPENLEGIS:208:TIPO-10:ID-157520', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-157211', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-155745', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-147937', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-145707', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-138554', 'RECIFE-OPENLEGIS:208:TIPO-14:ID-141210', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-133292', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-131874', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-130241', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-126710', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-125852', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-125644', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-125043', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-124854', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-123553', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-123452', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-121909', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-117165', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-115896', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-107171', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-105695', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-105573', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-105360', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-103942', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-103230', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-103229', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-103228', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-102469', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-102468', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-102360', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-102081', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-97300', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-95832', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-95343', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-94378', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-93772', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-91199', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-89479', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-89477', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-88256', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-81054', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-81053', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-76160', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-75424', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-74239', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-72057', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-72030', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-70716', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-69907');
  SELECT count(*) INTO coverage_count
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id = 'ivan-moraes-recife-openlegis-autoria-principal-ampliado-parcial-20260507'
    AND coverage_scope = 'inventario_ampliado_parcial_recife_openlegis_autoria_principal_2017_2024_20260507';
  SELECT count(*) INTO wrong_lme_count FROM legislacao_mandato_executivo WHERE candidato_id = cand_id;
  SELECT count(*) INTO rejected_present_count
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND proposicao_id_api IN ('RECIFE-OPENLEGIS:208:TIPO-10:ID-105154', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-105493', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-112905', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-116304', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-123775', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-123776', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-126837', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-127066', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-128485', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-137906', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-63402', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-69918', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-70722', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-71590', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-76256', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-81052', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-81055', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-81062', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-81988', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-82135', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-82440', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-82623', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-84204', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-85753', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-92955', 'RECIFE-OPENLEGIS:208:TIPO-10:ID-93785', 'RECIFE-OPENLEGIS:208:TIPO-2:ID-102359', 'RECIFE-OPENLEGIS:208:TIPO-2:ID-103613', 'RECIFE-OPENLEGIS:208:TIPO-2:ID-104166', 'RECIFE-OPENLEGIS:208:TIPO-2:ID-104651', 'RECIFE-OPENLEGIS:208:TIPO-2:ID-104890', 'RECIFE-OPENLEGIS:208:TIPO-2:ID-104891', 'RECIFE-OPENLEGIS:208:TIPO-2:ID-105566', 'RECIFE-OPENLEGIS:208:TIPO-2:ID-106076', 'RECIFE-OPENLEGIS:208:TIPO-2:ID-112515', 'RECIFE-OPENLEGIS:208:TIPO-2:ID-135411', 'RECIFE-OPENLEGIS:208:TIPO-2:ID-65843', 'RECIFE-OPENLEGIS:208:TIPO-2:ID-94520', 'RECIFE-OPENLEGIS:208:TIPO-2:ID-98301', 'RECIFE-OPENLEGIS:208:TIPO-6:ID-102334', 'RECIFE-OPENLEGIS:208:TIPO-6:ID-102458', 'RECIFE-OPENLEGIS:208:TIPO-6:ID-113215', 'RECIFE-OPENLEGIS:208:TIPO-6:ID-123213', 'RECIFE-OPENLEGIS:208:TIPO-6:ID-129307', 'RECIFE-OPENLEGIS:208:TIPO-6:ID-129308', 'RECIFE-OPENLEGIS:208:TIPO-6:ID-138424', 'RECIFE-OPENLEGIS:208:TIPO-6:ID-144636', 'RECIFE-OPENLEGIS:208:TIPO-6:ID-148503', 'RECIFE-OPENLEGIS:208:TIPO-6:ID-150122', 'RECIFE-OPENLEGIS:208:TIPO-6:ID-78525', 'RECIFE-OPENLEGIS:208:TIPO-6:ID-94788', 'RECIFE-OPENLEGIS:208:TIPO-6:ID-94789', 'RECIFE-OPENLEGIS:208:TIPO-6:ID-94790', 'RECIFE-OPENLEGIS:208:TIPO-6:ID-96941');

  IF target_count <> 50 THEN
    RAISE EXCEPTION 'Pos-apply ivan-moraes: esperadas 50 rows alvo em projetos_lei, encontradas %', target_count;
  END IF;

  IF coverage_count <> 50 THEN
    RAISE EXCEPTION 'Pos-apply ivan-moraes: esperadas 50 rows com coverage_id/scope alvo, encontradas %', coverage_count;
  END IF;

  IF total_count <> 50 THEN
    RAISE EXCEPTION 'Pos-apply ivan-moraes: total projetos_lei esperado 50, encontrado %', total_count;
  END IF;

  IF wrong_lme_count <> 0 THEN
    RAISE EXCEPTION 'Pos-apply ivan-moraes: legislacao_mandato_executivo deveria permanecer 0, encontrado %', wrong_lme_count;
  END IF;

  IF rejected_present_count <> 0 THEN
    RAISE EXCEPTION 'Pos-apply ivan-moraes: % rejected rows foram inseridas indevidamente', rejected_present_count;
  END IF;

  RAISE NOTICE 'Pos-apply ivan-moraes OpenLegis Lote A: projetos_lei=% coverage_rows=%', total_count, coverage_count;
END $$;
