-- ============================================
-- Legislacao full-site: tarcisio-gov-sp / SP ALESP / legislacao_mandato_executivo
-- Seed ampliado parcial: Lote A normas de 2026 sancionadas por Tarcisio de Freitas
-- ============================================
-- Fonte oficial: Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao
-- Artefato: fonte interna de curadoria
-- Coverage: tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506
-- Esta migration NAO escreve em projetos_lei.
-- Esta migration NAO escreve em historico_politico.
-- ============================================

DO $$
DECLARE
  cand_id uuid;
  lme_total int;
  target_count int;
  mandato_count int;
  projetos_count int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'tarcisio-gov-sp';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'tarcisio-gov-sp: candidato ausente neste banco local/CI minimo; seed LME SP ALESP pulado';
    RETURN;
  END IF;

  SELECT count(*) INTO lme_total
  FROM legislacao_mandato_executivo
  WHERE candidato_id = cand_id;

  SELECT count(*) INTO target_count
  FROM legislacao_mandato_executivo
  WHERE candidato_id = cand_id
    AND metadata->>'coverage_id' = 'tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506';

  SELECT count(*) INTO projetos_count
  FROM projetos_lei
  WHERE candidato_id = cand_id;

  IF lme_total NOT IN (1, 62) THEN
    RAISE EXCEPTION 'Pre-condicao tarcisio-gov-sp: esperada 1 row legado atual ou 62 rows idempotentes em LME, encontradas %', lme_total;
  END IF;

  IF lme_total = 62 AND target_count <> 61 THEN
    RAISE EXCEPTION 'Pre-condicao tarcisio-gov-sp: 62 rows LME existentes, mas apenas % com coverage_id alvo', target_count;
  END IF;

  IF projetos_count <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao tarcisio-gov-sp: projetos_lei deve permanecer 0 rows, encontrado %', projetos_count;
  END IF;

  SELECT count(*) INTO mandato_count
  FROM historico_politico hp
  WHERE hp.candidato_id = cand_id
    AND COALESCE(hp.tipo_evento, 'mandato') = 'mandato'
    AND hp.cargo_canonico = 'Governador'
    AND upper(coalesce(hp.estado, '')) = 'SP'
    AND coalesce(hp.periodo_inicio, 9999) <= 2026
    AND coalesce(hp.periodo_fim, 9999) >= 2026;

  IF mandato_count < 1 THEN
    RAISE EXCEPTION 'Pre-condicao tarcisio-gov-sp: mandato Governador/SP compativel com 2026 nao encontrado';
  END IF;
END $$;

WITH seed_rows(tipo_relacao, esfera, uf_norma, municipio_norma, tipo_norma, numero, ano, data_norma, ementa, signatario, autoridade_papel, fonte_primaria_url, fonte_primaria_titulo, fonte_tramitacao_url, identificador_fonte, metadata) AS (
  VALUES
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.447', 2026, '2026-04-28', 'Altera a Lei nº 7.964, de 16 de julho de 1992 , que dá nova denominação ao Fundo de Expansão Agropecuária, define seus objetivos, dispõe sobre a aplicação dos seus recursos e dá providências correlatas.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18447-28.04.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212505', 'ALESP-SP-TARCISIO:212505', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18447_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212505","alesp_norma_url":"https://www.al.sp.gov.br/norma/212505","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212505","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.446', 2026, '2026-04-14', 'Inclui no Calendário Oficial de Eventos do Estado o espetáculo Paixão de Cristo, em Cubatão.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18446-14.04.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212467', 'ALESP-SP-TARCISIO:212467', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18446_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212467","alesp_norma_url":"https://www.al.sp.gov.br/norma/212467","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212467","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.445', 2026, '2026-04-14', 'Institui o "Dia Estadual do Cavaleiro".', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18445-14.04.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212466', 'ALESP-SP-TARCISIO:212466', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18445_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212466","alesp_norma_url":"https://www.al.sp.gov.br/norma/212466","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212466","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.444', 2026, '2026-04-14', 'Denomina "Benedito Olympio Leite (Ipojucã)" a Escola Estadual Jardim Paraíso, em Boituva.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18444-14.04.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212465', 'ALESP-SP-TARCISIO:212465', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18444_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212465","alesp_norma_url":"https://www.al.sp.gov.br/norma/212465","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212465","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei complementar', '1.440', 2026, '2026-04-14', 'Dispõe sobre a criação de cargos de Promotor de Justiça na Parte Permanente do Quadro do Ministério Público do Estado de São Paulo.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei.complementar/2026/lei.complementar-1440-14.04.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212464', 'ALESP-SP-TARCISIO:212464', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_complementar_1440_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212464","alesp_norma_url":"https://www.al.sp.gov.br/norma/212464","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212464","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.443', 2026, '2026-04-02', 'Dispõe sobre o plano de carreira dos integrantes das carreiras policiais civis do Estado de São Paulo.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18443-02.04.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212444', 'ALESP-SP-TARCISIO:212444', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18443_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212444","alesp_norma_url":"https://www.al.sp.gov.br/norma/212444","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212444","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.442', 2026, '2026-04-02', 'Dispõe sobre efetivo, regime jurídico e regras gerais de promoção dos militares do Estado de São Paulo e dá providências correlatas.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18442-02.04.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212443', 'ALESP-SP-TARCISIO:212443', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18442_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212443","alesp_norma_url":"https://www.al.sp.gov.br/norma/212443","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212443","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.441', 2026, '2026-04-02', 'Dispõe sobre a reclassificação dos vencimentos dos integrantes da carreira de Delegado de Polícia, das demais carreiras policiais civis e da Polícia Militar, na forma que especifica.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18441-02.04.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212442', 'ALESP-SP-TARCISIO:212442', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18441_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212442","alesp_norma_url":"https://www.al.sp.gov.br/norma/212442","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212442","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.440', 2026, '2026-04-02', 'Altera a Lei Complementar nº 1.280, de 13 de janeiro de 2016 , que institui a Diária Especial por Jornada Extraordinária de Trabalho Policial Civil - DEJEC.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18440-02.04.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212441', 'ALESP-SP-TARCISIO:212441', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18440_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212441","alesp_norma_url":"https://www.al.sp.gov.br/norma/212441","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212441","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.439', 2026, '2026-04-01', 'Autoriza o Poder Executivo a contratar operações de crédito e a prestar contragarantias aos projetos que especifica, e dá providências correlatas.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18439-01.04.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212423', 'ALESP-SP-TARCISIO:212423', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18439_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212423","alesp_norma_url":"https://www.al.sp.gov.br/norma/212423","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212423","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.438', 2026, '2026-03-25', 'Declara de utilidade pública a Associação Guaratinguetaense de Engenheiros e Arquitetos - AGEA, com sede em Guaratinguetá.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18438-25.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212412', 'ALESP-SP-TARCISIO:212412', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18438_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212412","alesp_norma_url":"https://www.al.sp.gov.br/norma/212412","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212412","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.437', 2026, '2026-03-25', 'Declara de utilidade pública o Coletivo 302, com sede no Município de Cubatão.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18437-25.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212411', 'ALESP-SP-TARCISIO:212411', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18437_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212411","alesp_norma_url":"https://www.al.sp.gov.br/norma/212411","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212411","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.436', 2026, '2026-03-25', 'Altera a Lei nº 17.383, de 5 de julho de 2021 , que dispõe sobre a criação de unidades regionais de saneamento básico, com fundamento nos artigos 2º, inciso XIV, e 3º, inciso VI, alínea "b", da Lei federal nº 11.445, de 5 de janeiro de 2007, e dá providências correlatas.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18436-25.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212410', 'ALESP-SP-TARCISIO:212410', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18436_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212410","alesp_norma_url":"https://www.al.sp.gov.br/norma/212410","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212410","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.435', 2026, '2026-03-25', 'Declara de utilidade pública a Sociedade Amigos de Bairro do Conjunto Habitacional Jardim Sapopemba, com sede na Capital.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18435-25.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212409', 'ALESP-SP-TARCISIO:212409', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18435_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212409","alesp_norma_url":"https://www.al.sp.gov.br/norma/212409","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212409","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.434', 2026, '2026-03-25', 'Declara de utilidade pública a Associação Amigos do XV de Piracicaba - AAXV, com sede naquele Município.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18434-25.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212408', 'ALESP-SP-TARCISIO:212408', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18434_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212408","alesp_norma_url":"https://www.al.sp.gov.br/norma/212408","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212408","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.433', 2026, '2026-03-25', 'Declara de utilidade pública a Associação Toque do Futuro Voleibol - ATFV, com sede em Piracicaba.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18433-25.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212407', 'ALESP-SP-TARCISIO:212407', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18433_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212407","alesp_norma_url":"https://www.al.sp.gov.br/norma/212407","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212407","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.432', 2026, '2026-03-25', 'Declara de utilidade pública a Associação Fábrica de Saúde, Esporte e Cultura, com sede em Paulínia.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18432-25.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212406', 'ALESP-SP-TARCISIO:212406', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18432_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212406","alesp_norma_url":"https://www.al.sp.gov.br/norma/212406","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212406","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.431', 2026, '2026-03-25', 'Declara de utilidade pública a Associação de Defesa Animal de Pereira Barreto, com sede naquele Município.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18431-25.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212405', 'ALESP-SP-TARCISIO:212405', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18431_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212405","alesp_norma_url":"https://www.al.sp.gov.br/norma/212405","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212405","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.430', 2026, '2026-03-25', 'Declara de utilidade pública a Associação Espaço Cidadania, Cultura e Arte (ECCART), com sede em Jales.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18430-25.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212404', 'ALESP-SP-TARCISIO:212404', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18430_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212404","alesp_norma_url":"https://www.al.sp.gov.br/norma/212404","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212404","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.429', 2026, '2026-03-13', 'Altera a Lei nº 17.431, de 14 de outubro de 2021 , para estabelecer o Protocolo de Combate à Violência contra a Mulher na Universidade.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18429-13.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212358', 'ALESP-SP-TARCISIO:212358', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18429_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212358","alesp_norma_url":"https://www.al.sp.gov.br/norma/212358","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212358","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.427', 2026, '2026-03-13', 'Institui o Protocolo Antirracista, determinando aos estabelecimentos comerciais de grande circulação de pessoas que implementem medidas de prevenção, conscientização e acolhimento de vítimas em situação de racismo no âmbito do Estado de São Paulo.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18427-13.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212356', 'ALESP-SP-TARCISIO:212356', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18427_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212356","alesp_norma_url":"https://www.al.sp.gov.br/norma/212356","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212356","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.426', 2026, '2026-03-13', 'Altera a redação da Lei nº 6.757, de 15 de março de 1990 , para tornar obrigatória a execução vocal semanal do Hino Nacional em todos os estabelecimentos públicos e privados de ensino fundamental e ensino médio no Estado de São Paulo.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18426-13.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212355', 'ALESP-SP-TARCISIO:212355', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18426_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212355","alesp_norma_url":"https://www.al.sp.gov.br/norma/212355","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212355","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.425', 2026, '2026-03-13', 'Garante o direito à amamentação e ao aleitamento materno em creches e estabelece diretrizes ao Poder Executivo Estadual para o apoio aos municípios na formulação e implementação de ações de proteção e incentivo à amamentação e ao aleitamento materno em creches no âmbito do Estado de São Paulo.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18425-13.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212354', 'ALESP-SP-TARCISIO:212354', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18425_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212354","alesp_norma_url":"https://www.al.sp.gov.br/norma/212354","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212354","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.424', 2026, '2026-03-13', 'Autoriza a criação do Programa de Combate aos Crimes de Pedofilia e Exploração Sexual Infantil no âmbito das escolas estaduais e dá outras providências.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18424-13.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212353', 'ALESP-SP-TARCISIO:212353', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18424_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212353","alesp_norma_url":"https://www.al.sp.gov.br/norma/212353","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212353","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.423', 2026, '2026-03-13', 'Disciplina a celebração de contratos de cessão onerosa de direito à nomeação de eventos e equipamentos públicos estaduais - "Naming Rights".', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18423-13.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212352', 'ALESP-SP-TARCISIO:212352', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18423_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212352","alesp_norma_url":"https://www.al.sp.gov.br/norma/212352","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212352","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.422', 2026, '2026-03-13', 'Autoriza o Poder Executivo a criar o Programa Estadual para o Incentivo à Utilização da Musicoterapia como tratamento terapêutico complementar de pessoas com deficiência, síndromes e/ou Transtorno do Espectro Autista - TEA.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18422-13.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212351', 'ALESP-SP-TARCISIO:212351', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18422_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212351","alesp_norma_url":"https://www.al.sp.gov.br/norma/212351","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212351","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.421', 2026, '2026-03-13', 'Institui a Semana Estadual do Rádio, no Estado de São Paulo.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18421-13.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212350', 'ALESP-SP-TARCISIO:212350', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18421_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212350","alesp_norma_url":"https://www.al.sp.gov.br/norma/212350","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212350","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.420', 2026, '2026-03-13', 'Dispõe sobre o combate ao desperdício de alimentos e a doação de excedentes de refeições prontas para o consumo e dá outras providências.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18420-13.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212349', 'ALESP-SP-TARCISIO:212349', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18420_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212349","alesp_norma_url":"https://www.al.sp.gov.br/norma/212349","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212349","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.419', 2026, '2026-03-13', 'Dispõe sobre o estabelecimento de Perímetro de Proteção Escolar no entorno das unidades da rede estadual de ensino, e dá outras providências.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18419-13.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212348', 'ALESP-SP-TARCISIO:212348', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18419_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212348","alesp_norma_url":"https://www.al.sp.gov.br/norma/212348","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212348","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.418', 2026, '2026-03-13', 'Altera as Leis nº 15.213, de 19 de novembro de 2013, nº 15.567, de 30 de outubro de 2014, nº 17.386, de 14 de julho de 2021, nº 17.989, de 22 de julho de 2024, nº 18.067, de 18 de dezembro de 2024, nº 18.147, de 26 de março de 2025, e nº 18.353, de 15 de dezembro de 2025, que autorizaram o Poder Executivo a contratar operações de crédito, e a Lei nº 7.964, de 16 de julho de 1992 , que dispõe sobre o Fundo de Expansão da Agropecuária e da Pesca.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18418-13.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212344', 'ALESP-SP-TARCISIO:212344', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18418_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212344","alesp_norma_url":"https://www.al.sp.gov.br/norma/212344","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212344","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei complementar', '1.439', 2026, '2026-03-13', 'Autoriza o Poder Executivo a assegurar a prestação de serviços de escolta e segurança pessoal a autoridades e ex-autoridades do Estado de São Paulo, bem como a seus familiares, em razão do risco inerente às funções públicas exercidas.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei.complementar/2026/lei.complementar-1439-13.03.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212347', 'ALESP-SP-TARCISIO:212347', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_complementar_1439_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212347","alesp_norma_url":"https://www.al.sp.gov.br/norma/212347","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212347","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.417', 2026, '2026-02-26', 'Declara de utilidade pública a Associação Fórum Permanente de Desenvolvimento Econômico e Social de Osvaldo Cruz - MULTIPLIC, com sede naquele Município.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18417-26.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212281', 'ALESP-SP-TARCISIO:212281', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18417_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212281","alesp_norma_url":"https://www.al.sp.gov.br/norma/212281","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212281","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.416', 2026, '2026-02-26', 'Declara de utilidade pública a Associação Paraguaçuense de Combate ao Câncer de Paraguaçu Paulista - APCC, com sede naquele Município.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18416-26.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212283', 'ALESP-SP-TARCISIO:212283', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18416_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212283","alesp_norma_url":"https://www.al.sp.gov.br/norma/212283","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212283","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.415', 2026, '2026-02-26', 'Declara de utilidade pública a filial da Beneficência Nipo-Brasileira de São Paulo, Hospital de Itapetininga Dr. Léo Orsi Bernardes - HLOB, com sede naquele Município.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18415-26.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212285', 'ALESP-SP-TARCISIO:212285', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18415_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212285","alesp_norma_url":"https://www.al.sp.gov.br/norma/212285","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212285","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.414', 2026, '2026-02-26', 'Declara de utilidade pública o Instituto Verus, com sede em Sorocaba.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18414-26.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212286', 'ALESP-SP-TARCISIO:212286', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18414_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212286","alesp_norma_url":"https://www.al.sp.gov.br/norma/212286","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212286","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.413', 2026, '2026-02-26', 'Declara de utilidade pública o Instituto Recomeçar em Amor, com sede em São José do Rio Preto.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18413-26.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212288', 'ALESP-SP-TARCISIO:212288', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18413_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212288","alesp_norma_url":"https://www.al.sp.gov.br/norma/212288","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212288","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.412', 2026, '2026-02-26', 'Denomina "Carlos Meinberg" o dispositivo de acesso e retorno com viaduto localizado no km 414 + 400m da Rodovia Brigadeiro Faria Lima - SP 326, em Barretos.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18412-26.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212290', 'ALESP-SP-TARCISIO:212290', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18412_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212290","alesp_norma_url":"https://www.al.sp.gov.br/norma/212290","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212290","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.411', 2026, '2026-02-26', 'Denomina "Deputado Campos Machado" o dispositivo de acesso e retorno com viaduto SPD 255/255, localizado no km 255,370 da Rodovia João Mellão - SP 255, em Avaré.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18411-26.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212289', 'ALESP-SP-TARCISIO:212289', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18411_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212289","alesp_norma_url":"https://www.al.sp.gov.br/norma/212289","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212289","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.410', 2026, '2026-02-26', 'Institui o "Dia do Desporto Escolar", incluindo-o no Calendário Oficial do Estado, e dá outras providências.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18410-26.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212287', 'ALESP-SP-TARCISIO:212287', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18410_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212287","alesp_norma_url":"https://www.al.sp.gov.br/norma/212287","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212287","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.409', 2026, '2026-02-26', 'Denomina "Geraldo Sarmento" a passarela PAS 462/294, localizada no km 462 + 470m da Rodovia Comandante João Ribeiro de Barros - SP 294, em Marília.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18409-26.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212284', 'ALESP-SP-TARCISIO:212284', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18409_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212284","alesp_norma_url":"https://www.al.sp.gov.br/norma/212284","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212284","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.408', 2026, '2026-02-26', 'Denomina "Milton Tédde" o dispositivo de acesso e retorno com passagem inferior, código SPD 464/294, localizado no km 464 + 150m da Rodovia Comandante João Ribeiro de Barros - SP 294, em Marília.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18408-26.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212282', 'ALESP-SP-TARCISIO:212282', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18408_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212282","alesp_norma_url":"https://www.al.sp.gov.br/norma/212282","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212282","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.407', 2026, '2026-02-26', 'Dá denominação de "Protético Geraldo Bolsonaro" ao viaduto de transposição, codificado VDT 028/150, localizado no km 27,750 da Rodovia Anchieta - SP 150, no município de São Bernardo do Campo.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18407-26.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212280', 'ALESP-SP-TARCISIO:212280', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18407_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212280","alesp_norma_url":"https://www.al.sp.gov.br/norma/212280","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212280","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.406', 2026, '2026-02-26', 'Denomina "Vereador Vanderlei Voltarelli" o dispositivo de entroncamento em nível de código SPD 073/215, localizado no km 73 + 300m da Rodovia Vicente Botta - SP 215, no município de Santa Cruz das Palmeiras.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18406-26.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212279', 'ALESP-SP-TARCISIO:212279', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18406_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212279","alesp_norma_url":"https://www.al.sp.gov.br/norma/212279","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212279","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.405', 2026, '2026-02-26', 'Denomina "Antônio Ermírio de Moraes" o viaduto localizado no Km 74 + 200m da Rodovia Raposo Tavares - SP 270, no município de Alumínio.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18405-26.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212278', 'ALESP-SP-TARCISIO:212278', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18405_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212278","alesp_norma_url":"https://www.al.sp.gov.br/norma/212278","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212278","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.404', 2026, '2026-02-26', 'Denomina "Prefeito Luiz Gonzaga Lança" a Escola Estadual no Jardim Primavera, em Taguaí.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18404-26.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212276', 'ALESP-SP-TARCISIO:212276', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18404_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212276","alesp_norma_url":"https://www.al.sp.gov.br/norma/212276","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212276","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.403', 2026, '2026-02-18', 'Dispõe sobre o direito à instalação de estação de recarga individual para veículos elétricos em edificações residenciais e comerciais no Estado e dá outras providências.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18403-18.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212240', 'ALESP-SP-TARCISIO:212240', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18403_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212240","alesp_norma_url":"https://www.al.sp.gov.br/norma/212240","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212240","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.402', 2026, '2026-02-13', 'Institui a Política Estadual de Garantia dos Direitos da Pessoa com Câncer e dá outras providências.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18402-13.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212233', 'ALESP-SP-TARCISIO:212233', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18402_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212233","alesp_norma_url":"https://www.al.sp.gov.br/norma/212233","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212233","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.401', 2026, '2026-02-13', 'Institui o Selo "Cidade Mulher Paulista", a ser conferido aos municípios que se destacarem na efetividade das políticas públicas específicas para o bem-estar das mulheres.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18401-13.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212232', 'ALESP-SP-TARCISIO:212232', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18401_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212232","alesp_norma_url":"https://www.al.sp.gov.br/norma/212232","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212232","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.400', 2026, '2026-02-13', 'Declara a música eletrônica como bem de natureza imaterial integrante do patrimônio cultural do Estado.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18400-13.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212231', 'ALESP-SP-TARCISIO:212231', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18400_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212231","alesp_norma_url":"https://www.al.sp.gov.br/norma/212231","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212231","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.399', 2026, '2026-02-13', 'Institui o "Selo Empresa Amiga do Cuidado", destinado a reconhecer empresas que abonem faltas de seus empregados e empregadas para acompanhamento de filhos, tutelados ou pessoas sob sua responsabilidade em atendimentos de saúde ou compromissos escolares.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18399-13.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212230', 'ALESP-SP-TARCISIO:212230', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18399_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212230","alesp_norma_url":"https://www.al.sp.gov.br/norma/212230","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212230","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.398', 2026, '2026-02-07', 'Autoriza o Governo do Estado a fornecer protetores auriculares para crianças com Transtorno do Espectro Autista (TEA) na rede pública do Estado.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18398-07.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212217', 'ALESP-SP-TARCISIO:212217', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18398_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212217","alesp_norma_url":"https://www.al.sp.gov.br/norma/212217","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212217","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.397', 2026, '2026-02-07', 'Autoriza o sepultamento de cães e gatos junto a seus tutores.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18397-07.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212216', 'ALESP-SP-TARCISIO:212216', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18397_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212216","alesp_norma_url":"https://www.al.sp.gov.br/norma/212216","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212216","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.396', 2026, '2026-02-07', 'Declara o Município de Ribeirão Grande "Capital do Rojão".', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18396-07.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212215', 'ALESP-SP-TARCISIO:212215', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18396_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212215","alesp_norma_url":"https://www.al.sp.gov.br/norma/212215","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212215","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.395', 2026, '2026-02-07', 'Institui a Política Estadual de Promoção da Vida e Prevenção do Suicídio, e dá outras providências.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18395-07.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212214', 'ALESP-SP-TARCISIO:212214', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18395_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212214","alesp_norma_url":"https://www.al.sp.gov.br/norma/212214","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212214","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.394', 2026, '2026-02-02', 'Assegura o direito à realização de sessão de cinema adaptada a crianças e adolescentes com Transtorno do Espectro Autista (TEA) e suas famílias.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18394-02.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212188', 'ALESP-SP-TARCISIO:212188', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18394_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212188","alesp_norma_url":"https://www.al.sp.gov.br/norma/212188","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212188","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.393', 2026, '2026-02-02', 'Inclui o inciso VI no artigo 58 da Lei nº 17.293, de 15 de outubro de 2020 .', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18393-02.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212187', 'ALESP-SP-TARCISIO:212187', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18393_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212187","alesp_norma_url":"https://www.al.sp.gov.br/norma/212187","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212187","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.392', 2026, '2026-02-02', 'Institui a Semana Estadual de Conscientização sobre as Doenças Negligenciadas.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18392-02.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212186', 'ALESP-SP-TARCISIO:212186', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18392_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212186","alesp_norma_url":"https://www.al.sp.gov.br/norma/212186","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212186","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.391', 2026, '2026-02-02', 'Declara a "Escola Bíblica Dominical" Patrimônio Cultural Imaterial do Estado.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18391-02.02.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212185', 'ALESP-SP-TARCISIO:212185', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18391_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212185","alesp_norma_url":"https://www.al.sp.gov.br/norma/212185","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212185","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.390', 2026, '2026-01-22', 'Dispõe sobre a obrigatoriedade de as empresas de cartões de crédito ou débito avisarem os consumidores ou clientes sobre a ocorrência de bloqueio do cartão de crédito ou débito.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18390-22.01.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212175', 'ALESP-SP-TARCISIO:212175', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18390_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212175","alesp_norma_url":"https://www.al.sp.gov.br/norma/212175","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212175","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.389', 2026, '2026-01-22', 'Reconhece a expressão cultural "Vira-Lata Caramelo" como de relevante interesse cultural do Estado.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18389-22.01.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212174', 'ALESP-SP-TARCISIO:212174', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18389_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212174","alesp_norma_url":"https://www.al.sp.gov.br/norma/212174","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212174","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb),
    ('lei_sancionada', 'estadual', 'SP', NULL, 'lei', '18.388', 2026, '2026-01-22', 'Reconhece como de relevante interesse cultural do Estado a "Região Turística da Fé" do Vale do Paraíba.', 'TARCÍSIO DE FREITAS', 'titular', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2026/lei-18388-22.01.2026.html', 'Assembleia Legislativa do Estado de Sao Paulo - Repositorio de Legislacao', 'https://www.al.sp.gov.br/norma/212173', 'ALESP-SP-TARCISIO:212173', '{"source":"ALESP","data_real":true,"fluxo":"Legislacao full-site","case_id":"sp_alesp_lei_18388_2026","curation_batch_id":"tarcisio-gov-sp-alesp-governador-lote-a-20260506","coverage_id":"tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506","coverage_scope":"inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506","projetos_lei_mixed":false,"historico_politico_id_inferido_por_data":false,"autoridade_papel_basis":"formula_governador_do_estado_e_assinatura_nominal","alesp_norma_id":"212173","alesp_norma_url":"https://www.al.sp.gov.br/norma/212173","alesp_publicacao_url":"https://www.al.sp.gov.br/norma/publicacao/212173","alesp_index_url":"https://www.al.sp.gov.br/norma/resultados?tipoPesquisa=E&page=0&size=1000&idsTipoNorma=9&idsTipoNorma=2&ano=2026","alesp_index_year":2026,"fonte_oficial_verificada_em":"2026-05-06T11:07:41.343Z"}'::jsonb)
), target AS (
  SELECT
    c.id AS candidato_id,
    seed.*,
    (
      SELECT hp.id
      FROM historico_politico hp
      WHERE hp.candidato_id = c.id
        AND COALESCE(hp.tipo_evento, 'mandato') = 'mandato'
        AND hp.cargo_canonico = 'Governador'
        AND upper(coalesce(hp.estado, '')) = 'SP'
        AND coalesce(hp.periodo_inicio, 9999) <= seed.ano
        AND coalesce(hp.periodo_fim, 9999) >= seed.ano
      ORDER BY hp.periodo_inicio DESC NULLS LAST, hp.id
      LIMIT 1
    ) AS historico_politico_id
  FROM candidatos c
  CROSS JOIN seed_rows seed
  WHERE c.slug = 'tarcisio-gov-sp'
)
INSERT INTO legislacao_mandato_executivo (
  candidato_id,
  historico_politico_id,
  tipo_relacao,
  esfera,
  uf_norma,
  municipio_norma,
  tipo_norma,
  numero,
  ano,
  data_norma,
  ementa,
  signatario,
  autoridade_papel,
  fonte_primaria_url,
  fonte_primaria_titulo,
  fonte_tramitacao_url,
  identificador_fonte,
  metadata
)
SELECT
  target.candidato_id,
  target.historico_politico_id,
  target.tipo_relacao,
  target.esfera,
  target.uf_norma,
  target.municipio_norma,
  target.tipo_norma,
  target.numero,
  target.ano,
  target.data_norma::date,
  target.ementa,
  target.signatario,
  target.autoridade_papel,
  target.fonte_primaria_url,
  target.fonte_primaria_titulo,
  target.fonte_tramitacao_url,
  target.identificador_fonte,
  target.metadata
FROM target
WHERE target.historico_politico_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM legislacao_mandato_executivo lme
    WHERE lme.candidato_id = target.candidato_id
      AND lme.identificador_fonte = target.identificador_fonte
  );

DO $$
DECLARE
  cand_id uuid;
  v_total integer;
  v_scope integer;
  v_projetos integer;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'tarcisio-gov-sp';
  IF cand_id IS NULL THEN
    RAISE NOTICE 'tarcisio-gov-sp: pos-condicao pulada porque candidato nao existe neste banco local/CI minimo';
    RETURN;
  END IF;

  SELECT count(*) INTO v_total
  FROM legislacao_mandato_executivo
  WHERE candidato_id = cand_id;

  SELECT count(*) INTO v_scope
  FROM legislacao_mandato_executivo
  WHERE candidato_id = cand_id
    AND metadata->>'coverage_id' = 'tarcisio-gov-sp-alesp-governador-ampliado-parcial-lote-a-20260506'
    AND metadata->>'coverage_scope' = 'inventario_ampliado_parcial_sp_alesp_governador_2026_lote_a_20260506'
    AND signatario = 'TARCÍSIO DE FREITAS'
    AND autoridade_papel = 'titular';

  SELECT count(*) INTO v_projetos
  FROM projetos_lei
  WHERE candidato_id = cand_id;

  IF v_total <> 62 THEN
    RAISE EXCEPTION 'Pos-condicao tarcisio-gov-sp: esperava 62 rows LME totais, encontrei %', v_total;
  END IF;
  IF v_scope <> 61 THEN
    RAISE EXCEPTION 'Pos-condicao tarcisio-gov-sp: esperava 61 rows com coverage/signatario/titular, encontrei %', v_scope;
  END IF;
  IF v_projetos <> 0 THEN
    RAISE EXCEPTION 'Pos-condicao tarcisio-gov-sp: projetos_lei deveria permanecer 0, encontrei %', v_projetos;
  END IF;
  RAISE NOTICE 'Pos-apply tarcisio-gov-sp SP ALESP Lote A: lme=% coverage=% projetos_lei=%', v_total, v_scope, v_projetos;
END $$;
