-- ============================================
-- Legislacao full-site: joao-capiberibe / Senado / projetos_lei
-- Seed completo do recorte: autoria parlamentar substantiva Senado 2003-2018
-- ============================================
-- Fonte oficial: Senado Federal Dados Abertos
--   https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json
--   https://legis.senado.leg.br/dadosabertos/materia/{codigo}.json
--   https://legis.senado.leg.br/dadosabertos/materia/autoria/{codigo}.json
--   https://www25.senado.leg.br/web/atividade/materias/-/materia/{codigo}
--
-- Artefato de auditoria:
--   fonte interna de curadoria
--
-- Coverage:
--   coverage_id    = joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505
--   coverage_scope = inventario_completo_senado_autoria_substantiva_2003_2018_20260505
--
-- Filtro factual: endpoint senador/3394/autorias.json com
--   IndicadorAutorPrincipal=Sim, siglas substantivas em
--   (PLS, PL, PEC, PLP, PRS, PDL, PDS, PCE), e endpoint
--   materia/autoria/{codigo}.json confirmando CodigoParlamentar=3394
--   com NumOrdemAutor=1. Resultado deste snapshot: 28 rows.
--
-- O recorte e completo apenas para a autoria parlamentar substantiva no Senado
-- retornada pelo endpoint oficial. Nao e inventario completo da vida publica do
-- candidato.
--
-- Esta migration NAO escreve em legislacao_mandato_executivo.
-- Esta migration NAO escreve em historico_politico.
-- Esta migration NAO popula tema, destaque, destaque_motivo nem situacao
--   (campos editoriais/curatoriais, fora do contrato bruto de ingest oficial).
-- Esta migration NAO promove UI/whitelist publica; isso exige novo fechamento.
-- ============================================

DO $$
DECLARE
  cand_id uuid;
  projetos_total int;
  target_count int;
  mandato_senado_count int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'joao-capiberibe';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'joao-capiberibe: candidato ausente neste banco local/CI minimo; seed projetos_lei Senado pulado';
    RETURN;
  END IF;

  SELECT count(*) INTO projetos_total
  FROM projetos_lei
  WHERE candidato_id = cand_id;

  SELECT count(*) INTO target_count
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id = 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505';

  IF projetos_total NOT IN (0, 28) THEN
    RAISE EXCEPTION 'Pre-condicao joao-capiberibe: esperadas 0 rows atuais ou 28 rows alvo idempotentes em projetos_lei, encontradas %', projetos_total;
  END IF;

  IF projetos_total = 28 AND target_count <> 28 THEN
    RAISE EXCEPTION 'Pre-condicao joao-capiberibe: 28 rows existentes, mas apenas % com coverage_id alvo', target_count;
  END IF;

  SELECT count(*) INTO mandato_senado_count
  FROM historico_politico hp
  WHERE hp.candidato_id = cand_id
    AND COALESCE(hp.tipo_evento, 'mandato') = 'mandato'
    AND (hp.cargo ILIKE '%Senador%' OR hp.cargo_canonico = 'Senador')
    AND UPPER(COALESCE(hp.estado, '')) = 'AP'
    AND COALESCE(hp.periodo_inicio, 9999) <= 2018
    AND COALESCE(hp.periodo_fim, 9999) >= 2003;

  IF mandato_senado_count < 1 THEN
    RAISE EXCEPTION 'Pre-condicao joao-capiberibe: mandato Senado/AP 2003-2018 nao encontrado em historico_politico';
  END IF;
END $$;

CREATE TEMP TABLE _seed_joao_capiberibe_senado_lote_a_projetos ON COMMIT DROP AS
SELECT *
FROM (
  VALUES
    ('PEC', '45', 2003, 'Insere novos parágrafos no artigo 212, instituindo o Fundo Nacional da Educação Infantil (FUNAEI) e fundos municipais para atendimento a crianças de até três anos, e dá nova redação ao artigo 239 da Constituição Federal.', 'Senado', '58877', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/58877', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"58877","descricao_identificacao":"PEC 45/2003","data_apresentacao":"2003-06-17","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/58877.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/58877.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/58877","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PLS', '130', 2003, 'Acrescenta dispositivos à Lei Complementar nº 101, de 4 de maio de 2000, que estabelece normas de finanças públicas voltadas para a responsabilidade na gestão fiscal e dá outras providências, a fim de determinar a disponibilização, em tempo real, de informações pormenorizadas sobre a execução orçamentária e financeira da União, dos Estados, do Distrito Federal e dos Municípios.', 'Senado', '56700', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/56700', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"56700","descricao_identificacao":"PLS 130/2003","data_apresentacao":"2003-04-14","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/56700.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/56700.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/56700","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PLS', '532', 2003, 'Altera os arts 16, 68, 81, 82, 86 e revoga o § 7º do art. 68 da Lei 9.610, de 19 de fevereiro de 1998, para disciplinar autoria e exibição pública de obras audiovisuais e cinematográficas.', 'Senado', '65050', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/65050', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"65050","descricao_identificacao":"PLS 532/2003","data_apresentacao":"2003-12-18","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/65050.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/65050.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/65050","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PLS', '195', 2004, 'Inclui parágrafo único no art. 31 da Lei nº 8.078, de 11 de setembro de 1990, para dispor que a oferta e apresentação de produtos ou serviços devem incluir o seu preço sem o valor do imposto sobre circulação de mercadorias e serviços e dos demais tributos sobre eles incidentes.', 'Senado', '68806', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/68806', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"68806","descricao_identificacao":"PLS 195/2004","data_apresentacao":"2004-06-29","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/68806.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/68806.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/68806","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PRS', '5', 2004, 'Altera o § 5º do art. 4º da Resolução nº 96, de 1989. (inclui entre as condições para solicitação de autorização de operação de crédito pela União, o cumprimento dos dispositivos pertinentes da da Lei nº 101, de 2000 - Lei de Responsabilidade Fiscal).', 'Senado', '66169', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/66169', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"66169","descricao_identificacao":"PRS 5/2004","data_apresentacao":"2004-02-16","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/66169.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/66169.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/66169","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PLS', '211', 2005, 'Altera o inciso III do art. 31 da Lei nº 8.987, de 13 de fevereiro de 1995, e inclui parágrafo no art. 35 da Lei nº 10.233, de 5 de junho de 2001, para prever publicação, na rede mundial de computadores (Internet), das informações acerca da gestão das prestadoras de serviços públicos e discrimina quais informações devem ser prestadas pelas concessionárias de rodovias.', 'Senado', '74106', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/74106', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"74106","descricao_identificacao":"PLS 211/2005","data_apresentacao":"2005-06-08","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/74106.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/74106.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/74106","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PLS', '214', 2005, 'Altera a Lei nº 7.827, de 27 de setembro de 1989, que regulamenta o art. 159, inciso I, alínea c, da Constituição Federal, institui o Fundo Constitucional de Financiamento do Norte - FNO, o Fundo Constitucional de Financiamento do Nordeste - FNE e o Fundo Constitucional de Financiamento do Centro-Oeste - FCO, e dá outras providências, de forma a incluir condicionantes relativos à biodiversidade amazônica na aplicação dos recursos do FNO.', 'Senado', '74117', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/74117', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"74117","descricao_identificacao":"PLS 214/2005","data_apresentacao":"2005-06-09","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/74117.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/74117.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/74117","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PEC', '24', 2012, 'Institui o Fundo Nacional de Desenvolvimento da Segurança Pública.', 'Senado', '105470', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/105470', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"105470","descricao_identificacao":"PEC 24/2012","data_apresentacao":"2012-05-09","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":32,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/105470.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/105470.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/105470","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PLS', '76', 2012, 'Adota medidas para informar os consumidores acerca de tributos que incidem diretamente sobre bens e serviços, conforme o disposto no § 5° do art. 150 da Constituição Federal.', 'Senado', '104801', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/104801', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"104801","descricao_identificacao":"PLS 76/2012","data_apresentacao":"2012-03-29","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":4,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/104801.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/104801.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/104801","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PLS', '141', 2012, 'Veda o segredo de justiça nos procedimentos investigatórios e processuais em que agente público seja investigado ou acusado e dá outras providências.', 'Senado', '105437', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/105437', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"105437","descricao_identificacao":"PLS 141/2012","data_apresentacao":"2012-05-08","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/105437.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/105437.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/105437","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PRS', '30', 2012, 'Determina o registro do nome do Presidente ou da Presidenta, conforme o caso, nas atas das sessões.', 'Senado', '106546', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/106546', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"106546","descricao_identificacao":"PRS 30/2012","data_apresentacao":"2012-07-12","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/106546.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/106546.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/106546","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PLS', '98', 2013, 'Altera o art. 93 e acrescenta os arts. 99-A, 124-A e 124-B à Lei nº 8.666, de 21 de junho de 1993, que regulamenta o art. 37, inciso XXI da Constituição Federal, institui normas para licitações e contratos da Administração Pública e dá outras providências, para estabelecer pena para o servidor que divulgar a identificação das pessoas que tenham retirado o ato de convocação ou sido convidados para certame licitatório, definir o alcance das penas previstas na Lei e para estabelecer diretrizes básicas de transparência nos processos licitatórios.', 'Senado', '111867', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/111867', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"111867","descricao_identificacao":"PLS 98/2013","data_apresentacao":"2013-03-26","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/111867.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/111867.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/111867","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PLS', '160', 2013, 'Prever a destinação de no mínimo cinco por cento dos recursos do Fundo Partidário para promoção da participação política dos afrodescendentes.', 'Senado', '112548', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/112548', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"112548","descricao_identificacao":"PLS 160/2013","data_apresentacao":"2013-05-07","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/112548.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/112548.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/112548","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PLS', '261', 2013, 'Altera os arts. 22 e 93, e acrescenta os arts. 33-A, 99-A e 124-A à Lei nº 8.666, de 21 de junho de 1993, que regulamenta o art. 37, inciso XXI, da Constituição Federal, institui normas para licitações e contratos da Administração Pública e dá outras providências, para redefinir a modalidade de licitação convite, estabelecer pena para o servidor que divulgar a identificação das pessoas que tenham retirado o ato de convocação ou sido convidados para certame licitatório, definir o alcance das penas previstas na Lei e estabelecer diretrizes básicas de transparência nos processos licitatórios, entre outras providências.', 'Senado', '113453', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/113453', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"113453","descricao_identificacao":"PLS 261/2013","data_apresentacao":"2013-07-02","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/113453.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/113453.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/113453","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PRS', '76', 2013, 'Altera a Resolução do Senado Federal nº 20, de 1993 (Código de Ética e Decoro Parlamentar), a fim de tornar mais transparentes os procedimentos realizados pelo Conselho de Ética e Decoro Parlamentar, e dá outras providências.', 'Senado', '114739', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/114739', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"114739","descricao_identificacao":"PRS 76/2013","data_apresentacao":"2013-10-10","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/114739.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/114739.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/114739","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PEC', '30', 2014, 'Acrescenta o art. 27-A, altera o § 3º do art. 32 e acrescenta § 2º ao art. 75, todos da Constituição Federal, bem como insere artigo no Ato das Disposições Constitucionais Transitórias; com o objetivo de fixar limite máximo para as despesas das Assembleias Legislativas dos Estados, da Câmara Legislativa do Distrito Federal e dos Tribunais de Contas dos Estados e do Distrito Federal.', 'Senado', '118418', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/118418', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"118418","descricao_identificacao":"PEC 30/2014","data_apresentacao":"2014-08-06","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":31,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/118418.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/118418.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/118418","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PLS', '101', 2014, 'Altera o Código de Processo Penal para prever nova modalidade de prisão preventiva: em caso de flagrante de crime de racismo ou injúria racial, como recurso pedagógico, no interesse da sociedade.', 'Senado', '116625', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/116625', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"116625","descricao_identificacao":"PLS 101/2014","data_apresentacao":"2014-03-25","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/116625.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/116625.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/116625","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PLS', '166', 2014, 'Dispõe sobre medidas que regulem a expansão do plantio de soja na Amazônia Legal.', 'Senado', '117456', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/117456', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"117456","descricao_identificacao":"PLS 166/2014","data_apresentacao":"2014-05-07","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/117456.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/117456.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/117456","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PDS', '5', 2015, 'Susta a Instrução Normativa - TCU nº 74, de 11 de fevereiro de 2015, que "dispõe sobre a fiscalização do Tribunal de Contas da União, com base no art. 3º da Lei nº 8.443/1992, quanto à organização do processo de celebração de acordo de leniência pela administração pública federal, nos termos da Lei 12.846/2013.', 'Senado', '119700', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/119700', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"119700","descricao_identificacao":"PDS 5/2015","data_apresentacao":"2015-02-19","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/119700.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/119700.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/119700","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PLS', '29', 2015, 'Regulamenta o inciso II do § 1° e o § 4º do art. 225 da Constituição; os arts. 1, 8, j, 10, c, 15 e 16, §§ 3 e 4 da Convenção sobre Diversidade Biológica, promulgada pelo Decreto nº 2.519, de 16 de março de 1998; dispõe sobre o acesso ao patrimônio genético; sobre a proteção e o acesso ao conhecimento tradicional associado; sobre a repartição de benefícios para conservação e uso sustentável da biodiversidade; e dá outras providências.', 'Senado', '119693', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/119693', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"119693","descricao_identificacao":"PLS 29/2015","data_apresentacao":"2015-02-12","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/119693.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/119693.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/119693","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PLS', '570', 2015, 'Altera a Lei Complementar nº 101, de 4 de maio de 2000, que estabelece normas de finanças públicas voltadas para a responsabilidade na gestão fiscal e dá outras providências, a fim de normatizar a transparência das informações sobre a execução orçamentária e financeira da União, dos Estados, do Distrito Federal e dos Municípios.', 'Senado', '122923', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/122923', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"122923","descricao_identificacao":"PLS 570/2015","data_apresentacao":"2015-08-31","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/122923.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/122923.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/122923","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PRS', '13', 2015, 'Altera o Regimento Interno do Senado Federal para criar a Comissão Permanente de Transparência e Governança Pública.', 'Senado', '120117', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/120117', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"120117","descricao_identificacao":"PRS 13/2015","data_apresentacao":"2015-03-17","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/120117.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/120117.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/120117","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PRS', '16', 2015, 'Institui, no âmbito do Senado Federal, a Frente Parlamentar para a Transparência dos Gastos Públicos.', 'Senado', '120367', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/120367', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"120367","descricao_identificacao":"PRS 16/2015","data_apresentacao":"2015-03-25","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/120367.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/120367.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/120367","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PEC', '16', 2016, 'Acrescenta o art. 81-A à Constituição Federal, para prever a possibilidade de revogação dos mandatos de Presidente e Vice-Presidente da República mediante referendo.', 'Senado', '125453', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/125453', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"125453","descricao_identificacao":"PEC 16/2016","data_apresentacao":"2016-04-06","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":30,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/125453.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/125453.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/125453","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PLS', '43', 2016, 'Modifica a Lei nº 9.504, de 30 de setembro de 1997, para facultar a partidos ou coligações o registro de candidatos que promovam campanha eleitoral exclusivamente pela Internet.', 'Senado', '124838', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/124838', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"124838","descricao_identificacao":"PLS 43/2016","data_apresentacao":"2016-02-18","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/124838.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/124838.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/124838","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PLS', '325', 2017, 'Institui a gestão compartilhada, destinada ao acompanhamento orçamentário, financeiro e físico da execução de obras, da prestação de serviços públicos e de aquisições de materiais e equipamentos por grupos de cidadãos organizados em aplicativos agregadores disponíveis na internet ou na telefonia celular.', 'Senado', '130834', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/130834', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"130834","descricao_identificacao":"PLS 325/2017","data_apresentacao":"2017-09-14","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/130834.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/130834.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/130834","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PLS', '355', 2018, 'Prevê a concessão de pensão especial, mensal, vitalícia e intransferível às vítimas de escalpelamento provocado por volantes, eixos ou partes moveis de motores de embarcação.', 'Senado', '134041', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/134041', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"134041","descricao_identificacao":"PLS 355/2018","data_apresentacao":"2018-08-07","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/134041.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/134041.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/134041","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb),
    ('PRS', '44', 2018, 'Institui a Frente Parlamentar em defesa da República Árabe Saaraui Democrática e dá outras providências.', 'Senado', '134225', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/134225', 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505', 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505', '{"proposicao_id_api":"134225","descricao_identificacao":"PRS 44/2018","data_apresentacao":"2018-09-05","casa":"SF","codigo_parlamentar_senado":3394,"indicador_autor_principal_endpoint_senador":"Sim","indicador_outros_autores_endpoint_senador":"Não","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSB","uf_autor_no_protocolo":"AP","autor_nome":"João Capiberibe","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/3394/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/134225.json","detalhe_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/134225.json","public_url":"https://www25.senado.leg.br/web/atividade/materias/-/materia/134225","coverage_id":"joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505","coverage_scope":"inventario_completo_senado_autoria_substantiva_2003_2018_20260505","lote":"A","tabela_alvo":"projetos_lei","legislacao_mandato_executivo_mixed":false,"curation_batch_id":"joao-capiberibe-senado-lote-a-20260505","snapshot_consulta_em":"2026-05-06T01:24:30.640Z"}'::jsonb)
) AS v(
  tipo,
  numero,
  ano,
  ementa,
  fonte,
  proposicao_id_api,
  url_inteiro_teor,
  coverage_id,
  coverage_scope,
  metadata
);

DO $$
DECLARE
  cand_id uuid;
  uncovered_year_count int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'joao-capiberibe';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'joao-capiberibe: validacao de mandato Senado pulada porque candidato nao existe neste banco local/CI minimo';
    RETURN;
  END IF;

  SELECT count(DISTINCT seed.ano) INTO uncovered_year_count
  FROM _seed_joao_capiberibe_senado_lote_a_projetos seed
  WHERE NOT EXISTS (
    SELECT 1
    FROM historico_politico hp
    WHERE hp.candidato_id = cand_id
      AND COALESCE(hp.tipo_evento, 'mandato') = 'mandato'
      AND (hp.cargo ILIKE '%Senador%' OR hp.cargo_canonico = 'Senador')
      AND UPPER(COALESCE(hp.estado, '')) = 'AP'
      AND COALESCE(hp.periodo_inicio, 9999) <= seed.ano
      AND COALESCE(hp.periodo_fim, 9999) >= seed.ano
  );

  IF uncovered_year_count <> 0 THEN
    RAISE EXCEPTION 'Pre-condicao joao-capiberibe: existem % anos de proposicoes Senado sem cobertura em mandato Senado/AP', uncovered_year_count;
  END IF;
END $$;

WITH target AS (
  SELECT c.id AS candidato_id
  FROM candidatos c
  WHERE c.slug = 'joao-capiberibe'
)
INSERT INTO projetos_lei (
  candidato_id,
  tipo,
  numero,
  ano,
  ementa,
  fonte,
  proposicao_id_api,
  url_inteiro_teor,
  coverage_id,
  coverage_scope,
  metadata
)
SELECT
  target.candidato_id,
  seed.tipo,
  seed.numero,
  seed.ano,
  seed.ementa,
  seed.fonte,
  seed.proposicao_id_api,
  seed.url_inteiro_teor,
  seed.coverage_id,
  seed.coverage_scope,
  seed.metadata
FROM target
CROSS JOIN _seed_joao_capiberibe_senado_lote_a_projetos AS seed
ON CONFLICT (candidato_id, proposicao_id_api) DO NOTHING;

DO $$
DECLARE
  cand_id uuid;
  total_count int;
  target_count int;
  scope_count int;
  lme_count int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'joao-capiberibe';

  IF cand_id IS NULL THEN
    RAISE NOTICE 'joao-capiberibe: pos-condicao pulada porque candidato nao existe neste banco local/CI minimo';
    RETURN;
  END IF;

  SELECT count(*) INTO total_count
  FROM projetos_lei
  WHERE candidato_id = cand_id;

  SELECT count(*) INTO target_count
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND fonte = 'Senado'
    AND proposicao_id_api IN ('58877', '56700', '65050', '68806', '66169', '74106', '74117', '105470', '104801', '105437', '106546', '111867', '112548', '113453', '114739', '118418', '116625', '117456', '119700', '119693', '122923', '120117', '120367', '125453', '124838', '130834', '134041', '134225');

  SELECT count(*) INTO scope_count
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND coverage_id = 'joao-capiberibe-senado-completo-autoria-substantiva-2003-2018-20260505'
    AND coverage_scope = 'inventario_completo_senado_autoria_substantiva_2003_2018_20260505';

  SELECT count(*) INTO lme_count
  FROM legislacao_mandato_executivo
  WHERE candidato_id = cand_id;

  IF target_count <> 28 THEN
    RAISE EXCEPTION 'Pos-apply joao-capiberibe: esperadas 28 rows alvo Senado em projetos_lei, encontradas %', target_count;
  END IF;

  IF total_count <> 28 THEN
    RAISE EXCEPTION 'Pos-apply joao-capiberibe: total projetos_lei esperado 28, encontrado %', total_count;
  END IF;

  IF scope_count <> 28 THEN
    RAISE EXCEPTION 'Pos-apply joao-capiberibe: esperadas 28 rows com coverage_id/scope alvo, encontradas %', scope_count;
  END IF;

  IF lme_count <> 0 THEN
    RAISE EXCEPTION 'Pos-apply joao-capiberibe: legislacao_mandato_executivo deve permanecer 0, encontrado %', lme_count;
  END IF;

  RAISE NOTICE 'Pos-apply joao-capiberibe Senado Lote A: projetos_lei=% coverage_scope=% legislacao_mandato_executivo=%', total_count, scope_count, lme_count;
END $$;
