-- ============================================
-- Fluxo 5B expansao parlamentar Senado
-- Seed parcial ampliado: Lote B Flavio Bolsonaro / projetos_lei
-- ============================================
-- DRAFT: nao aplicar ao Supabase remoto sem dry-run estreito e autorizacao
-- explicita do usuario neste prompt nao foi concedida (artefato fica como
-- draft local). Quando autorizado, aplicar com:
--   supabase db push --linked --dry-run
-- e em seguida:
--   supabase db push --linked
--
-- Fonte oficial: Senado Federal - Dados Abertos (Atividade Legislativa)
--   https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json
--   https://legis.senado.leg.br/dadosabertos/materia/{codigo}
--   https://legis.senado.leg.br/dadosabertos/materia/autoria/{codigo}
--   Pagina publica: https://www25.senado.leg.br/web/atividade/materias/-/materia/{codigo}
--
-- Snapshot deste lote: 2026-05-01 (versao do servico legado: 7).
-- Nota: endpoint legado /dadosabertos/senador/{codigo}/autorias.json esta em
-- descontinuacao (DataDepreciacao 2025-03-18; DataDesativacaoCompleta
-- 2026-02-01). Substituto oficial:
--   https://legis.senado.leg.br/dadosabertos/processo
-- A migracao para o novo endpoint vira como follow-up em proximo lote;
-- esta coleta ainda foi obtida com sucesso em 2026-05-01.
--
-- Artefato de auditoria:
--   fonte interna de curadoria
-- Coverage scope: inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501
-- Linhas verificadas: 62
-- Filtro: IndicadorAutorPrincipal=Sim (endpoint senador/5894/autorias.json)
--   E NumOrdemAutor=1 (endpoint materia/autoria/{codigo}) E
--   CodigoParlamentar=5894 E SiglaSubtipoMateria IN
--   (PL, PEC, PLP, PDL, PCE, PRS).
--
-- Esta migration NAO escreve em legislacao_mandato_executivo.
-- Esta migration NAO altera nem deleta as 5 rows aplicadas no Lote A
--   (PEC 32/2019, PL 2393/2019, PL 4475/2021, PL 5593/2025, PL 1019/2026
--    com proposicao_id_api 135977, 136390, 151329, 171423, 172949).
-- Esta migration NAO popula tema, destaque, destaque_motivo nem situacao
--   (campos editoriais/curatoriais, fora do contrato bruto de ingest oficial).
-- Esta migration NAO inclui requerimentos (REQ, RQS, RQN, R.S), denuncias
--   (DEN) ou peticoes (PET); 111 dessas autorias principais ficam fora de
--   projetos_lei por escopo de tabela.
-- Esta migration NAO promove status para inventario_completo: ALERJ
--   (Assembleia Legislativa do RJ, mandato 1991-2018) permanece como
--   limite estrutural fora desta fonte; status publico continua
--   "ampliado_parcial".
--
-- coverage_id permanece NULL nestas rows (somente coverage_scope e
-- metadata populados); o registro em COMPLETE_PARLAMENTAR_AUTHORSHIP_COVERAGE
-- nao deve ser estendido a flavio-bolsonaro neste lote.
-- ============================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM candidatos c
    WHERE c.slug = 'flavio-bolsonaro'
  ) THEN
    RAISE EXCEPTION 'flavio-bolsonaro nao encontrado em candidatos';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM candidatos c
    JOIN historico_politico hp ON hp.candidato_id = c.id
    WHERE c.slug = 'flavio-bolsonaro'
      AND hp.tipo_evento = 'mandato'
      AND (hp.cargo ILIKE '%Senador%' OR hp.cargo_canonico = 'Senador')
      AND hp.estado = 'RJ'
      AND hp.periodo_inicio <= 2019
  ) THEN
    RAISE EXCEPTION 'mandato Senador/RJ de flavio-bolsonaro com inicio <= 2019 nao encontrado em historico_politico';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM candidatos c
    JOIN historico_politico hp ON hp.candidato_id = c.id
    WHERE c.slug = 'flavio-bolsonaro'
      AND hp.tipo_evento = 'mandato'
      AND (
        hp.cargo ILIKE '%Presidente%'
        OR hp.cargo ILIKE '%Governador%'
        OR hp.cargo ILIKE '%Prefeito%'
        OR hp.cargo_canonico IN ('Presidente', 'Governador', 'Prefeito')
      )
  ) THEN
    RAISE EXCEPTION 'flavio-bolsonaro tem mandato de chefe do Executivo no historico_politico; rota parlamentar deste lote esta incorreta';
  END IF;
END $$;

-- Pre-condicao: schema uplift 20260430070000 (coverage_id, coverage_scope,
-- metadata) ja aplicado.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'projetos_lei' AND column_name = 'coverage_scope'
  ) THEN
    RAISE EXCEPTION 'Pre-apply: projetos_lei.coverage_scope ausente; aplique 20260430070000 primeiro';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'projetos_lei' AND column_name = 'metadata'
  ) THEN
    RAISE EXCEPTION 'Pre-apply: projetos_lei.metadata ausente; aplique 20260430070000 primeiro';
  END IF;
END $$;

-- Pre-condicao: as 5 rows do Lote A devem estar presentes intactas e nao
-- deve haver row legacy NULL pendente do cleanup 20260429235959.
DO $$
DECLARE
  cand_id uuid;
  lote_a_count int;
  legacy_null_count int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'flavio-bolsonaro';

  SELECT count(*) INTO lote_a_count
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND fonte = 'Senado'
    AND proposicao_id_api IN ('135977', '136390', '151329', '171423', '172949');
  IF lote_a_count <> 5 THEN
    RAISE EXCEPTION 'Pre-apply: esperadas 5 rows do Lote A intactas, encontradas %', lote_a_count;
  END IF;

  SELECT count(*) INTO legacy_null_count
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND fonte = 'Senado'
    AND proposicao_id_api IS NULL;
  IF legacy_null_count <> 0 THEN
    RAISE EXCEPTION 'Pre-apply: encontradas % rows legacy com proposicao_id_api NULL; aplique cleanup 20260429235959 primeiro', legacy_null_count;
  END IF;
END $$;

CREATE TEMP TABLE _seed_flavio_bolsonaro_parlamentar_lote_b_projetos ON COMMIT DROP AS
SELECT *
FROM (
VALUES
  ('PEC', '80', 2019, 'Altera os artigos 182 e 186 da Constituição Federal para dispor sobre a função social da propriedade urbana e rural.', 'Senado', '136894', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/136894', '{"proposicao_id_api":"136894","descricao_identificacao":"PEC 80/2019","data_apresentacao":"2019-05-21","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":27,"partido_autor_no_protocolo":"PSL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/136894","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '1451', 2019, 'Altera o Decreto nº 24.602, de 06 de julho de 1934, que “Dispõem sobre instalação e fiscalização de fábricas e comércio de armas municções, explosivos, produtos químicos agressivos e matérias correlatas”, para aperfeiçoar as regras sobre a matéria.', 'Senado', '135687', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/135687', '{"proposicao_id_api":"135687","descricao_identificacao":"PL 1451/2019","data_apresentacao":"2019-03-13","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/135687","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '1715', 2019, 'Revoga o § 2º do art. 342 do Código Penal para suprimir a possibilidade de extinção de punibilidade pela retratação no crime de falso testemunho ou falsa perícia.', 'Senado', '135938', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/135938', '{"proposicao_id_api":"135938","descricao_identificacao":"PL 1715/2019","data_apresentacao":"2019-03-21","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/135938","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '1867', 2019, 'Acrescenta o art. 320-B à Lei nº 9.503, de 23 de setembro de 1997, para limitar a remuneração de empresas prestadoras de serviços de instalação e manutenção de equipamentos de fiscalização eletrônica do trânsito em até 20% do montante aferido com a arrecadação de multas.', 'Senado', '136027', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/136027', '{"proposicao_id_api":"136027","descricao_identificacao":"PL 1867/2019","data_apresentacao":"2019-03-28","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/136027","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '2167', 2019, 'Altera os incisos III e VI do art. 21 da Lei nº 9.503, de 1997, que “Institui o Código de Trânsito Brasileiro” para disciplinar a aplicação das infrações e penalidades delas decorrentes por excesso de velocidade cometidas por veículos automotores, elétricos, reboques e semirreboques nas vias públicas somente quando aferidas por redutor eletrônico de velocidade fixo dotado de registro de velocidade em “display”, visíveis a distância segura mesmo em dias de visibilidade reduzida, sob pena de nulidade do ato administrativo correspondente.', 'Senado', '136253', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/136253', '{"proposicao_id_api":"136253","descricao_identificacao":"PL 2167/2019","data_apresentacao":"2019-04-08","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/136253","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '2169', 2019, 'Modifica a Lei nº 8.069, de 13 de julho de 1990, que dispõe sobre o Estatuto da Criança e do Adolescente, alterando para 07 (sete) anos o prazo da medida sócio-educativa de internação aplicável aos atos infracionais e, por conseguinte, altera o prazo da liberação compulsória para vinte e cinco anos de idade.', 'Senado', '136254', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/136254', '{"proposicao_id_api":"136254","descricao_identificacao":"PL 2169/2019","data_apresentacao":"2019-04-05","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/136254","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '2170', 2019, 'Altera a Lei nº 9.394, de 20 de dezembro de 1996, que estabelece as diretrizes e bases da educação nacional, para incluir empreendedorismo, matemática financeira, educação moral e cívica e organização social e política do Brasil - OSPB no rol dos temas transversais obrigatórios da educação básica.', 'Senado', '136251', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/136251', '{"proposicao_id_api":"136251","descricao_identificacao":"PL 2170/2019","data_apresentacao":"2019-04-05","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/136251","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '2171', 2019, 'Altera o Código Penal para definir o crime de arrastão.', 'Senado', '136252', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/136252', '{"proposicao_id_api":"136252","descricao_identificacao":"PL 2171/2019","data_apresentacao":"2019-04-05","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/136252","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '2175', 2019, 'Altera o Código Penal para prever agravamento de pena em razão do emprego de brinquedos, réplicas e simulacros de armas de fogo.', 'Senado', '136262', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/136262', '{"proposicao_id_api":"136262","descricao_identificacao":"PL 2175/2019","data_apresentacao":"2019-04-09","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/136262","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '2362', 2019, 'Revoga o Capítulo IV - Da Reserva Legal, da Lei nº 12.651, de 25 de maio de 2012, que dispõe sobre a proteção da vegetação nativa, para garantir o direito constitucional de propriedade.', 'Senado', '136371', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/136371', '{"proposicao_id_api":"136371","descricao_identificacao":"PL 2362/2019","data_apresentacao":"2019-04-16","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":2,"partido_autor_no_protocolo":"PSL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/136371","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '3071', 2019, 'Altera a Lei 13.756 de 2018 para incluir a Associação Brasileira Beneficente de Reabilitação -ABBR no destino da arrecadação das loterias.', 'Senado', '136918', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/136918', '{"proposicao_id_api":"136918","descricao_identificacao":"PL 3071/2019","data_apresentacao":"2019-05-22","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/136918","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '3132', 2019, 'Altera o Decreto-Lei nº 2.848, de 7 de dezembro de 1940 (Código Penal), para revogar a atenuante da menoridade e a redução dos prazos prescricionais ao menor de 21 (vinte e um) anos.', 'Senado', '136970', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/136970', '{"proposicao_id_api":"136970","descricao_identificacao":"PL 3132/2019","data_apresentacao":"2019-05-24","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/136970","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '3133', 2019, 'Altera o art. 64 do Decreto-Lei nº 2.848, de 7 de dezembro de 1940 – Código Penal, para prever que o condenado por estupro de menor de quatorze anos será considerado reincidente, independentemente de o novo crime ter sido cometido após passados mais de cinco anos do cumprimento ou da extinção da pena.', 'Senado', '136978', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/136978', '{"proposicao_id_api":"136978","descricao_identificacao":"PL 3133/2019","data_apresentacao":"2019-05-24","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/136978","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '3462', 2019, 'Altera o Decreto Lei nº 2.848, de 07 de dezembro de 1940 (Código Penal) para incluir como causa de aumento de pena na denunciação caluniosa a imputação falsa de crime hediondo.', 'Senado', '137241', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/137241', '{"proposicao_id_api":"137241","descricao_identificacao":"PL 3462/2019","data_apresentacao":"2019-06-06","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/137241","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '3589', 2019, 'Altera a Lei nº 5.991, de 17 de dezembro de 1973, que dispõe sobre o controle sanitário do comércio de drogas, medicamentos, insumos farmacêuticos e correlatos, e dá outras providências, para permitir a dispensação de medicamentos em todos os estabelecimentos comerciais.', 'Senado', '137330', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/137330', '{"proposicao_id_api":"137330","descricao_identificacao":"PL 3589/2019","data_apresentacao":"2019-06-13","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/137330","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '4640', 2019, 'Acrescenta o art. 25-A ao Decreto-Lei nº 2.848, de 7 de dezembro de 1940 – Código Penal, para prever a excludente de ilicitude designada por “suicídio por policial”.', 'Senado', '138227', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/138227', '{"proposicao_id_api":"138227","descricao_identificacao":"PL 4640/2019","data_apresentacao":"2019-08-20","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/138227","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '6479', 2019, 'Institui a região da Costa Verde, nos termos que especifica, como Área Especial de Interesse Turístico.', 'Senado', '140268', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/140268', '{"proposicao_id_api":"140268","descricao_identificacao":"PL 6479/2019","data_apresentacao":"2019-12-17","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"S/Partido","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/140268","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PLP', '132', 2019, 'Altera a Lei Complementar nº 159, de 19 de maio de 2017, que institui o Regime de Recuperação Fiscal dos Estados e do Distrito Federal, para dispor sobre a renúncia de receita em caso de comprovação de benefício fiscal futuro.', 'Senado', '136764', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/136764', '{"proposicao_id_api":"136764","descricao_identificacao":"PLP 132/2019","data_apresentacao":"2019-05-13","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/136764","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PLP', '214', 2019, 'Altera o art. 61-A da Lei Complementar n° 123, de 14 de dezembro de 2006, para regular a remuneração do investidor-anjo e excetuar as hipóteses de responsabilidade solidária.', 'Senado', '138702', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/138702', '{"proposicao_id_api":"138702","descricao_identificacao":"PLP 214/2019","data_apresentacao":"2019-09-11","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PSL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/138702","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '1174', 2020, 'Dispõe sobre a realização de Assembleias Gerais de Acionistas e Reuniões de Sócios com possibilidade de votação e participação a distância, por meio da rede mundial de computadores (internet) e do emprego de outras tecnologias, autoriza a utilização de mecanismos de registro eletrônico e dá outras providências', 'Senado', '141305', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/141305', '{"proposicao_id_api":"141305","descricao_identificacao":"PL 1174/2020","data_apresentacao":"2020-03-30","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"S/Partido","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/141305","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '3324', 2020, 'Altera a Lei nº 10.406, de 10 de janeiro de 2002 para autorizar a emissão de debêntures por sociedades limitadas e cooperativas.', 'Senado', '142510', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/142510', '{"proposicao_id_api":"142510","descricao_identificacao":"PL 3324/2020","data_apresentacao":"2020-06-16","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"REPUBLICANOS","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/142510","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PCE', '4', 2021, 'Requer a abertura de procedimento disciplinar c/c inquérito em face do Senador Jorge Kajuru, com fundamento nos arts. 25 e 32 do Regimento Interno do Senado Federal e no art. 20 da Resolução do Senado Federal nº 20, de 1993.', 'Senado', '148048', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/148048', '{"proposicao_id_api":"148048","descricao_identificacao":"PCE 4/2021","data_apresentacao":"2021-04-12","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"REPUBLICANOS","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/148048","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PCE', '6', 2021, 'Requer a abertura de procedimento disciplinar c/c inquérito em face do Senador Renan Calheiros, com fundamento nos arts. 17 e 20 da Resolução 20/1993 c/c os arts. 25 e 32, II, do Regimento Interno do Senado Federal.', 'Senado', '149150', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/149150', '{"proposicao_id_api":"149150","descricao_identificacao":"PCE 6/2021","data_apresentacao":"2021-07-15","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PATRIOTA","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/149150","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '2326', 2021, 'Altera a Lei nº 8.078, de 11 de setembro de 1990, para estabelecer parâmetros na oferta de produtos e serviços ao consumidor.', 'Senado', '148902', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/148902', '{"proposicao_id_api":"148902","descricao_identificacao":"PL 2326/2021","data_apresentacao":"2021-06-25","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PATRIOTA","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/148902","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '2327', 2021, 'Altera a Lei nº 12.305, de 2 de agosto de 2010, para tratar da logística reversa para baterias de veículos elétricos.', 'Senado', '148903', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/148903', '{"proposicao_id_api":"148903","descricao_identificacao":"PL 2327/2021","data_apresentacao":"2021-06-25","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PATRIOTA","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/148903","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '2734', 2021, 'Altera a Lei nº 8.906, de 4 de julho de 1994, e a Lei nº 10.826, de 22 de dezembro de 2003, para conceder porte de arma de fogo aos advogados, para defesa pessoal.', 'Senado', '149286', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/149286', '{"proposicao_id_api":"149286","descricao_identificacao":"PL 2734/2021","data_apresentacao":"2021-08-05","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PATRIOTA","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/149286","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '4476', 2021, 'Altera o art. 218-A do Decreto-Lei nº 2.848, de 7 de dezembro de 1940 (Código Penal), para tipificar a conduta de submeter menor de 14 (catorze) anos a presenciar evento cultural ou artístico que contenha nudez ou simule atos de lascívia ou sexo explícito.', 'Senado', '151330', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/151330', '{"proposicao_id_api":"151330","descricao_identificacao":"PL 4476/2021","data_apresentacao":"2021-12-15","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/151330","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PLP', '157', 2021, 'Autoriza o Poder Executivo a criar a Região Administrativa Integrada de Desenvolvimento Sustentável da Costa Verde/RJ e o Programa Especial de Desenvolvimento do Polo Turístico, integrado pelos municípios de Angra dos Reis, Paraty e Mangaratiba.', 'Senado', '150245', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/150245', '{"proposicao_id_api":"150245","descricao_identificacao":"PLP 157/2021","data_apresentacao":"2021-10-13","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PATRIOTA","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/150245","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PCE', '1', 2022, 'Requer abertura de procedimento disciplinar e inquérito em face do Senador Randolfe Rodrigues, com fundamento nos arts. 25 e 32 do Regimento Interno do Senado Federal e no art. 20 da Resolução do Senado Federal 20, de 1993.', 'Senado', '151868', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/151868', '{"proposicao_id_api":"151868","descricao_identificacao":"PCE 1/2022","data_apresentacao":"2022-02-22","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/151868","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '828', 2022, 'Altera o Decreto-Lei nº 2.848, de 7 de dezembro de 1940 – Código Penal, para aumentar as penas previstas para o furto e receptação de petróleo ou seus derivados, gás natural ou suas frações recuperáveis, álcool etílico hidratado carburante ou demais combustíveis líquidos carburantes.', 'Senado', '152626', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/152626', '{"proposicao_id_api":"152626","descricao_identificacao":"PL 828/2022","data_apresentacao":"2022-04-05","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/152626","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '829', 2022, 'Altera o art. 129 do Decreto-Lei nº 2.848, de 7 de dezembro de 1940 (Código Penal), e o art. 1º da Lei nº 8.072, de 25 de julho de 1990, para incluir o parentesco civil na causa de aumento de pena de lesão corporal praticada contra autoridade ou agente descrito nos arts. 142 e 144 da Constituição Federal, integrantes do sistema prisional ou da Força Nacional de Segurança Pública, bem como para incluir no rol dos crimes hediondos a lesão corporal dolosa de natureza gravíssima e lesão corporal seguida de morte quando praticadas contra parentes por afinidade dos referidos agentes ou autoridades.', 'Senado', '152627', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/152627', '{"proposicao_id_api":"152627","descricao_identificacao":"PL 829/2022","data_apresentacao":"2022-04-05","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/152627","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '830', 2022, 'Altera a Lei nº 8.069, de 13 de julho de 1990 - Estatuto da Criança e do Adolescente, para aumentar as penas dos crimes previstos nos arts. 240, 241, 241-A a 241-D; bem como incluir a internet entre os possíveis meios de aliciamento, assédio, instigação ou constrangimento e, nesses casos, prever causa de aumento de pena para quem se vale de perfil em redes sociais para interagir com criança ou pratica abuso psicológico.', 'Senado', '152628', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/152628', '{"proposicao_id_api":"152628","descricao_identificacao":"PL 830/2022","data_apresentacao":"2022-04-05","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/152628","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '969', 2022, 'Altera a Lei nº 13.019, de 31 de julho de 2014, para incluir o esporte dentre as atividades previstas como pressuposto para dispensa de chamamento público.', 'Senado', '152773', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/152773', '{"proposicao_id_api":"152773","descricao_identificacao":"PL 969/2022","data_apresentacao":"2022-04-19","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/152773","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PCE', '2', 2023, 'Requer instauração de processo disciplinar (Denúncia) em face do Senador Randolfe Rodrigues.', 'Senado', '155771', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/155771', '{"proposicao_id_api":"155771","descricao_identificacao":"PCE 2/2023","data_apresentacao":"2023-02-06","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/155771","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PDL', '107', 2023, 'Susta os efeitos do Decreto nº 11.466, de 5 de abril 2023, que trata da metodologia para comprovação da capacidade econômico financeira dos prestadores de serviços públicos de abastecimento de água potável ou de esgotamento sanitário e o Decreto nº 11.467, de 5 de abril de 2023, que dispõe sobre a prestação regionalizada dos serviços públicos de saneamento básico, o apoio técnico e financeiro de que trata o art. 13 da Lei nº 14.026, de 15 de julho de 2020.', 'Senado', '156769', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/156769', '{"proposicao_id_api":"156769","descricao_identificacao":"PDL 107/2023","data_apresentacao":"2023-04-10","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/156769","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PDL', '193', 2023, 'Susta os efeitos do Decreto nº 11.615, de 21 de julho de 2023, que regulamenta a Lei nº 10.826, de 22 de dezembro de 2003, para estabelecer regras e procedimentos relativos à aquisição, ao registro, à posse, ao porte, ao cadastro e à comercialização nacional de armas de fogo, munições e acessórios, disciplinar as atividades de caça excepcional, de caça de subsistência, de tiro desportivo e de colecionamento de armas de fogo, munições e acessórios, disciplinar o funcionamento das entidades de tiro desportivo e dispor sobre a estruturação do Sistema Nacional de Armas - Sinarm.', 'Senado', '158826', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/158826', '{"proposicao_id_api":"158826","descricao_identificacao":"PDL 193/2023","data_apresentacao":"2023-07-25","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":11,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/158826","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '2109', 2023, 'Altera o Código Penal para prever que o ato preparatório no crime de massa é punível em caso de crime que implique lesão ou morte de três ou mais pessoas.', 'Senado', '157069', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/157069', '{"proposicao_id_api":"157069","descricao_identificacao":"PL 2109/2023","data_apresentacao":"2023-04-25","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/157069","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '3165', 2023, 'Altera a Lei nº 9.503, de 23 de setembro de 1997 (Código de Trânsito Brasileiro), para modificar as regras sobre remoção de veículo em caso de estacionamento proibido.', 'Senado', '158333', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/158333', '{"proposicao_id_api":"158333","descricao_identificacao":"PL 3165/2023","data_apresentacao":"2023-06-20","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/158333","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '5335', 2023, 'Altera a Lei 10.257, de 10 de julho de 200, para incluir normas sobre concessão de uso especial para fins de moradia e concede aos possuidores irregulares de imóveis urbanos até 80 m2 (oitenta metros quadrados) em terreno da União, do Estado ou Município, o título definitivo de propriedade do bem, na forma que dispõe.', 'Senado', '160817', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/160817', '{"proposicao_id_api":"160817","descricao_identificacao":"PL 5335/2023","data_apresentacao":"2023-11-06","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/160817","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '6043', 2023, 'Altera a Lei 9.472, de 16 de julho de 1997, para tornar obrigatório o bloqueio do código IMEI (Identificação Internacional de Equipamento Móvel) a contar da realização de boletim de ocorrência ou de outro documento equivalente emitido por órgão policial nas hipóteses de furto, roubo ou extravio de aparelho de telefone celular.', 'Senado', '161629', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/161629', '{"proposicao_id_api":"161629","descricao_identificacao":"PL 6043/2023","data_apresentacao":"2023-12-14","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/161629","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '6131', 2023, 'Altera os arts. 155 e 157 do Decreto-Lei nº 2.848, de 07 de dezembro de 1940 (Código Penal), para dispor sobre os crimes de furto e roubo praticados com a finalidade de a vítima ceder o uso de seu aparelho celular.', 'Senado', '161721', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/161721', '{"proposicao_id_api":"161721","descricao_identificacao":"PL 6131/2023","data_apresentacao":"2023-12-20","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/161721","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PRS', '19', 2023, 'Estabelece que as concessões de garantia pela União, direta ou indiretamente, em operações de crédito à exportação de valor superior a US$ 100 milhões (cem milhões de dólares dos Estados Unidos da América), deverão ser previamente autorizadas pelo Senado Federal.', 'Senado', '155978', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/155978', '{"proposicao_id_api":"155978","descricao_identificacao":"PRS 19/2023","data_apresentacao":"2023-03-02","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/155978","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PEC', '53', 2024, 'Dá nova redação à alínea “d” do inciso XXXVIII do art. 5º da Constituição Federal para excetuar da competência do Tribunal do Júri os crimes dolosos contra a vida praticados por integrantes de associação criminosa, milícia privada e organização criminosa.', 'Senado', '166887', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/166887', '{"proposicao_id_api":"166887","descricao_identificacao":"PEC 53/2024","data_apresentacao":"2024-12-19","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":28,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/166887","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '517', 2024, 'Altera a Lei nº 14.597, de 14 de junho de 2023, que institui a Lei Geral do Esporte, para estabelecer medidas de proteção ao atleta profissional, deveres e responsabilidades das organizações esportivas, bem como definir o crime de violência física e moral contra o atleta profissional e dá outras providências.', 'Senado', '162279', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/162279', '{"proposicao_id_api":"162279","descricao_identificacao":"PL 517/2024","data_apresentacao":"2024-02-29","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/162279","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '4082', 2024, 'Veda a concessão de liberdade provisória e aplicação de medidas cautelares diversas à prisão para presos em flagrante pela prática de crimes hediondos ou aqueles a ele equiparados.', 'Senado', '165920', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/165920', '{"proposicao_id_api":"165920","descricao_identificacao":"PL 4082/2024","data_apresentacao":"2024-10-25","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/165920","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PDL', '29', 2025, 'Susta o Decreto nº 12.341, de 23 de dezembro de 2024.', 'Senado', '167042', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/167042', '{"proposicao_id_api":"167042","descricao_identificacao":"PDL 29/2025","data_apresentacao":"2025-01-07","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/167042","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PDL', '96', 2025, 'Susta os efeitos a Portaria MAPA/SDA Nº 1179, de 05 setembro de 2024 e a Portaria SDA/MAPA Nº 1.244, de 18 de fevereiro de 2025.', 'Senado', '167313', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/167313', '{"proposicao_id_api":"167313","descricao_identificacao":"PDL 96/2025","data_apresentacao":"2025-02-21","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/167313","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PDL', '1165', 2025, 'Susta o Decreto nº 12.774, de 09 de dezembro de 2025.', 'Senado', '172022', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/172022', '{"proposicao_id_api":"172022","descricao_identificacao":"PDL 1165/2025","data_apresentacao":"2025-12-10","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/172022","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '494', 2025, 'Altera o art. 155 do Decreto-Lei nº 2.848, de 07 de dezembro de 1940 (Código Penal) para dispor sobre o crime de furto de aparelho de celular', 'Senado', '167238', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/167238', '{"proposicao_id_api":"167238","descricao_identificacao":"PL 494/2025","data_apresentacao":"2025-02-18","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/167238","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '1950', 2025, 'Dispõe da devolução dos descontos não autorizados em folha de pagamento dos benefícios previdenciários relativos a mensalidades de associações.', 'Senado', '168298', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/168298', '{"proposicao_id_api":"168298","descricao_identificacao":"PL 1950/2025","data_apresentacao":"2025-04-29","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/168298","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '3300', 2025, 'Altera a Lei 8.078, de 11 de setembro de 1990 (Código de Defesa do Consumidor), para estabelecer o direito à troca imotivada de produtos adquiridos no comércio físico ou eletrônico e dá outras providências.', 'Senado', '169490', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/169490', '{"proposicao_id_api":"169490","descricao_identificacao":"PL 3300/2025","data_apresentacao":"2025-07-08","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/169490","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '3846', 2025, 'Dispõe sobre a isenção de cobrança de taxas de pouso, decolagem ou uso de infraestrutura rodoviária por aeronaves civis de uso público em missões oficiais de segurança pública, saúde e defesa civil.', 'Senado', '169779', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/169779', '{"proposicao_id_api":"169779","descricao_identificacao":"PL 3846/2025","data_apresentacao":"2025-08-11","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/169779","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '3980', 2025, 'Dispõe sobre a obrigatoriedade de cobertura integral e prioritária, no âmbito do Sistema Único de Saúde (SUS), de exames diagnósticos especializados para identificação precoce do Transtorno do Espectro Autista (TEA) e dá outras providências.', 'Senado', '169904', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/169904', '{"proposicao_id_api":"169904","descricao_identificacao":"PL 3980/2025","data_apresentacao":"2025-08-13","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/169904","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '4244', 2025, 'Altera a Lei 2.848, de 7 de setembro de 1940 (Código Penal), para incluir como circunstância agravante, a prática de crime na presença de criança ou adolescente; e altera a Lei 11.343 de 23 de agosto de 2006 (Lei de Drogas), para incluir causa de aumento de pena.', 'Senado', '170061', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/170061', '{"proposicao_id_api":"170061","descricao_identificacao":"PL 4244/2025","data_apresentacao":"2025-08-27","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/170061","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '4597', 2025, 'Altera o Decreto-Lei nº 2.848, de 7 de dezembro de 1940 (Código Penal), para incluir como qualificadora do crime de homicídio o uso de drones ou dispositivos remotos ou automatizados que dificultem ou impossibilitem a defesa da vítima; modifica a Lei nº 10.826, de 22 de dezembro de 2003 (Estatuto do Desarmamento), para agravar condutas relacionadas ao uso de armamento com drones ou tecnologia autônoma; e altera a Lei nº 11.343, de 23 de agosto de 2006 (Lei de Drogas), para aumentar a pena em casos de crimes cometidos com o emprego desses meios tecnológicos.', 'Senado', '170485', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/170485', '{"proposicao_id_api":"170485","descricao_identificacao":"PL 4597/2025","data_apresentacao":"2025-09-16","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/170485","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '4598', 2025, 'Altera o Decreto Lei 2.848, de 7 de dezembro de 1940 (Código Penal), para incluir como circunstância agravante, a prática de crime contra a pessoa com deficiência ou neurodivergente e para estender a causa de aumento de pena, tornando-a aplicável independentemente do local da prática do crime.', 'Senado', '170486', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/170486', '{"proposicao_id_api":"170486","descricao_identificacao":"PL 4598/2025","data_apresentacao":"2025-09-16","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/170486","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '4963', 2025, 'Altera o Decreto-Lei nº 2.848, de 7 de dezembro de 1940 (Código Penal), para acrescentar parágrafos ao art. 272, e modifica a Lei nº 8.072, de 25 de julho de 1990, para incluir entre os crimes hediondos as hipóteses qualificadas de falsificação, corrupção, adulteração ou alteração de substância, produto alimentício ou bebidas destinadas a consumo com resultado lesão grave ou morte.', 'Senado', '170769', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/170769', '{"proposicao_id_api":"170769","descricao_identificacao":"PL 4963/2025","data_apresentacao":"2025-10-06","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/170769","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '5115', 2025, 'Altera as Lei nº 8.742, de 7 de dezembro de 1993, e nº 10.741, de 1º de outubro de 2003, para determinar a instalação de centros-dia para pessoas idosas atendidas no âmbito do Sistema Único de Assistência Social (Suas).', 'Senado', '170925', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/170925', '{"proposicao_id_api":"170925","descricao_identificacao":"PL 5115/2025","data_apresentacao":"2025-10-14","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/170925","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '5594', 2025, 'Altera o Decreto-Lei nº 2.848, de 7 de dezembro de 1940 (Código Penal), para agravar as penas do crime de atentado contra a segurança de transporte marítimo, fluvial ou aéreo, prever formas qualificadas quando da ocorrência de resultado lesivo e aperfeiçoar a modalidade culposa.', 'Senado', '171424', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/171424', '{"proposicao_id_api":"171424","descricao_identificacao":"PL 5594/2025","data_apresentacao":"2025-11-03","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/171424","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '5646', 2025, 'Altera a Lei nº 7.565, de 19 de dezembro de 1986 (Código Brasileiro de Aeronáutica), para dispor sobre a interceptação, neutralização e abate de Aeronaves Remotamente Pilotadas (ARP) por órgãos de segurança pública, bem como para regulamentar o emprego de Contramedidas Anti-Drones (CAD) no território nacional, em situações de ameaça à segurança pública, à vida humana ou à ordem nacional.', 'Senado', '171453', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/171453', '{"proposicao_id_api":"171453","descricao_identificacao":"PL 5646/2025","data_apresentacao":"2025-11-04","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/171453","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PEC', '4', 2026, 'Altera a Constituição Federal para determinar a inelegibilidade para o cargo de Presidente da República no período subsequente.', 'Senado', '172830', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/172830', '{"proposicao_id_api":"172830","descricao_identificacao":"PEC 4/2026","data_apresentacao":"2026-03-02","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":30,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/172830","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb),
  ('PL', '1400', 2026, 'Altera a Lei nº 11.340, de 7 de agosto de 2006, para autorizar a autoridade policial a conceder, em caráter imediato, medidas protetivas de urgência em casos de violência doméstica e familiar contra a mulher, e dispõe sobre o controle judicial subsequente.', 'Senado', '173320', 'https://www25.senado.leg.br/web/atividade/materias/-/materia/173320', '{"proposicao_id_api":"173320","descricao_identificacao":"PL 1400/2026","data_apresentacao":"2026-03-25","casa":"SF","indicador_autor_principal_endpoint_senador":"Sim","num_ordem_autor":1,"total_autores":1,"partido_autor_no_protocolo":"PL","uf_autor_no_protocolo":"RJ","fonte":"Senado Federal Dados Abertos","autorias_endpoint":"https://legis.senado.leg.br/dadosabertos/senador/5894/autorias.json","autoria_endpoint":"https://legis.senado.leg.br/dadosabertos/materia/autoria/173320","coverage_scope":"inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501","lote":"B","curation_batch_id":"flavio-bolsonaro-parlamentar-lote-b-20260501","snapshot_consulta_em":"2026-05-01T22:30:00Z"}'::jsonb)
) AS v(
  tipo,
  numero,
  ano,
  ementa,
  fonte,
  proposicao_id_api,
  url_inteiro_teor,
  metadata
);

-- Idempotente: ON CONFLICT DO NOTHING. Re-rodar nao duplica nem sobrescreve.
WITH target AS (
  SELECT c.id AS candidato_id
  FROM candidatos c
  WHERE c.slug = 'flavio-bolsonaro'
)
INSERT INTO projetos_lei (
  candidato_id,
  tipo,
  numero,
  ano,
  ementa,
  fonte,
  proposicao_id_api,
  url_inteiro_teor,
  coverage_id,
  coverage_scope,
  metadata
)
SELECT
  target.candidato_id,
  seed.tipo,
  seed.numero,
  seed.ano,
  seed.ementa,
  seed.fonte,
  seed.proposicao_id_api,
  seed.url_inteiro_teor,
  NULL::text AS coverage_id,
  'inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501'::text AS coverage_scope,
  seed.metadata
FROM target
CROSS JOIN _seed_flavio_bolsonaro_parlamentar_lote_b_projetos AS seed
ON CONFLICT (candidato_id, proposicao_id_api) DO NOTHING;

-- Pos-apply: 62 rows do Lote B presentes; 5 do Lote A intactas; total Senado
-- = 67; coverage_id continua NULL para todas as rows do Flavio (status
-- ampliado_parcial, sem registro em COMPLETE_PARLAMENTAR_AUTHORSHIP_COVERAGE);
-- nenhum outro slug afetado.
DO $$
DECLARE
  cand_id uuid;
  lote_b_count int;
  lote_a_count int;
  total_senado int;
  with_target_scope int;
  null_coverage_id int;
  any_coverage_id_set int;
BEGIN
  SELECT id INTO cand_id FROM candidatos WHERE slug = 'flavio-bolsonaro';

  SELECT count(*) INTO lote_b_count
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND fonte = 'Senado'
    AND proposicao_id_api IN (
    '136894', '135687', '135938', '136027', '136253', '136254', '136251', '136252',
    '136262', '136371', '136918', '136970', '136978', '137241', '137330', '138227',
    '140268', '136764', '138702', '141305', '142510', '148048', '149150', '148902',
    '148903', '149286', '151330', '150245', '151868', '152626', '152627', '152628',
    '152773', '155771', '156769', '158826', '157069', '158333', '160817', '161629',
    '161721', '155978', '166887', '162279', '165920', '167042', '167313', '172022',
    '167238', '168298', '169490', '169779', '169904', '170061', '170485', '170486',
    '170769', '170925', '171424', '171453', '172830', '173320'
    );
  IF lote_b_count <> 62 THEN
    RAISE EXCEPTION 'Pos-apply: esperadas 62 rows do Lote B em projetos_lei (Senado), encontradas %', lote_b_count;
  END IF;

  SELECT count(*) INTO lote_a_count
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND fonte = 'Senado'
    AND proposicao_id_api IN ('135977', '136390', '151329', '171423', '172949');
  IF lote_a_count <> 5 THEN
    RAISE EXCEPTION 'Pos-apply: Lote A perdeu rows; esperado 5, encontrado %', lote_a_count;
  END IF;

  SELECT count(*) INTO total_senado
  FROM projetos_lei
  WHERE candidato_id = cand_id AND fonte = 'Senado';
  IF total_senado <> 67 THEN
    RAISE EXCEPTION 'Pos-apply: total Senado esperado 67 (5 Lote A + 62 Lote B), encontrado %', total_senado;
  END IF;

  SELECT count(*) INTO with_target_scope
  FROM projetos_lei
  WHERE candidato_id = cand_id
    AND fonte = 'Senado'
    AND coverage_scope = 'inventario_parlamentar_ampliado_parcial_senado_lote_b_20260501';
  IF with_target_scope <> 62 THEN
    RAISE EXCEPTION 'Pos-apply: esperadas 62 rows com coverage_scope alvo, encontradas %', with_target_scope;
  END IF;

  SELECT count(*) INTO any_coverage_id_set
  FROM projetos_lei
  WHERE candidato_id = cand_id AND coverage_id IS NOT NULL;
  IF any_coverage_id_set <> 0 THEN
    RAISE EXCEPTION 'Pos-apply: encontradas % rows do flavio-bolsonaro com coverage_id NAO NULL; status ampliado_parcial requer coverage_id NULL', any_coverage_id_set;
  END IF;

  RAISE NOTICE 'Pos-apply flavio-bolsonaro Lote B: lote_b=% lote_a=% total_senado=% scope_alvo=% coverage_id_nao_nulo=%',
    lote_b_count, lote_a_count, total_senado, with_target_scope, any_coverage_id_set;
END $$;
